### ISSUE TITLE
typos in _common.scss

### ISSUE THREAD

**Issue by glitsj16** [tista500/Adapta#102]
Hi, just a FYI on 2 typos I noticed in _common.scss (current git version):

(1) 'linkind' should be 'linking'
    * gtk-3.20/_common.scss --> line 1351
    * gtk-3.22/_common.scss --> line 1335

(2) 'istead' should be 'instead'
    * gtk-3.20/_common.scss --> line 4471
    * gtk-3.22/_common.scss --> line 4437

Many thanks for this excellent theming project,

glitsj16
 ```
 $ lsb_release -d
Description:	Arch Linux

$ pacman -Qi gtk3
Version         : 3.20.5-1

$ env | grep DESKTOP_SESSION
 DESKTOP_SESSION=gnome

$ pacman -Qi gtk-theme-adapta-git
Version         : 876.6dfaef7-1
 ```

**Comment by tista500** [comment]
@glitsj16,

Nice finding and then fIx was committed: https://github.com/tista500/Adapta/commit/4fc0d9d05c300cda3fe2e29f4cdd3ffc21867456


Regards.
