### ISSUE TITLE
Inkscape crash with small palettes

### ISSUE THREAD

**Issue by dcpurton** [tista500/Adapta#103]
Inkscape crashes with the Adpata themes when you load a palatte with a small enough number of colours in it that no scroll bar is needed. The problem does not occur with other themes.

 ```
 * Distribution - Debian Stretch
 * Gtk+ 3.0 version - 3.20.4
 * Gtk+ 2.0 version - 2.24.30
 * Desktop environment - Awesome WM
 * Inkscape version - 0.91
 * Adapta version - git commit 3ea4c1f
 ```

**Steps to reproduce**

1. Open inkscape
2. Select a palatte with a small number of colours, e.g. websafe22
3. Inkscape freezes

**Comment by tista500** [comment]
@dcpurton,

Reproduced and Confirmed.

Regards.

**Comment by tista500** [comment]
@dcpurton,

Fix was committed: https://github.com/tista500/Adapta/commit/9dba9932258282a5417b38e2ad16b669a5e8fc8a

Please check if that commit could solve this issue...

Regards.

**Comment by dcpurton** [comment]
Fixed, thanks!
