### ISSUE TITLE
GParted almost invisible buttons

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#104]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.20.4
 * Desktop environment - GNOME 3.20.1
 ```

**Adapta version (if you knew)**
3.21.1.204

**Related Application and/or Shell theming (or name of widget)**
GParted

**Actual issue**
Disabled buttons have almost no contrast to the background.
![gparted](https://cloud.githubusercontent.com/assets/526104/15453357/edc85106-2012-11e6-8829-333ec39b10a9.png)

**Steps to reproduce (if you knew)**
Open the application

**Expected behaviour**
More contrast to the background for disable buttons.

**Comment by tista500** [comment]
Gtk+ 2.0 never re-colour symbolic svg files.

Invalid.

**Comment by pschichtel** [comment]
Invalid as in this is a gtk2 problem?
