### ISSUE TITLE
Top bar menu's not aligned to the left

### ISSUE THREAD

**Issue by gregorydk** [tista500/Adapta#105]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version - 3.20.5
 * Desktop environment - 3.20.2
 ```

**Adapta version (if you knew)**
Git

**Related Application and/or Shell theming (or name of widget)**
All applications

**Actual issue**
In GNOME the top bar menu is not aligned to the left. The longer the name the more misaligned it is. Is this expected behaviour?

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

![screenshot adapta menu-alignment 2016-05-23](https://cloud.githubusercontent.com/assets/7804464/15475921/b0f88a7a-210c-11e6-9827-afef16120f32.png)

**Comment by tista500** [comment]
Compare with Adwaita before posting here.

**Comment by gregorydk** [comment]
The standard shell theme has an arrow pointing up, centered with the name. Adapta has not which looks weird and confusing.
