### ISSUE TITLE
Ubuntu top bar

### ISSUE THREAD

**Issue by stelariusinfinitek** [tista500/Adapta#106]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version -
 * Desktop environment - Unity 
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue** My friend told me about this. Look in the top-right corner, you can see that the color is not the same. I hope you can fix it. :)

![13275060_1134299209955500_815149772_o](https://cloud.githubusercontent.com/assets/18717816/15482224/290bf932-2137-11e6-8e36-8c0f0df3cdf1.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by GhettoGirl** [comment]
I can confirm this.
You should also mention that this happens only when the window focus changes or when you hover the top bar with the mouse cursor.
The color change isn't constant either, it flickers.

This isn't that annoying imo, but still, a fix is highly appreciated :)

PS: Thanks for this amazing theme.

**Comment by tista500** [comment]
@stelariusinfinitek,

1st trial fix was committed: https://github.com/tista500/Adapta/commit/acb79752d1492bd26d1d7bed1d7b019f1cb5c963

But don't expect too much in Unity7 theming. It only brings me breakage of my design works... :(

Regards.
