### ISSUE TITLE
Evince annotation header

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#109]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment - 3.20.2
 ```

**Adapta version (if you knew)**
3.21.1.233

**Related Application and/or Shell theming (or name of widget)**
Evince PDF Viewer

**Actual issue**
The header bar of the annotation boxes has a light grey color on bright yellow, so the author's name is not readable. 
![evince-annotations](https://cloud.githubusercontent.com/assets/526104/15520984/73a9244c-2209-11e6-90b7-28252e6465e3.png)

**Steps to reproduce (if you knew)**
Open a PDF with annotations in evince

**Expected behaviour**
The author name should be readable.

**Other Note (feature-request, question, etc...)**
Since I'm using Adapta Nokto, I think bright yellow might not be the best color, however I understand that annotations are supposed to stick out, so this is up to you.

**Comment by tista500** [comment]
Confirmed foreground-colour and committed: https://github.com/tista500/Adapta/commit/a450da2e821c14b477be0510086e6766249277a8

Regards.
