### ISSUE TITLE
Title of inactive tabs in firefox unreadable

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#11]
I'm running Firefox 44.0.2 on latest Archlinux (they compile Firefox with GTK3).

The text in the tabs has almost the same color as the tab background.

![tab-color](https://cloud.githubusercontent.com/assets/526104/13472698/5572d700-e0b6-11e5-8fc0-d1fe21f2be91.png)

**Comment by tista500** [comment]
@pschichtel,

Oh that's ugly issue... :confused: 

Unfortunately Gtk+ 3.0 version firefox is not landed in Ubuntu 16.04, so I did not test it yet. But I will fix it.

Regards.

**Comment by tista500** [comment]
OK.

Now I've tried Nightly browser and confirmed this issue.
Then I've also committed fix : 5ecd33d51e3d2e678eb94d1e083daf91e4bc64b3

Please check it out whether the issue was fixed or not...

Regards.

**Comment by pschichtel** [comment]
I can confirm the fix
