### ISSUE TITLE
Return appearance Flat-Plat gnome-shell

### ISSUE THREAD

**Issue by gargullia** [tista500/Adapta#110]
Return appearance Flat-Plat gnome-shell 
![aqmuvib](https://cloud.githubusercontent.com/assets/19420334/15555646/525c2414-22d2-11e6-9b4a-ad8138b6a346.jpeg)
What is that line? Not on Google's guideline

**Comment by tista500** [comment]
No.

In the same zero elevation, we need pane-separator between dock and window previews.

Regards.

**Comment by gargullia** [comment]
@tista500 Please select the file and the string to replace this value
