### ISSUE TITLE
Almost the best theme - but lime green ???

### ISSUE THREAD

**Issue by gps1539** [tista500/Adapta#111]
I love the theme and hats off to the folks that put this together.

My comment is clearly a preference (but supported by several observers).
The colors for when I click top-right in gnome for volume-mgr or open-weather are a ghastly lime green.  Can this be changed to a white or sane blue?

**Comment by tista500** [comment]
@gps1539,

Here is neither forum nor SNS. Reriwte with issue template.

Regards.

**Comment by tista500** [comment]
@gps1539,

Specific styling of OpenWeatherExtension was committed: https://github.com/tista500/Adapta/commit/af2854fc6617d2e802496e38d73a4c5d6f7fbf05

I don't have any ideas why devs use 'system-menu-action' style-class for its extension... :(

> Can this be changed to a white or sane blue?
No.
Cyan is for selections.

Regards.
