### ISSUE TITLE
 Unable to locate package adapta-gtk-theme

### ISSUE THREAD

**Issue by MrYogi** [tista500/Adapta#112]
as title suggest, issue while installing

**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Why you guys did not explain which distribution you run, what command you did... 

I'm really tired to answer against such poor reports.

**Comment by tista500** [comment]
My PPA only supports Xenial and Yakkety.

Regards.
