### ISSUE TITLE
Replace font color of notificationin a dark theme

### ISSUE THREAD

**Issue by gargullia** [tista500/Adapta#113]
We need to change the font color of the notification. In a dark theme
 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```
**Adapta version 3.21.1 Stable Release (rev.242)**
![pcbbky9](https://cloud.githubusercontent.com/assets/19420334/15575390/3f19c774-235b-11e6-8392-8727620d5084.jpeg)

**Comment by tista500** [comment]
I could not track this issue down since you did not follow the issue template. So I also could not reproduce it.

Invalid.
