### ISSUE TITLE
Huge headerbars on Gnome logs

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#116]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.20.6-1
 * Desktop environment -  Gnome
 ```

**Adapta version (if you knew)** The latest from `adapta-gtk-theme-git` on AUR packages

**Related Application and/or Shell theming (or name of widget)** Gnome logs

**Actual issue**
As with #98, Gnome logs has the same issue
![capture du 2016-05-27 20-02-23](https://cloud.githubusercontent.com/assets/7660997/15616744/f96c5b06-2445-11e6-9c48-835dec3a8b08.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@bil-elmoussaoui,

It's not the same issue. Different reasons.
Since devs did crazy constructing for GtkButton.

Fix was committed: https://github.com/tista500/Adapta/commit/b8fe62d12600acf5591aa0381ae8f57ed500a558

Regards.

**Comment by bil-elmoussaoui** [comment]
Thanks for the quick fix
