### ISSUE TITLE
Album poster size on gnome shell

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#117]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment -  Gnome
 ```

**Adapta version (if you knew)** the latest one

**Related Application and/or Shell theming (or name of widget)** Gnome shell player controller

**Actual issue**
The size of the album poster is so small
![capture d ecran de 2016-05-27 20-53-34](https://cloud.githubusercontent.com/assets/7660997/15618339/cddf5530-244d-11e6-9790-8dba5c338f1e.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**
With default shell theme
![capture d ecran de 2016-05-27 20-53-22](https://cloud.githubusercontent.com/assets/7660997/15618347/d5ae13a0-244d-11e6-9da4-4899c259fa51.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Confirmed and enlarged album-cover image a bit.

Fix was committed: https://github.com/tista500/Adapta/commit/fb75de3da3d089cbbab90a3e1c31e77bf2688632

Regards.
