### ISSUE TITLE
Huge headerbars on Vocal

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#118]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment -  Gnome
 ```

**Adapta version (if you knew)** The latest version from git

**Related Application and/or Shell theming (or name of widget)** The headerbar of Vocal

**Actual issue**
As you can see in the screenshot, i've compared Vocal headerbar and FeedReader headerbar, and Vocal's one is a little bigger
![capture d ecran de 2016-05-28 00-53-51](https://cloud.githubusercontent.com/assets/7660997/15622958/c4658b0c-246e-11e6-83c9-4da31df21c9a.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**
With Adawita, the difference is not the same. 
![capture d ecran de 2016-05-28 00-56-35](https://cloud.githubusercontent.com/assets/7660997/15622984/0ca205a8-246f-11e6-8526-0c7c1606ee13.png)

**Other Note (feature-request, question, etc...)**

I don't know if it's really a bug, or just the application not using the right icon sizes for the headerbar..but i wanted to be sure.

**Comment by tista500** [comment]
I've read this: https://quassy.github.io/elementary-apps/Vocal/
Adapta won't support elementaryOS components.

And their repositories for Ubuntu didn't support our Xenial and Yakkety. Though I don't know whether that application was popular or not...

Regards.

**Comment by bil-elmoussaoui** [comment]
Ah i see! It's not a problem :)
