### ISSUE TITLE
Is there a possibility of an icon pack with this theme in the future?

### ISSUE THREAD

**Issue by zoutiyx** [tista500/Adapta#12]
### Query
Just curious. This theme is wonderful and I'm curious as the whether or not there might be a icon pack the go with it?

**Comment by pschichtel** [comment]
You might want to look at https://github.com/snwh/paper-icon-theme

**Comment by tista500** [comment]
@zoutiyx,
@pschichtel,

Yeah specific icon theme must be great, but I don't have such skills to implement various icons unfortunately :cry: 

I just use Numix-Circle icon pack daily-use with my theme and looks nice. But I could hope much more, we may want "long-shadow-ed" icons like Android M (or N). I love them...

Regards.

**Comment by zoutiyx** [comment]
@pschichtel ,

Thanks for the recommendation. I used paper, but the terminal icon is too dark. and it sometimes appears invisible based on the window color below.

@tista500,
I currently use this theme https://github.com/rudrab/Shadow. It's a good one I fine. Just dislike the folder icons.

**Icons:**
![Image of my Dock](http://s30.postimg.org/fro42ue1d/shadow.png)

**Folders:**
![Image of Folder icons](http://s29.postimg.org/kif1f6h0n/folders.png)

**Comment by tista500** [comment]
@zoutiyx,

Wow top-right to bottom-left shadows!? looks aggressive...
In Gnome's Human Interface Guideline, if we speak/write "left to right' languages, the work-flow of GUIs should follow such directions (left-to-right & top-to-bottom). so drop-shadows should do as well (or at least, simple top-to-bottom shadows are welcome), just my thoughts.

And indeed, folder icons are not modern for me, too.:smile:

Regards.

**Comment by MichaelTiebesl** [comment]
I tried to modify some icons for this theme already. I just don't get the icons symbolic showing correctly in Gnome. https://github.com/MichaelTiebesl/Plat

**Comment by zoutiyx** [comment]
@tista500,

I never looked at it from that perspective. But now it seems that way.

**Comment by tista500** [comment]
@zoutiyx,

Yeah here's the HiG: https://developer.gnome.org/hig/stable/
My Adapta is developed with that guideline ( and Material Design, too).

Basically, every light-spot/drop-shadow and 'ply' of the papers, are described, based on Japanese Origami:
![origami](https://cloud.githubusercontent.com/assets/6073622/13555985/6368be88-e412-11e5-8de4-a3df278ef952.jpg)

We can see how Google design team designed those icons and widget elements by learning paper-craft Origami... That picture, with top-left light spot and bottom-right drop-shadows, in most cases, our eyes will track the paper edges, light and shadow, from top-left to bottom-right in order. So icon design should be like this...

Regards.

**Comment by zoutiyx** [comment]
@tista500,

I wasn't really aware. Thank you for further clarifying.


___________________________________________________________________________________

Philan James

Software Engineer | Linux Enthusiast
___________________________________________________________________________________

**Comment by user501254** [comment]
@zoutiyx 
Hi, Paper icons go very well with this particular theme. However, I too think that the Terminal icon under the icon theme is a bit too dark. 
This has already been reported [here](https://github.com/snwh/paper-icon-theme/issues/82) and am hopeful that it will improve as refinements are made.
Meanwhile you could just use your own custom icon for Terminal.

**Comment by mustafaozhan** [comment]
I am using currently Papirus icon theme (Dark one) with Paper folder icons, this combination is the best  one which i figured out so far.
