### ISSUE TITLE
Ubuntu 16.04 top bar - line of demarcation

### ISSUE THREAD

**Issue by 1Claude** [tista500/Adapta#120]
**Reporter info**

 ```
 * Distribution - Ubuntu
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**
Latest from PPA

**Related Application and/or Shell theming (or name of widget)**
Top bar menu

**Actual issue**
There's a fine line of demarcation visible bellow the top bar menu.

![capture du 2016-05-29 22-03-39](https://cloud.githubusercontent.com/assets/19640810/15638868/f075950e-25f2-11e6-834d-595028783a54.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**
Full black top bar menu

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@1Claude,

Stop using external link to put images, use Github instead. I won't open your link. :(

Regards.

**Comment by 1Claude** [comment]
![capture du 2016-05-29 22-03-39](https://cloud.githubusercontent.com/assets/19640810/15638858/c2e0827a-25f2-11e6-85a9-96522f44dddf.png)

Sorry for the external link...

**Comment by tista500** [comment]
OK, Trial started.

Trial 1: https://github.com/tista500/Adapta/commit/f4acd9a9cafb3a263d473525727e1d140a5ebde1
But I now have not any Unity environments, so please check if that commit solve the issue...

Regards.

**Comment by 1Claude** [comment]
I'd like to help, but I'm just a regular user with zero knowledge in coding and dev. 

I'm experienced enough to use all sorts of distros and find solutions on Google, but that's about it.

So, I don't know what to do at all with those lines and numbers...

**Comment by tista500** [comment]
Updated PPA packages...

Check it out.

Regards.

**Comment by GhettoGirl** [comment]
The line is gone now. Look much better imo :)

![screenshot from 2016-05-30 08-57-43](https://cloud.githubusercontent.com/assets/13280758/15642004/c73c3c22-2644-11e6-9919-c23d6e55a3a5.png)

Regards

**Comment by tista500** [comment]
Good ;)

**Comment by 1Claude** [comment]
Yes, I confirm. Many thanks ! 

![capture du 2016-05-30 10-14-17](https://cloud.githubusercontent.com/assets/19640810/15651712/54267efe-264f-11e6-97cb-ebbb9736d500.png)
