### ISSUE TITLE
Break when using as Cinnamon Controls (LM 17.2)

### ISSUE THREAD

**Issue by lbngoc** [tista500/Adapta#121]
This theme is broken window and force it close when I using this theme for Cinnamon Controls in Linux Mint 17.2

**Comment by tista500** [comment]
Did you read README.md already? So LinuxMint 17.2 had enough newer versioned against Adapta's required components?

Oh please...

**Comment by lbngoc** [comment]
So sorry, I checked the cinnamon version and it is just v 2.6.13

**Comment by tista500** [comment]
Unfortunately unsupported.

Closed.
