### ISSUE TITLE
(Occasional) black separator line in Nautilus

### ISSUE THREAD

**Issue by baurigae** [tista500/Adapta#122]
I encounter this behavior in Nautilus:

![blin](https://cloud.githubusercontent.com/assets/5447269/15754438/6c110326-28f8-11e6-9231-1f6decec447a.png)

Namely, there is a black (looks like solid #000) 1px separator line between the sidebar and the rest of Nautilus. This happens the first time I right-click on an icon to get the menu - but only after switching to a new directory. This is not present on subsequent right-clicks in the same directory. But once I switch to another, all over again.

I'm running Ubuntu 16.04 upgraded to Gnome 3.20.

**Comment by tista500** [comment]
Tell me "how many times I have to say *Why you guys did not follow the issue-template?*"

**Comment by tista500** [comment]
In past, Gtk+ 3.19.3, I saw similar issue but now I could not reproduce. And why you're still stuck with older Adapta?

Regards.

**Comment by baurigae** [comment]
Okay. _Let me tell you_.
I've read some other issues & your responses. So let me be as rude as you are and say that the only thing I'm stuck with here is your truly regrettable attitude to people trying to help you make your mod better than it is right now. This is a fine theme. But it's got problems. So why not take the advantage of working with people - isn't that why you posted this on GitHub? - instead of putting people off.

Instead, I've seen you shaming new GitHub users because they haven't yet learned how to properly include pictures in their posts, you're closing bugs you don't know how to fix, along with smartass remarks about your... _template_? What? Why not consult @nana-4 instead - the bug I reported is inherited from Flat-Plat. 
Maybe they have some pointers on how to fix it? 

But at least that theme doesn't have the nasty gThumb bug that you have. Don't worry, I won't bother reporting it :)

I'm done here, cheers, & no hard feelings. I'm super sure you can take it was well as you like to give it.
