### ISSUE TITLE
GTK error when starting steam

### ISSUE THREAD

**Issue by KeizerDev** [tista500/Adapta#123]
**Reporter info**

 ```
 * Distribution - Fedora
 * Gtk+ 3.0 version - Don't know
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)**
Latest build

**Related Application and/or Shell theming (or name of widget)**
Steam

**Actual issue**
```
/usr/share/themes/Adapta/gtk-2.0/common.rc:1135: error: unexpected identifier `direction', expected character `}'
/usr/share/themes/Adapta/gtk-2.0/misc.rc:36: error: unexpected identifier `direction', expected character `}'
/usr/share/themes/Adapta/gtk-2.0/3rd-party.rc:190: error: invalid string constant "null", expected valid string constant
Gtk-Message: Failed to load module "pk-gtk-module"
```

**Steps to reproduce (if you knew)**
Just start steam

**Expected behaviour**
-

**Other Note (feature-request, question, etc...)**
When I start steam I see that error

**Comment by tista500** [comment]
So what was the actual issue? GtkComboBox and GtkSpinButton are missed? 

Regards.

**Comment by tista500** [comment]
> `/usr/share/themes/Adapta/gtk-2.0/3rd-party.rc:190: error: invalid string constant "null", expected valid string constant`

That was the theme specific issue.
But I don't have any clue why Steam said that about the others.. :(
Since I've never seen such warning in any other Gtk+ 2.0 applications.

Regards.

**Comment by tista500** [comment]
No response, just closed...
