### ISSUE TITLE
small line under the menu bar in nautilus

### ISSUE THREAD

**Issue by GhettoGirl** [tista500/Adapta#124]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04 Xenial
 * Gtk+ 3.0 version - 3.18.9 (with custom patches)
 * Desktop environment - Unity 7.4 (with custom patches)
 ```

**Adapta version (if you knew)**
f7ce41ddc2e538542a8f858572a2e328328e192a 2016-06-03 20:54:13 +0900

**Related Application and/or Shell theming (or name of widget)**
Nautilus 3.14.3 (with custom patches)

**Actual issue**
Below the global menu bar there is a small line. I'm not sure if this is part of the theme or a bug.
![nautilus_scrmb1](https://cloud.githubusercontent.com/assets/13280758/15778953/bd7615e8-2999-11e6-813d-cdf8cbe0abab.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**
In my opinion it would look a bit better without this line. But it is your decision ;)

**Other Note (feature-request, question, etc...)**
custom patches: removed trash out of of unity, gtk and nautilus (i hate trash)

**Comment by tista500** [comment]
@GhettoGirl,

Just to be clear: Which you mean: 
 * Global menu in Unity-Panel
 * LIM in Window Frames in each GtkWindows

Let me know...

Regards.

**Comment by GhettoGirl** [comment]
__Global menu in Unity-Panel__: Unity Global menu configured to show in every applications title bar, when you hover with the mouse.

__LIM in Window Frames in each GtkWindows__: Sorry, I don't know what you mean by this? Can you clarify? Thanks

Regards

**Comment by tista500** [comment]
Which are you taking about Unity-Panel or GtkWindow?

**Comment by GhettoGirl** [comment]
Unity Panel

**Comment by tista500** [comment]
>  Unity Global menu configured to show in every applications title bar, when you hover with the mouse.

That is the LIM (Locally Integrated Menu). It's NOT Unity-Panel but part of GtkWindow (more precisely, compiz's window decoration).

Global-Menu what we usually call is GtkMenuBar inside top-bar at the top of screen (means inside the Unity-Panel).

So which?

**Comment by GhettoGirl** [comment]
Ah, now I see. In this case it's the __LIM__, i prefer this. I attached a additional screenshot to my last comment.
It this line below the title bar part of the theme or a bug? I never read the Material Design Guidelines, but it doesn't feel right, it shouldn't be here imo.

Regards

**Comment by tista500** [comment]
OK. I imagine you're using Nautilus 3.14.x with Canonical patchset.
If those patches are applied, Nautilus removes its own `.titlebutton` class from GtkHeaderBar and then moves them into Compiz's window decoration (crazy).
It also means Compiz draws own `.titlebar` class above the GtkHeaderBar without any optimizing. Once that happened, the "header-bar top-edge" effect remains in GtkHeaderBar (Unity specific problem). Most of designers did not find any solution to handle such "crazy" behaviour of Compiz yet.

For example, 
 * GtkHeaderBar's border-radius in right/left edge was remained still.
 * GtkHeaderBar's top-border colour was remained still.

You may see those "gap" between Compiz's titlebar and GtkHeaderBar as "small line", right? It's completely upstream (Canonical) issue and the worst thing in Ubuntu 16.04.

So there's no way to solve from theme-side today.

Regards.

**Comment by GhettoGirl** [comment]
How unfortunate :(

*Another question:*
Do you think that the line will disapper if I use the plain vanilla nautilus (without Canonical patches)? Since I have custom patches enabled anyway, I don't mind a recompilation from source code. Is it worth a try?

The latest nautilus version is **3.20.1** and the **[git version](https://github.com/GNOME/nautilus)** had the last commit 4 days ago.

Regards

**Comment by tista500** [comment]
> Do you think that the line will disapper if I use the plain  vanilla nautilus (without Canonical patches)? 

Maybe no. Once you've dispatched, Compiz will stop drawing its own titlebar for Nautilus anymore (means it disables LIM as well).

> The latest nautilus version is 3.20.1 and the git version had the last commit 4 days ago.

Please don't mix Gtk+ 3.18 and Nautilus 3.20 regardless... That breaks theming completely. Use Nautilus 3.18.x instead.

Anyway here's the wrong place to discuss the way to employ vanilla Nautilus into Xenial.

Regards.
