### ISSUE TITLE
Polari unread channel indicator

### ISSUE THREAD

**Issue by MadcapJake** [tista500/Adapta#125]
**Reporter info**

 ```
 * Distribution - Ubuntu Gnome 16.04
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Gnome Shell
 ```

**Adapta version (if you knew)**

Installed via PPA around a week ago (not sure what version)

**Related Application and/or Shell theming (or name of widget)**

Polari

**Actual issue**

Polari indicated a channel has unread messages by showing a darker font for the channel name.  With Adapta, I can't tell if it's just not there or too similar to distinguish.

**Steps to reproduce (if you knew)**

Open Polari, get a message in channel you're in but not currently active in.

**Expected behaviour**

A darker font (or some other color even)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
What is the "channel indicator"? I'm not a Polari user... :(

**Comment by MadcapJake** [comment]
In the left sidebar is a list of channels whereupon any activity occurs within each channel, the name of the channel becomes bold (or darker at least).
![screenshot from 2016-06-04 00-02-08](https://cloud.githubusercontent.com/assets/3377525/15797739/ac2e0e28-29e7-11e6-91a9-4b936c01194d.png)
Several channels that I am in have new messages, but there is seemingly no way to tell. Here's a shot of Polari with paper theme and you can see several darker channel names.
![screenshot from 2016-06-04 00-04-01](https://cloud.githubusercontent.com/assets/3377525/15797744/fb81d586-29e7-11e6-9f2c-908774745380.png)

**Comment by MadcapJake** [comment]
Thanks!
