### ISSUE TITLE
Unreadable text in the Hamster Time Tracking GNOME Extension

### ISSUE THREAD

**Issue by sanfilippopablo** [tista500/Adapta#126]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment - GNOME 3.20.2
 ```

**Adapta version (if you knew)**

This commit: f9d5ad254f6b1b41c800f4e1c8436cfc91e62a1a

**Related Application and/or Shell theming (or name of widget)**

Hamster Time Tracking GNOME Extension

**Actual issue**

The _What are you doing?_ text input is unreadable.

![hamster-adapta](https://cloud.githubusercontent.com/assets/1562004/15803402/1fe0c4b2-2ab2-11e6-999f-37cebfbb2b54.png)

**Steps to reproduce (if you knew)**

Insert text in the _What are you doing?_ text input.

**Expected behavior**

The text being edited should be dark.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@sanfilippopablo,

Trial was committed: https://github.com/tista500/Adapta/commit/7947af5ece79ea10578a78b8db412f7f9712fb29
Check if that commit solve the issue.

Regards.

**Comment by sanfilippopablo** [comment]
Yes. That commit solved the issue. That's perfect. Thanks for your dedication.

**Comment by tista500** [comment]
OK. Good... ;)
