### ISSUE TITLE
deja-dup: progress window incorrectly styled

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#127]
**Reporter info**

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - GTK+ 3.20
 * Desktop environment - Gnome 3.20
 ```

**Adapta version (if you knew)**
latest git master

**Related Application and/or Shell theming (or name of widget)**
deja-dup

**Actual issue**
The progress window of deja-dup is incorrectly styled because it only shows one line
![bildschirmfoto von 2016-06-08 12-45-28](https://cloud.githubusercontent.com/assets/1418818/15891965/58a69336-2d77-11e6-9f18-7a029d2b2661.png)

**Steps to reproduce (if you knew)**
create a new deja-dup backup and open the progress window

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Confirmed and fixed.

Regards.
