### ISSUE TITLE
Last update Adapata-Nokto not workin Mint Cinnamon 3

### ISSUE THREAD

**Issue by 1Claude** [tista500/Adapta#128]
**Reporter info**

 ```
 * Distribution - Linux Mint 18 beta
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Cinnamon 3.0.5
 ```

**Adapta version (if you knew)**Latest from PPA

**Related Application and/or Shell theming (or name of widget)** Cinnamon Desktop Theme
![adapata2](https://cloud.githubusercontent.com/assets/19640810/15941713/68d82d7c-2e4f-11e6-9ca5-4041fe21ac84.png)

**Actual issue** Unreadable blank
![adapata](https://cloud.githubusercontent.com/assets/19640810/15941541/a8b6b66c-2e4e-11e6-96c7-e293338f036b.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Confirmed and committed: https://github.com/tista500/Adapta/commit/f90f846700cffa500633e56e70f2c4e5e2feee28

Regards.
