### ISSUE TITLE
gnome-terminal menu misstyled

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#133]
**Reporter info**

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3.20 
 ```

**Adapta version (if you knew)**
git master

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
gnome-terminal menu is unreadable because of black font on black background

**Steps to reproduce (if you knew)**
open gnome-terminal

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by HeikoAdams** [comment]
![bildschirmfoto von 2016-06-14 21-41-40](https://cloud.githubusercontent.com/assets/1418818/16057123/d057facc-3278-11e6-9883-9a1471ee9cad.png)

**Comment by HeikoAdams** [comment]
![bildschirmfoto von 2016-06-14 21-41-40](https://cloud.githubusercontent.com/assets/1418818/16057146/ee82a97a-3278-11e6-97c2-8d37fcec1f64.png)

**Comment by tista500** [comment]
Confirmed and fixed: https://github.com/tista500/Adapta/commit/3e11cc1aa32f5a3f57b63d7aa51eaef6e4b694b6

Regards.
