### ISSUE TITLE
Theme for QT

### ISSUE THREAD

**Issue by N4d4** [tista500/Adapta#134]
**Reporter info**

 ```
 * Distribution - Debian8
 * Gtk+ 3.0 version -
 * Desktop environment - XFce4
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

There is a way to adapt the "color scheme" of the Adapta-Nokto for the [QT applications](http://i.imgur.com/pDSHCVw.png)?
The white is a punch in the eyes...

**Comment by tista500** [comment]
@N4d4,

If you had already set `GTK+` on `qt4-qtconfig -> Appearance -> GUI Style`, theme specific issues might exist... But I don't know about Qt5 apps.

Regards.

**Comment by N4d4** [comment]
I solved it by adding:
`export QT_STYLE_OVERRIDE=gtk`
to my **$HOME/.profile**
Now it  [looks better...](http://i.imgur.com/LYe8Fmp.png)

**Comment by tista500** [comment]
OK, Good...

Closed.

**Comment by Krakob** [comment]
The .profile fix fixed it for me on i3-gaps, despite having the correct settings in Qt 4 Settings and the Qt apps working as they should in Xfce. Running Xubuntu 16.04. Thank you :)
