### ISSUE TITLE
Black icons in file manager

### ISSUE THREAD

**Issue by rascal-pl** [tista500/Adapta#135]
**Reporter info**

 ```
 * Distribution - Elementary OS Loki
 * Desktop environment - Pantheon
 * GTK - 3.18
 ```

**Adapta version (if you knew)**
Newest, probably.

**Actual issue**
Icons in file manager are black after selection. I don't know if it's normal, or just a bug. It looks bad for me and looking for it in .css file is a horror.
![alt tag](http://i.imgur.com/euywQQ5.jpg)

+ one more thing - there is no infomration about used space in mounted partitions.

**Steps to reproduce (if you knew)**
Click on anything in file manager.

**Expected behaviour**
Click on folder in any other app. This is how it should looks like imho.
Or on stock theme:
![alt tag](http://i.imgur.com/Uxcyfpn.jpg)

**Other Note (feature-request, question, etc...)**
If it is normal, please, just tell me where it is in gtk.css.
Thank you.
Regards

**Comment by tista500** [comment]
@rascal-pl,

ElementaryOS is not supported.

Regards.

**Comment by rascal-pl** [comment]
OK I understand, but could you tell me which line it could be in gtk.css? Or some clues at least. Thank you in advance.

**Comment by tista500** [comment]
I haven't any clues about ElementaryOS's components since those are not my things... So please use other themes in that distribution. I can not help.

Regards.
