### ISSUE TITLE
git master fails to build

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#136]
**Reporter info**

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 
 ```

**Adapta version (if you knew)**
git master

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Theme fails to build:
> checking for bundle... no
> configure: error: 'bundle' not found.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by GhettoGirl** [comment]
Adapta has now new dependencies, which are
 - [ruby bundler](http://bundler.io/)
 - [sass](http://sass-lang.com/install)
 - [Inkscape](https://inkscape.org/)
 - glib-compile-resources

You need to install these first.

**Comment by HeikoAdams** [comment]
Okay the dependencies are now satisfied but when running make i get
> error 3.18/_common.scss (Line 1992: Invalid US-ASCII character "\xE2")

**Comment by GhettoGirl** [comment]
Is your locale ```UTF-8``` encoded? I don't know what could be the problem otherwise :/

```bash
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=C
LC_TIME=C
LC_COLLATE=C
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I had no problems installing the new version.

What you could try since this line is just a comment
```css
// Abandon all hope — Ye Who Enter Here
```
is to remove it and watch out for other occurenced of ```—``` and remove them if they are in comments. Comments are every line starting with ```//```.

Maybe you have a locale problem or your system doesn't support Unicode.

Regards

**Comment by HeikoAdams** [comment]
After a short research that can be fixed by adding
> @charset "UTF-8";
at the top of the file(s)

**Comment by GhettoGirl** [comment]
This is definitely the best solution to overcome different locale settings.

**Comment by tista500** [comment]
This could help: https://github.com/tista500/Adapta/commit/d364761dbc0a8a0ebec6d0fadd16acdcf8fce702 ? :(

Regards.

**Comment by HeikoAdams** [comment]
Yeah, that did the job! Thanks!

**Comment by tista500** [comment]
What error messages?

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/6410ed3e4b3f9cd444cf43d707fe497ec96fd9ab

**Comment by GhettoGirl** [comment]
I guess adding
```css
@charset "UTF-8";
```
on top of every CSS file would be the best solution.

**Comment by tista500** [comment]
@GhettoGirl,

Generally yes. But those were the code-bug itself, since surely scss should be built even on C locales... ;)

Thanks.

**Comment by HeikoAdams** [comment]
With latest commit build works fine.

**Comment by tista500** [comment]
Closed.

**Comment by karencho777** [comment]
i have this error please help i have downloaded latest theme also add @charset "UTF-8"; to every css gile ,i am using kali linux 2016

**Comment by AnwarShah** [comment]
@tista500 I can't install sassc in Ubuntu 16.04. It's not in the default repository and I couldn't find any ppa. Any pointer on where can I find it would be useful.

**Comment by AnwarShah** [comment]
I found a way and I'll be documenting it for 16.04
