### ISSUE TITLE
config.status failed

### ISSUE THREAD

**Issue by drxspace** [tista500/Adapta#137]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04 LTS 64-bit
 * Gtk+ 3.0 version - 3.20.6-1ubuntu1
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)**
...

**Related Application and/or Shell theming (or name of widget)**
Adapta theme

**Actual issue**
.
.
.
checking for bundle... no
configure: error: 'bundle' not found.
Makefile:331: recipe for target 'config.status' failed
make: *** [config.status] Error 1
.
.
.
checking for bundle... no
Makefile:331: recipe for target 'config.status' failed

**Steps to reproduce (if you knew)**
```
	cd "$HOME"/gitClones/Adapta # directory with clone
	sh autogen.sh
	sudo sh -c '
		make uninstall
		rm -rfv /usr/share/themes/Adapta*
		make install'
	make clean 2>/dev/null

```

**Expected behaviour**
...

**Other Note (feature-request, question, etc...)**
Thank you for all these works of yours!

**Comment by tista500** [comment]
@drxspace,

Read the https://github.com/tista500/Adapta#installation-from-git-source first...

Regards.

**Comment by drxspace** [comment]
okay, I did that and everything's fine! Thanks.

**Comment by tista500** [comment]
Good...

Closed.
