### ISSUE TITLE
Firefox save password popup bad arrow placement and shadow

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#14]
Yet Another Firefox Problem.

As on the screenshots:
- The arrow down seems too close to the button (with normal and hover state)
- The shadow in hover state seems "cut off"

![menu_003](https://cloud.githubusercontent.com/assets/526104/13502030/740ba2a6-e169-11e5-8e7a-7b95dce31ce1.png)
![menu_004](https://cloud.githubusercontent.com/assets/526104/13502032/75a02fb0-e169-11e5-9402-d6c946197cb1.png)

There are possibly more popups with this problem as it is probably related to these composite-buttons

**Comment by tista500** [comment]
@pschichtel,

Sorry for my delayed response.
I suspect this issue might be the upstream bug. The reasons are:
* Various Gtk+ themes act exactly same with mime.
* My theme did not have any 'raised' GtkComboBox (GtkButton + GtkButton).
* My theme did not have any 'negative margin' in GtkButton, GtkComboBox, GtkButtonBox etc.
* Even if I add the padding around GtkImage in global section, it have been ignored still.
* We just only don't know such unknown style-class? No clue...

Anyway I have not any clue to solve this issue via Gtk+ theming (I could not override this),  Firefox's codes might have some hardcoded stupid margins and/or aligns...

Regards.
