### ISSUE TITLE
Previous selected font name is also showing after selecting another font in Libreoffice.

### ISSUE THREAD

**Issue by WantedFish** [tista500/Adapta#141]
**Reporter info**

 ``` 
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3.20
 ```

**Adapta version (if you knew)**

Latest

**Related Application and/or Shell theming (or name of widget)**

Libreoffice

**Actual issue**

Previous selected font name is also showing after selecting another font in Libreoffice.

**Steps to reproduce (if you knew)**

Change the font in Libreoffice Writer. 

**Expected behaviour**

Not showing previous font name after selecting anther font.

**Other Note (feature-request, question, etc...)**

Please check this out. Then you can easily understand the issue.
[https://drive.google.com/file/d/0B0WWVqN0QQS-eDBWeDV0QVZLNVE/view?pref=2&pli=1](https://drive.google.com/file/d/0B0WWVqN0QQS-eDBWeDV0QVZLNVE/view?pref=2&pli=1)

**Comment by tista500** [comment]
@WantedFish,

Those commit may fix the issue:  https://github.com/tista500/Adapta/commit/53a115be7c1a60577fdda921a8d15af5242af2f7

Regards.

**Comment by WantedFish** [comment]
Didn't fixed yet. :(

**Comment by tista500** [comment]
Ah you run LO with Gtk+-2 backend...
2nd fix was committed: https://github.com/tista500/Adapta/commit/187af0b130ed96b504ad08a3a82c065ebc5c2498

Regards.

**Comment by WantedFish** [comment]
Thanks bro. Fixed. :+1:  :)
