### ISSUE TITLE
Hinted fonts such as Ubuntu and Roboto becoming bold in Nautilus and GNOME Tweak Tool

### ISSUE THREAD

**Issue by tristan957** [tista500/Adapta#142]
**Reporter info**

 ```
 * Distribution - Ubutntu GNOME 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)** tista/adapta PPA Version

**Related Application and/or Shell theming (or name of widget)** Nautilus 3.20, GNOME Tweak Tool

**Actual issue** Hinted fonts become bold in these applications. Changing to the light version of the font has no effect. If I use FreeSans the font is not bold.
![screenshot from 2016-06-22 15-40-33](https://cloud.githubusercontent.com/assets/11936772/16282742/acd144ce-388f-11e6-9fa2-68729d43b67e.png)

**Steps to reproduce (if you knew)** Apply the Ubuntu regular font or the Roboto regular font. According to their descriptions both are hinted fonts.

**Expected behaviour** Use the specified font.

**Comment by tista500** [comment]
In Material Design, Clickable widgets in 13px(or 14px) should use 500 font-weight. It's not Bold font-face but Medium weight.
