### ISSUE TITLE
Gtk Entry on a selected GtkListBoxRow

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#143]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version  -3.21.2-1
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)** The latest git version

**Related Application and/or Shell theming (or name of widget)** GtkEntry on a selected GtkListBoxRow

**Actual issue**
![capture du 2016-06-23 00-00-46](https://cloud.githubusercontent.com/assets/7660997/16285291/9eb52158-38d5-11e6-88c0-f45720e017a3.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

![capture du 2016-06-23 00-01-09](https://cloud.githubusercontent.com/assets/7660997/16285297/a607b86c-38d5-11e6-848a-f4c3b3a691a0.png)

**Other Note (feature-request, question, etc...)**

I had this issue with an application i'm working on

**Comment by tista500** [comment]
@bil-elmoussaoui,

I've never seen such entry node directly embedded into list node... :(
BTW, why that app did not employ popover node to do 'rename' actions?

Anyway this issue is new feature for me...

Regards.

**Comment by bil-elmoussaoui** [comment]
@tista500 
I don't know, it's the only idea i had in mind. Still trying to improve the design of the application
Thanks.

**Comment by tista500** [comment]
Trials are committed...

Check if those could implement expected features properly...

Regards.

**Comment by bil-elmoussaoui** [comment]
Thanks for the quick fix, a part of the issue was fixed 
When the window is unfocused, the white color is not used anymore 
![capture d ecran de 2016-06-23 01-48-55](https://cloud.githubusercontent.com/assets/7660997/16287608/b9d46016-38e4-11e6-80f3-346c1df096a2.png)
Btw, i got those errors when i open any app on terminal
```bash
(gnome-twofactorauth:22186): Gtk-WARNING **: Theme parsing error: gtk.css:8093:10: not a number

(gnome-twofactorauth:22186): Gtk-WARNING **: Theme parsing error: gtk.css:8093:17: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gnome-twofactorauth:22186): Gtk-WARNING **: Theme parsing error: gtk.css:9038:173: Using one color stop with linear-gradient() is deprecated.

(gnome-twofactorauth:22186): Gtk-WARNING **: Theme parsing error: gtk.css:9040:171: Using one color stop with linear-gradient() is deprecated.

(gnome-twofactorauth:22186): Gtk-WARNING **: Theme parsing error: gtk.css:9103:165: Using one color stop with linear-gradient() is deprecated.
```
Should i open a new issue about that?

**Comment by bil-elmoussaoui** [comment]
The same for the unselected row
![capture d ecran de 2016-06-23 01-53-12](https://cloud.githubusercontent.com/assets/7660997/16287667/446498ae-38e5-11e6-9160-17ec2dd82330.png)

**Comment by tista500** [comment]
Where is the source of that app?

**Comment by bil-elmoussaoui** [comment]
@tista500 https://github.com/bil-elmoussaoui/Gnome-TwoFactorAuth

**Comment by tista500** [comment]
OK. Let's see...

And some parsing errors would be fixed soon.

Regards.

**Comment by tista500** [comment]
> The same for the unselected row

!?
Why does 'unselected' list node need entry node? wasn't it un-selected? entry node should follow the parent state... :(

**Comment by bil-elmoussaoui** [comment]
@tista500 Sorry, it was a bug on the code, just fixed that :)

**Comment by tista500** [comment]
> When the window is unfocused, the white color is not used anymore 
Indeed, it's quite right that I expect. Because entry should only be 'raised/activated' (means `focus` pseudo-class) in case users click the entry node in the selected-row, and then once unfocused, entry should be back to `normal` pseudo-class...

Regards.

**Comment by bil-elmoussaoui** [comment]
@tista500 Totally agree with you. So this can be closed or there's still some improvements to do on the unfocused window case? :)
Thanks

**Comment by tista500** [comment]
In this time, I close this. But after making my time to polish those codes, I will retry, maybe... ;)

Regards.

**Comment by tista500** [comment]
Implemented raised materials for selected-rows.
https://github.com/tista500/Adapta/commit/6c3a655095497dc496d41dd91d3c05a478631e05
https://github.com/tista500/Adapta/commit/b1d9087d1d5315c1dd163f4a6fc2ec0935536012

Those might be better...

Regards.

**Comment by bil-elmoussaoui** [comment]
Looks better! Thanks for your work :+1:
