### ISSUE TITLE
[FIXED] Fails to compile on Fedora 23

### ISSUE THREAD

**Issue by CrusoeDaWolf** [tista500/Adapta#144]
**Reporter info**
bundle exec sass --update --sourcemap=none --watch \
3.20/gtk-dark.scss:../gtk-3.20/gtk-dark.css
Could not find sass-3.4.22 in any of the sources
Run `bundle install` to install missing gems.
Makefile:1148: recipe for target 'all' failed
make[2]: *** [all] Error 7
make[2]: Leaving directory '/home/ssardiko/Adapta/gtk'
Makefile:1035: recipe for target 'install-am' failed
make[1]: *** [install-am] Error 2
make[1]: Leaving directory '/home/ssardiko/Adapta/gtk'
Makefile:353: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

 ```
 * Distribution - Fedora 23
 * Gtk+ 3.0 version - gtk3-3.18.9-1.fc23.x86_64
 * Desktop environment - XFCE4
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
While doing 'sudo make install', I get the error above, however, when I run 'bundle install'
I get:
`Using sass 3.4.22
Using bundler 1.7.8
Your bundle is complete!
`

**Steps to reproduce (if you knew)**
Just went straight through instructions on compiling from git.

**Expected behaviour**
Success running 'sudo make install'.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@CrusoeDaWolf,

If you've run `bundle install` after autoconf had finished, remove `Gemfile.lock` and re-run `autogen.sh`:

```
cd SRC_DIR_OF_ADAPTA
find . -name "Gemfile.lock" -exec rm -f {} \;
./autogen.sh
```

Regards.

**Comment by CrusoeDaWolf** [comment]
Nope. Once again, it failed after I compiled and did 'sudo make install'
Same error.

**Comment by GhettoGirl** [comment]
Try to switch to root account with either ```su``` or ```sudo su``` and than issue ```make install```. I have the same issue on Arch. Bundler just complains about missing dependencies when invoked using ```sudo``` :/

**Comment by tista500** [comment]
I've reverted commit: https://github.com/tista500/Adapta/commit/a6b94eeaf3327baaaf1038773f25c7ec4024791f

That might run 'all' twice even if `make` was finished...

Regards.

**Comment by user501254** [comment]
Same issue, on Fedora 24.

**Comment by CrusoeDaWolf** [comment]
You can close this now! It's been fixed! Thanks c:
