### ISSUE TITLE
A little hack to avoid conflicts when Gnome panel is moved to bottom

### ISSUE THREAD

**Issue by Thisuu** [tista500/Adapta#145]
**Reporter info**

 ```
 * Distribution - Debian Stretch/Sid
 * Gtk+ 3.0 version - Gtk3 - 3.20.6
 * Desktop environment -  Gnome
 ```

**Adapta version (if you knew)** 
Latest from github

**Related Application and/or Shell theming (or name of widget)**
Gnome shell extensions: mmod-panel, Dash-to-dock

**Actual issue**
As you might already know,if the gnome panel is moved to bottom, Legacy tray icon conflicts with the panel. I did a little bit hack to solve this by something like this, (I'm not that good in sass so css code is added here. feel free to play with this and add upstream)

####
.legacy-tray {
  border: none;
  border-bottom-width: 0;
  background-color:transparent;                   [1] <----
  color: rgba(236, 239, 241, 0.75);
  padding-bottom:60px;                                 [2] <----
  box-shadow: none; }
  .legacy-tray:ltr {
    border-radius: 0 2px 0 0;
    border-left-width: 0; }
  .legacy-tray:rtl {
    border-radius: 2px 0 0 0;
    border-right-width: 0; }

.legacy-tray-handle,
.legacy-tray-icon {
  padding: 6px;
  background-color: rgba(42, 55, 62, 0.9) }
.legacy-tray-icon {
  border-radius:2px;
  box-shadow: 0 3px 4px rgba(0, 0, 0, 0.32), 0 3px 2px rgba(0, 0, 0, 0.24); }
.legacy-tray-handle:hover, .legacy-tray-handle:focus,
  .legacy-tray-handle:active {
  color:#FFFFFF; }
.legacy-tray-icon:hover {
  background-color: rgba(42, 55, 62, 0.7) }
  
  .legacy-tray-handle StIcon,
  .legacy-tray-icon StIcon {
    icon-size: 24px; }

.legacy-tray-icon-box {
  spacing: 10px; }
  .legacy-tray-icon-box:ltr {
    padding-left: 12px; }
  .legacy-tray-icon-box:rtl {
    padding-right: 12px; }
  .legacy-tray-icon-box StButton {
    width: 24px;
    height: 24px; }
####
The trick here is to hide the real tray by making it transparent[1] and taking the visible handle and icon higher with "padding-bottom". So theming can be added to those afterwards.
This solves the issue,plus makes the legacy tray more usable and responsive.
(Screenshot after solving this is added)

**Steps to reproduce (if you knew)**
Install the mmod-panel (Or any other gnome extension which support moving top panel) and move the top panel to bottom.

**Expected behaviour**

**Other Note (feature-request, question, etc...)**
![screenshot from 2016-06-23 16-59-38](https://cloud.githubusercontent.com/assets/13273054/16301637/04195eb8-3964-11e6-82d9-c70d27e2c295.png)

**Comment by tista500** [comment]
@Thisuu,

Just let me know, shouldn't those extensions improve that feature? :/
Or "systray to top(or bottom)-bar" extension solves itself without any ugly hacks in theme-level?

Regards.
