### ISSUE TITLE
Theme is not showing in themes list in Gnome tweak tool.

### ISSUE THREAD

**Issue by WantedFish** [tista500/Adapta#146]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3.20
 ```

**Adapta version (if you knew)**

Latest

**Related Application and/or Shell theming (or name of widget)**

Tweak tool

**Actual issue**

Adapta theme is not listed in the theam list in Gnome tweak tool. This is happened only in latest VERSIONS of Adapta theme.  

**Steps to reproduce (if you knew)**

:(

**Expected behaviour**

Showing this theme in Gnome tweak tool's theme list.

**Other Note (feature-request, question, etc...)**

I installed this theme by downloading this theme directly from this site and extract it to ~/.themes

**Comment by tista500** [comment]
Read the https://github.com/tista500/Adapta#installation-from-git-source first.
Adapta doesn't support 'copy-n-paste' theme installing anymore.

Regards.

**Comment by WantedFish** [comment]
Got it.
But have to uninstall the old theme when going to install the latest theme using terminal codes.
Installing themes using copy and paste is the easiest way.
