### ISSUE TITLE
Missing support for secondary_selection_color in gtk/asset/render-assets-gtk3.sh?

### ISSUE THREAD

**Issue by glitsj16** [tista500/Adapta#148]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.6-1
 * Desktop environment - gnome
 ```

**Adapta version (if you knew)**
3.21.3 (latest from git)

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Support for secondary_selection_color looks missing from gtk/asset/render-assets-gtk3.sh

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

Commit https://github.com/tista500/Adapta/commit/7d7ff5a1c8cd13bb47df25ced4763ad738f0a637 added support for destruction_color to gtk/asset/render-assets-gtk3.sh (color-changer scheme). The updated README.md mentions support for changing **5** Key-Colors, yet gtk/asset/render-assets-gtk3.sh currently only deals with **4**, missing the **secondary_selection**.

I've forked and will make a PR if the above makes sense to you.

Regards.

**Comment by tista500** [comment]
There's no images use such colors.

Regards.

**Comment by glitsj16** [comment]
Thanks, makes sense. Closing this.

Regards.
