### ISSUE TITLE
[Request] Adapta for Fedora, OpenSuse

### ISSUE THREAD

**Issue by 1Claude** [tista500/Adapta#150]
**Reporter info**

 ```
 * Distribution - Fedora 24, OpenSuse Leap 42 (Tumbleweed)
 * Gtk+ 3.0 version - GTK 3.20
 * Desktop environment - GNOME, etc.
 ```

**Adapta version (if you knew)**Latest

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

If you could make Adapta available to easily install in Fedora and OpenSuse, as easy with the PPA option, so users could also get updates. Lots of people love Adapta, but can't find a simple way to get it. For example, see what arc-theme did on opensuse software : [https://software.opensuse.org/download.html?project=home%3AHorst3180&package=arc-theme](url)

![capture du 2016-06-27 14-05-00](https://cloud.githubusercontent.com/assets/19640810/16390375/6fb76674-3c70-11e6-8067-237fa2127f7c.png)

Thanks.

**Comment by tista500** [comment]
We can already see the RPM packages here: https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/

So are there any reasons to duplicate pacakge-building by me?

Regards.

**Comment by Abhinav1217** [comment]
I am having similar issues. I have used the copr but it is full of conflicting issues. That was why I was looking for somewhat better solution for this theme. Currently Either I can install Adapta-gtk3 or gnome-shell-theme-Adapta but not both. And I can't install Adapta-chrome-theme. All of theme are conflicting on Adapta-common with slightly different git patch number.

Any solution to that. I would want to have Adapta across shell theme, gtk theme chrome theme etc.

**Comment by woohooatb** [comment]
Fedorainfracloud.org doesn't install your theme properly. It only install the Shell themes and not the GTK+ themes.

**Comment by caoli5288** [comment]
@woohooatb You can download deb file from https://launchpad.net/~tista/+archive/ubuntu/adapta/+packages

**Comment by HeikoAdams** [comment]
@woohooatb @Abhinav1217 Thanks for notifying me about problems with my packages instead of blaming @tista500' about that :smiling_imp:

**Comment by tista500** [comment]
I have nothing to do with it, so closed.

**Comment by woohooatb** [comment]
@caoli5288 I don't want it.

**Comment by USBA** [comment]
@HeikoAdams 
I added the copr repo from Heikoada. 
https://copr.fedorainfracloud.org/coprs/heikoada/gtk-themes/

I tried `dnf install gnome-shell-theme-Adapta`
It's working. But only having the shell theme (Adapta gtk+ theme is not installed)

then I tried 
`dnf install gnome-gtk-theme-Adapta`,
`dnf install gnome-gtk3-theme-Adapta`
`dnf install adapta-gtk-theme`
`dnf install adapta-gtk4-theme`

But not working :'(

What is the command to install complete Adapta theme (gtk+ theme and shell theme) on Fedora ?

> Fedora version that I'm using: Fedora 24 (GNOME 3.20) & Fedora 25 Alpha (GNOME 3.22)


Please help me.
thanks.

**Comment by HeikoAdams** [comment]
@USBA running `$ dnf list \*Adapta\*` lists
`Adapta-chrome-theme`
`Adapta-cinnamon-theme`
`Adapta-metacity-theme`
`Adapta-plank-theme.noarch`
`Adapta-xfce4-notifyd-theme`
`Adapta-xfwm4-theme.noarch`
so just pick the packages you need :wink:

**Comment by woohooatb** [comment]
It looks like Tista only uses Ubuntu and hates other distros. :(

**Comment by USBA** [comment]
I'm also an Ubuntu user and recently moved to Fedora 25 Alpha to use GNOME  3.22

Thanks @HeikoAdams It's working

**Comment by Veske** [comment]
@woohooatb It looks like Fedora users are a bit too spoonfed and cannot package a simple RPM for them selves.
