### ISSUE TITLE
Make icons larger in the top-right menu

### ISSUE THREAD

**Issue by WantedFish** [tista500/Adapta#151]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment -  Gnome 3.20
 ```

**Adapta version (if you knew)**

latest

**Related Application and/or Shell theming (or name of widget)**

menu of the right side in the top panel. 

**Actual issue**

Small size icons & user name.

**Steps to reproduce (if you knew)**

**Expected behaviour**

Large user name & icons

**Other Note (feature-request, question, etc...)**

Please check the right-top menu of the Paper theme.
[https://drive.google.com/open?id=0BywiiYFzILRIQmQyOEtSR3hJVEE]

**Comment by WantedFish** [comment]
If you don't like to resize this in adapta theme, please teach me to resize it.
Please. I need to resize it like in Paper theme.

Regards

**Comment by tista500** [comment]
Paper's approach is breaking the alignments and geometries of extractable sub-menu containers. Once that happened, laptop users will see unwanted displacements of sub-menu containers (see my shot).

![screenshot from 2016-06-28 22-40-07](https://cloud.githubusercontent.com/assets/6073622/16417808/494fad08-3d82-11e6-984f-43286608fdf4.png)

So no, Adapta won't do. And I can't help you as well.

If you REALLY want to ignore my opinion and to tweak that icon-size, see `.system-switch-user-submenu-icon` style-class. And then I have to say again, "I do NOT suggest such things".

Regards.

**Comment by WantedFish** [comment]
![adapta top panel](https://cloud.githubusercontent.com/assets/19838220/16446735/ad0fe8e2-3e06-11e6-8c41-bddabd1bf0d3.png)
Look at the top right menu of adapta in desktop pc.
User name & picture is very small.
:(

**Comment by WantedFish** [comment]
![paper top panel](https://cloud.githubusercontent.com/assets/19838220/16446789/f7180186-3e06-11e6-95e1-0fdd2f008d25.png)
this is the paper top-right menu

**Comment by WantedFish** [comment]
Increase the icon-size to 40px
`.system-switch-user-submenu-icon.user-icon {
  icon-size: 40px;
  padding: 0 2px; }`

![adapta123](https://cloud.githubusercontent.com/assets/19838220/16457383/ef26eed8-3e38-11e6-9387-20e83d328b3c.png)


Thanks for giving me the style-class
