### ISSUE TITLE
lmb click by itself on some option in context menu

### ISSUE THREAD

**Issue by WantedFish** [tista500/Adapta#152]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3.20
 ```

**Adapta version (if you knew)**

latest

**Related Application and/or Shell theming (or name of widget)**

nautilus

**Actual issue**

when I click on folder or file in nautilus (but only on objects below center), lmb click by itself on some option in context menu. So I must push and hole lmb to see the context menu.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by WantedFish** [comment]
please refer this video.
https://drive.google.com/file/d/0B0WWVqN0QQS-YWd2anF2VTluVWM/view

**Comment by pschichtel** [comment]
Isn't that normal behavior if you click-hold on a select menu and move the mouse?
