### ISSUE TITLE
hovering buttons in thunderbird

### ISSUE THREAD

**Issue by WantedFish** [tista500/Adapta#153]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment -  Gnome 3.20
 ```

**Adapta version (if you knew)**

latest

**Related Application and/or Shell theming (or name of widget)**

thunderbird

**Actual issue**

Hovering buttons in thunderbird looks ugly 
![zrzut ekranu z 2016-06-30 14-09-28](https://cloud.githubusercontent.com/assets/19838220/16488258/63de63b4-3eed-11e6-8876-0ae6342c6cd1.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

Please modify it

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
I think it's an upstream issue caused in Thunderbird's code itself because that happens in various themes like Numix, Ark-Darker, Ambiance and Adapta, too.

Regards.

**Comment by WantedFish** [comment]
ok.
