### ISSUE TITLE
Nemo file manager file/directory renaming color

### ISSUE THREAD

**Issue by ijustjoinedtoreport** [tista500/Adapta#154]
**Reporter info**

 ```
 * Distribution - Linux Mint 18 (64bit)
 * Gtk+ 3.0 version - 3.18.9-1ubuntu3
 * Desktop environment - Cinnamon
 ```

**Adapta version (if you knew)**
3.21.3+git20160701-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)**
Nemo v3.0.6

**Actual issue**
While renaming a file, selected text has the same color like non-selected text and background. This causes wierd renaming experience, e.g. user is unable to read the item name while renaming and is unable to see the text cursor position while renaming.

**Steps to reproduce (if you knew)**
Try renaming a file inside Nemo file manager while using Adapta-Nokto with the following theme settings:
Window borders: Adapta-Nokto
Controls: Adapta-Nokto
Mouse Pointer: Adwaita
Desktop: Adapta-Nokto

**Expected behaviour**
Selection cursor and selected text should be different color than non-selected text.
Selection cursor should also be of a different color than background color.

**Other Note (feature-request, question, etc...)**
Possible solution: create a proper color property for an appropriate 'EelEditableLabel' element

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/3c74366cffc1582540fdf3377ecc2c2cf243ffe0

Regards.
