### ISSUE TITLE
Color Request: ubuntu colors

### ISSUE THREAD

**Issue by Feichtmeier** [tista500/Adapta#157]
**Reporter info**

 ```
 * Distribution - ubuntu 16.04
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

It would be totally awesome to have the exact theme but with the Ubuntu orange instead of the bright blue. Maybe if you are completely bored (haha) and what to make a ubuntu fanboy happy! Thanks for the work! Most modern gtk theme out there atm!

**Comment by tista500** [comment]
I'm not a fanboy of Ubuntu-Artworks.

Read this first: https://github.com/tista500/Adapta#installation-from-git-source
You should build Adapta by your own.

Regards.
