### ISSUE TITLE
Xfce4-mixer sliders and text

### ISSUE THREAD

**Issue by stelariusinfinitek** [tista500/Adapta#158]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment - Xfce4
 ```

**Adapta version (if you knew)** 3.21.3.56

**Related Application and/or Shell theming (or name of widget)** xfce4-mixer

**Actual issue** Missing or unreadable elements

**Steps to reproduce (if you knew)** Open xfce4-mixer. The sliders are missing. Also some text is hardly readable.

**Expected behaviour** The volume sliders should appear and the text can be darker. I attached a comparison between Adapta and Arc-Darker.

**Other Note (feature-request, question, etc...)**

![screenshot from 2016-07-04 16-29-10](https://cloud.githubusercontent.com/assets/18717816/16562016/dbdc242c-4204-11e6-8eae-053ca85ccf00.png)
![screenshot from 2016-07-04 16-29-33](https://cloud.githubusercontent.com/assets/18717816/16562017/dbdded20-4204-11e6-84b4-2abc789c62fd.png)

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/6ad4d66ffaae36891d228193b27ce88584ad1940

By the way, why Arch still had such dropped plugins in 4.12.2? :(
Upstream has already moved to pulseaudio-plugin, for Adapta, there's no advantages to support outdated apps...

Regards.

**Comment by stelariusinfinitek** [comment]
I understand. I didn't know they are so outdated. Thank you so much!
