### ISSUE TITLE
Consistant versioning

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#16]
You just added a "-2" to you version which complicates packaging a bit.
I tihnk it would be best to always append the revision, if you want to be able to release multiple versions per day. Alternatively just use an increasing number without the date (e.g. 3.18.8.123).
At least for Archlinux package versions may not contain a dash.

**Comment by tista500** [comment]
@pschichtel,

OK. I will do for Arch...

Regards.

**Comment by pschichtel** [comment]
Where did the releases go?

**Comment by zoutiyx** [comment]
@pschichtel,

I saw that they were deleted:

![Releases deeted](http://s23.postimg.org/a04azp18r/deleted_releases.png)
