### ISSUE TITLE
[Eclipse/SWT (neon)] theming still has shadows and gradients in the tool-bar

### ISSUE THREAD

**Issue by Feichtmeier** [tista500/Adapta#160]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
Eclipse (Neon) Java IDE 

**Actual issue**

**Steps to reproduce (if you knew)**
Install eclipse neon, open it and look to the menu bar with GTK theming activated (it is activated by default after a fresh install) in eclipse

**Expected behaviour**
![bildschirmfoto vom 2016-07-04 20-44-05](https://cloud.githubusercontent.com/assets/15329494/16568279/744cebce-4228-11e6-9d00-e8a98ef08744.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Edited the title.

**Comment by tista500** [comment]
Workaround was committed: https://github.com/tista500/Adapta/commit/f6a623f703668367d12e972504d0d47586146cc0

Regards.

**Comment by Feichtmeier** [comment]
Thanks! Works! :dancer:
