### ISSUE TITLE
Is it possible to configure Adapta to have light-colored header bars?

### ISSUE THREAD

**Issue by swarnendubiswas** [tista500/Adapta#161]
**Reporter info**

 ```
 * Distribution - Ubuntu Gnome 16.04 w/ Gnome3 staging ppa
 * Gtk+ 3.0 version - 3.20.6-1ubuntu1~ppa1
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)** 
Built from source (070616)

**Related Application and/or Shell theming (or name of widget)**
Most applications, such as Firefox, Evince

**Actual issue**
I built Adapta from source and I have global dark theme turned off. Current header bars in Adapta are dark in color.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**
Is there an option in Adapta to build light colored header bars? It seems such was the case according to a few videos. Does Adapta provide any such options currently?

**Comment by stlaz** [comment]
I would love to see that as well.

**Comment by tista500** [comment]
> Is there an option in Adapta to build light colored header bars?
No. Now Adapta employs dark GtkHeaderBars and Title-bars in any cases.
