### ISSUE TITLE
Transparent top bar and menus of top bar

### ISSUE THREAD

**Issue by WantedFish** [tista500/Adapta#162]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3.20
 ```

**Adapta version (if you knew)**

latest

**Related Application and/or Shell theming (or name of widget)**

Top bar

**Actual issue**

This is not a issue.

**Steps to reproduce (if you knew)**

**Expected behaviour**

Transparent top bar and menus of top bar.

**Other Note (feature-request, question, etc...)**

98% sure you won't like this.
If you don't like to do this, Please give me the style-class.
Thanks.

**Comment by tista500** [comment]
100% I dislike.
So I can't help anymore.

Regards.
