### ISSUE TITLE
Colourful headers/titlebars  

### ISSUE THREAD

**Issue by WantedFish** [tista500/Adapta#163]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.20
 * Desktop environment -  Gnome 3.20
 ```

**Adapta version (if you knew)**

latest

**Related Application and/or Shell theming (or name of widget)**

gtk+

**Actual issue**

not a issue

**Steps to reproduce (if you knew)**

**Question**

Is there any way to change colours (colors) of title bars like colourful (colorful) headers in Paper gtk+ theme ??

**Comment by bil-elmoussaoui** [comment]
Well, dude the guys on Paper gtk theme repo told you that was not possible on gtk 3.20+...

**Comment by WantedFish** [comment]
yeah, I know that. But I need to know that how to do that?
in gtk 3.18 or any

**Comment by tista500** [comment]
> Is there any way to change colours (colors) of title bars like colourful (colorful) headers in Paper gtk+ theme ?? 

No way and Adapta does not have such plans to mimic Paper.

Regards.

**Comment by WantedFish** [comment]
ok
