### ISSUE TITLE
Libre office tooltips not fully displayed

### ISSUE THREAD

**Issue by Feichtmeier** [tista500/Adapta#165]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**
The most up to date version from this ppa

**Related Application and/or Shell theming (or name of widget)**
Libre Office  5.1.4.2

**Actual issue**
The mouseover tooltips  are not fully displayed -> a certain rest of the tooltip is cutted
If you change the theme with unity tweak tool from adapta to a different theme and back to adapta again the tooltip is shown correc
![bildschirmfoto vom 2016-07-12 19-44-33](https://cloud.githubusercontent.com/assets/15329494/16777259/184638b6-4869-11e6-8553-e7ec2c02e7b5.png)
tly

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
There's nothing to do from theme-side, it's Compiz issue. So I will drop unity support in future. Unity7 always brings tons of problems in theme development. :/

Regards.

**Comment by Feichtmeier** [comment]
Nooooooo :( But I love Adapta and I love unity :(

**Comment by fitojb** [comment]
No, it’s not a Compiz issue nor it is Unity’s. This is just an artifact of the old, emulated GTK+ widgets in LibreOffice’s VCL library. If you want native tooltips in LibreOffice, you must install its GTK+ 3 backend (`libreoffice-gtk3` package). Make sure it is compiled against the version of GTK+ 3 you’re using, or just use the distro package.

**Comment by Feichtmeier** [comment]
Wow that worked! 
Ubuntu 16.04 and without adding a ppa or anything:

sudo apt install libreoffice-gtk3

Thanks mate!

**Comment by fitojb** [comment]
You’re welcome ;)
