### ISSUE TITLE
[Request] Vivaldi / Chrome Themes

### ISSUE THREAD

**Issue by The5heepDev** [tista500/Adapta#166]
Can you add support for vivaldi and chrome?

Vivaldi (snapshot) has a built in theme, as does chrome.

**Comment by tista500** [comment]
Vivaldi has its own colour-changer to make user-side custom color-scheme. So what did you want me to support that? :(

Regards.

**Comment by The5heepDev** [comment]
@tista500 I guess? Or could you put in the readme the color hex's so that I can make the vivaldi theme?

**Comment by tista500** [comment]
Added: https://github.com/tista500/Adapta/commit/6e30771cf16abaa40e08290ecc0391a25ca7cc6c
