### ISSUE TITLE
[Request] GTK2 Title bars

### ISSUE THREAD

**Issue by Hori873** [tista500/Adapta#167]
Hello, can you please add support for GTK2 title bars?

My main PC (laptop) has Gnome-Shell (GTK3) and Adapta is my favourite theme, but I also have some older PCs around that have GTK2 (LXDE, Mate) and I would really like to use Adapta there as well... the GTK2 theme itself is ok but the title bars are the default ones... I partly solved it by using Numix title bars but they look quite out of place as well.

**Comment by tista500** [comment]
@Hori873,

LXDE runs OpenBox window-manager, it is not Gtk+ 2.0 native. And Mate has own window-managers folked from Metacity and Compiz code-base. Unfortunately Adapta won't support LXDE bacause LXDE development team has already announced to move to Qt toolkit desktop environment, so today there's no advantages to support openbox theming for Adapta. And Mate, especially talking about Compiz, I've been frustrated to support it so I really don't want to support it.

I don't think those window-managers are modern, and could never be 'fallback' of Mutter...

Adapta strongly suggests to run gnome-flashback as fallback desktop environment in case your machines did not have decent performance on OpenGL/GLES/Mesa based composited window-managers and desktop environemnts. Surely Adapta supports classical Metacity theming support (Gnome-Flashback is hosted in Gnome's git and developed in active, I actually run it on my ARM based chromebooks which employ Rockchip and Exynos).

So now there's no plans to support OpenBox and Mate's window-manager.

Regards.

**Comment by Hori873** [comment]
Thanks for your answer. You made some really good points and I respect your decision :D

This issue can be closed now.
Keep up the good work, this theme is awesome!

**Comment by singpolyma** [comment]
"LXDE development team has already announced to move to Qt toolkit desktop environment"

Actually, LXQt is a parallel project with similar goals. LXDE is going to remain maintained on GTK
