### ISSUE TITLE
Color subfolders for chrome theme

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#169]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.20+
 * Desktop environment -  Gnome
 ```

**Adapta version (if you knew)** Latest

**Related Application and/or Shell theming (or name of widget)** Google Chrome/Chromium

**Actual issue** The subfolders are not colored with the same color as the main folders
![capture d ecran de 2016-07-17 12-16-04](https://cloud.githubusercontent.com/assets/7660997/16900283/6b5507f0-4c18-11e6-9876-63f8f8287594.png)

**Steps to reproduce (if you knew)**
1 - Add a folder to the bookmarks bar
2 - Add a subfolder to it
3 - Show the bookmark bar 

**Expected behaviour**
I don't know if it's possible to color the subfolders too, if it's please fix it; otherwise you can close this!

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@bil-elmoussaoui,

Hmm, I did not notice those differences of colours...
So 1st trial was committed: https://github.com/tista500/Adapta/commit/dd2dd4c108b01ba4b08395604a513a0119162e66
I don't know Chrome(ium) could re-colour the svgs in CustomMenuItem via its own Gtk+ 2.0 backend though, but anyway please check if that commit fixed the issue...

Regards.

**Comment by tista500** [comment]
Damned... Couldn't fix. :/

So close in this time.

Regards.

**Comment by bil-elmoussaoui** [comment]
Thanks for trying anyway.. hope this will be fixed by Chrom(ium) soon!
