### ISSUE TITLE
Downloading bar is showed wrong in transmission

### ISSUE THREAD

**Issue by zoutiyx** [tista500/Adapta#17]
This is what the downloading bar in Transmission looks like with the Adwaita Theme:
![Adwaita](http://s17.postimg.org/jb0hysjen/showing.png)
And here is it with the Adapta Theme:
[]()

![Adapta](http://s17.postimg.org/n8nro767z/torrent_problem.png)
If looks like it has downloaded to me. But that is not the case. I can't tell if it has downloaded or not by the progress bar.

**Comment by tista500** [comment]
@zoutiyx,

I could reproduce this issue and confirm. Seems the side-effect bug in a couple of recent commits...

Regards.

**Comment by tista500** [comment]
This issue would be fixed by latest commit and closed...

Regards.

**Comment by zoutiyx** [comment]
@tista500,

Thanks, confirming the resolution of this issue.
