### ISSUE TITLE
Wrong color on librebreoffice dialog tabs

### ISSUE THREAD

**Issue by thepasto** [tista500/Adapta#170]
**Reporter info**

 ```
 * Distribution - ArchLinux
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3
 ```

**Adapta version (if you knew)**
3.21.4.15

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
On a libreoffice dialog, tabs are shown with white background and white font color

**Steps to reproduce (if you knew)**
Just open a dialog in libreoffice.

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

In the attachments, two images, one with adapta theme, and one with adwaita.
![schermata da 2016-07-20 10-54-04](https://cloud.githubusercontent.com/assets/593416/16985710/9b095a5c-4e82-11e6-80ee-28ef6f4e2643.png)
![schermata da 2016-07-20 11-09-59](https://cloud.githubusercontent.com/assets/593416/16985719/ac6fb70a-4e82-11e6-8f26-70bf5ef1728f.png)

**Comment by tista500** [comment]
LibreOffice is the "never ending nightmare"... :/

**Comment by tista500** [comment]
LibreOffice 5.2.0 seems to change its UI of 'Manage Templates', so there's nothing to do for that.

Closed

**Comment by RalphBariz** [comment]
with libreoffice 5.2.1 rc2 tabs are still white on white

BR
Ralph

**Comment by tista500** [comment]
If you haven't any patches/pull-requests, you don't have to bump this issue. I've already seen 5.2.1-rc2...

**Comment by tista500** [comment]
Workaround was committed: https://github.com/tista500/Adapta/commit/9d3e456055a5e27eb70f92a62a1967c58832d033

Regards.
