### ISSUE TITLE
Request : Red banner in window while using " Open as adminsitrator "

### ISSUE THREAD

**Issue by meetdilip** [tista500/Adapta#171]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version -
 * Desktop environment - Unity 7
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

There is currently no indication if we right click in window and " open it as admin ". Cinnamon gives a warning banner within window when we use " open as root ". Would be great if we can have it for Adapta as well. Thanks.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

Feature_Request

**Comment by tista500** [comment]
@meetdilip,

> Desktop environment - Unity 7

> here is currently no indication if we right click in window and " open it as admin ". Cinnamon gives a warning banner within window when we use " open as root ". Would be great if we can have it for Adapta as well. Thanks.

I could not get the point of your request at all...
Why did you compare the desktop environment (Cinnamon) with Gtk+ theme (Adapta)? If you meant that Unity7 should have the feature what Cinnamon did, you should file a report to Unity7 development team... :(

Those features should be implemented as applications/window-managers API instead of Gtk+ themes. So I haven't any clue what you want me to do... Or was there any actual parts Adapta still could not support GtkInfoBar in case Compiz/Unity7 was running?

Regards.

**Comment by meetdilip** [comment]
@tista500 , sorry if I got you confused. I was simply giving you idea of something that is available in Cinnamon. I just want to have a warning banner in window when I open the window as root/administrator within Unity in 16.04. Will it be possible to have it through Adapta ? Thanks.

**Comment by tista500** [comment]
@meetdilip,

Hmm, 
> a warning banner in window when I open the window as root/administrator within Unity in 16.04

Isn't it the application or shell APIs? Gtk+ theme does not have any calls like `widget_show()` and/or `widget_hide()`, and any calls via dbus to handle user-ids/session-buses as well. So how Gtk+ theme shows up GtkInfoBar from theme-side? I could not understand your request yet...

If you had any screenshots or mockups, please let me see to explain your request more precisely...

Regards.

**Comment by meetdilip** [comment]
@tista500 

Currently, this is the windows display if we open the window as a normal user and administrator / root. I was hoping to see some sort of warning / banner to denote you are root and be careful when you have opened the window as root.

![screenshot from 2016-07-23 12-37-37](https://cloud.githubusercontent.com/assets/6965443/17076555/e2a58136-50d2-11e6-9cb4-b11aa53c375d.png)

**Comment by tista500** [comment]
It's Nemo's feature: `./src/nemo-toolbar.c`
```
static void
setup_root_info_bar (NemoToolbar *self) {

    GtkWidget *root_bar = gtk_info_bar_new ();
    gtk_info_bar_set_message_type (GTK_INFO_BAR (root_bar), GTK_MESSAGE_ERROR);
    GtkWidget *content_area = gtk_info_bar_get_content_area (GTK_INFO_BAR (root$

    GtkWidget *label = gtk_label_new (_("Elevated Privileges"));
    gtk_widget_show (label);
    gtk_container_add (GTK_CONTAINER (content_area), label);

    self->priv->root_bar = root_bar;
    gtk_box_pack_start (GTK_BOX (self), self->priv->root_bar, TRUE, TRUE, 0);
}
```

So let's say again, you should better to file a feature-request to Nautilus development team.

Regards.

**Comment by meetdilip** [comment]
Ok. Thanks.

**Comment by tista500** [comment]
What did you mean "manually"? :(

**Comment by meetdilip** [comment]
@tista500  Doing it myself in some safe way.

**Comment by tista500** [comment]
Patching Nautilus? Yeah do it yourself.

**Comment by meetdilip** [comment]
@tista500 But I do not know what code to add :(

**Comment by tista500** [comment]
Hey hey.... I'm not a member of Nautilus team but theme designer. So isn't there proper place to do patchworks to Gtk+ applications? :(

**Comment by meetdilip** [comment]
I am sorry. Thanks for guiding so far. Cheers :)

**Comment by tista500** [comment]
No problem. ;)
