### ISSUE TITLE
[Suggestion] makefile: parallel build jobs (-jN)

### ISSUE THREAD

**Issue by GhettoGirl** [tista500/Adapta#172]
I have a suggestion. The current build process takes very (very) long because it doesn't have support for parallel jobs. While rendering assets using inkscape the use of the ```-jN``` flag of make would speed things up a lot :grin: 

Would it be possible to extend the current make system with that feature? Than someone could execute ```make -j16``` and the build process is finished super fast.

**Comment by tista500** [comment]
@GhettoGirl,

On build-servers distribution hosted, build should be done with `-j1` because we share the resources of them in case package-building in Ubuntu, Fedora, OpenSUSE...

And number of parallel lines are depend on your machine's CPUs core. In general, number of parallels are defined as: `make -j$(($(getconf _NPROCESSORS_ONLN)+1))`. As your post, someone had 15 cores!? :eyes: Anyway `-j` could make local-building faster with proper values, indeed.

Regards.

**Comment by tista500** [comment]
Enhancement was committed: https://github.com/tista500/Adapta/commit/483ec9798b00b8594c94bbf49cf1184655e4cf96

Regards.

**Comment by GhettoGirl** [comment]
I just tested and it seems that it never goes beyond 2 build jobs no matter what value I pass to the ```-j``` option :confused: Is this indented or a misuse of parallel?

My machine for example could run 8~9 instances of inkscape without performance degradation.

**Comment by tista500** [comment]
@GhettoGirl,

> I just tested and it seems that it never goes beyond 2 build jobs no matter what value I pass to the -j option  Is this indented or a misuse of parallel?

??
Rendering script executions from sh-scripts are 2 threads, so how could we make more parallel executions? It doesn't call `gcc`...

> My machine for example could run 8~9 instances of inkscape without performance degradation.

What did you mean? How did you deal with "for-loop" in sh-scripts to run executables?

**Comment by GhettoGirl** [comment]
> How did you deal with "for-loop" in sh-scripts to run executables?

I never tested this, its just a presumption based on the power of my machine. Since the inkscape process has only ~4~5% CPU usage. I have CPU 8 threads.

**Comment by tista500** [comment]
I'm talking about the differences between "line-interpreter" and "compiler", so I'm also afraid that you might be confused those. :(

**Comment by GhettoGirl** [comment]
Maybe :/
Anyway 2 jobs are faster than just 1, so its still a improvement :)

**Comment by tista500** [comment]
2nd enhancement was committed: https://github.com/tista500/Adapta/commit/71b835cd49bb9d307ebf345a105cd4787f89d5d0

That commit could increase the num. of threads up to 8 or 10 at peak-time...

Regards.

**Comment by GhettoGirl** [comment]
Thats pretty neat :)
Thanks for your work on this. Now build is even faster and re-renderings are also skipped.

Regards
