### ISSUE TITLE
[KDE] Tooltips: text is unreadable on background (almost same color)

### ISSUE THREAD

**Issue by GhettoGirl** [tista500/Adapta#173]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 2.0 version - 2.24.30+95+g876b5f7
 * Desktop environment - KDE Plasma 5.7.2
 ```

**Adapta version (if you knew)**
**master** (483ec9798b00b8594c94bbf49cf1184655e4cf96)

**Related Application and/or Shell theming (or name of widget)**
All GTK-based apps which doesn't override the theme/comes with a custom theme (including wxWidgets with GTK backend)

**Actual issue**
The text of tooltips is unreadable. The background is light grey and the text is white which makes it impossible to see the text.

NOTE: This does not happen with the Nokto version. GTK 3 is fine too.

I'm not sure if this happens because I use KDE, but the theme works great for GTK apps so I'm using it anyway.

Here are some screenshots from different GTK-based apps which doesn't override its theme.

![untitled](https://cloud.githubusercontent.com/assets/13280758/17085069/4602638c-51cf-11e6-9d00-e7fd81c28a45.png)
Dolphin Emulator &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Inkscape &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; wxFormBuilder

**Comment by tista500** [comment]
Hey, Adapta doesn't support K Desktop Environment... :(

**Comment by GhettoGirl** [comment]
I know that, but it still works for GTK apps with all the animations etc.
Are the tooltips ok in a supported desktop environment or does KDE fuk up the theme without my attention? I'm not sure.

**Comment by tista500** [comment]
@GhettoGirl,

You encountered this issue?: https://bugs.kde.org/show_bug.cgi?id=355540
And I could not get any actual solutions to be done with Gtk+ theme. :(

Regards.

**Comment by GhettoGirl** [comment]
The workaround is to comment out the line ```widget "gtk-tooltip" style "ToolTip"``` in ```~/.config/gtkrc-2.0```. Tooltips fallback to Breeze and are readable again.

This issue is out of control than.

Closing this

Regards

**Comment by phgachoud** [comment]
I would add to @magiruuvelvet answer which is 
  - remove "gtk-tooltip" style "ToolTip" in `~/.config/gtkrc-2.0`
  - restart the gtk-application (no display manager)
