### ISSUE TITLE
Customizable Window titlebar on GTK3

### ISSUE THREAD

**Issue by TheAifam5** [tista500/Adapta#174]
Hey,
I love your project because its very integrated with environment.
I have one question to you:
  * Its possible to make titlebar height more customizable?

ArchLinux, Budgie Desktop (git), gtk 3.20

Regards,
TheAifam5

**Comment by TheAifam5** [comment]
Title bar its possible to change using: headerbar.default-decoration

**Comment by tista500** [comment]
There's no plan to customize those geometries.

Closed
