### ISSUE TITLE
Selection in wireshark

### ISSUE THREAD

**Issue by Mephistophiles** [tista500/Adapta#176]
**Reporter info**

 ```
 * Distribution - ArchLinux
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - xfce4
 ```

**Adapta version (if you knew)**
3.21.4.43-1

**Related Application and/or Shell theming (or name of widget)**
wireshark-gtk

**Actual issue**
White selection in wireshark in bite view

In adapta theme
![screenshot_2016-07-25_12-55-49](https://cloud.githubusercontent.com/assets/4850908/17097652/5a55fdba-5267-11e6-9d37-f73997dd759c.png)

In adwaita
![screenshot_2016-07-25_12-57-57](https://cloud.githubusercontent.com/assets/4850908/17097692/806bc9bc-5267-11e6-8f29-5add6303ea36.png)

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/9ea7330c2ff314ce91295db754b5af9930ccad4b

Regards.
