### ISSUE TITLE
Latest Adapta fails to build

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#178]
Latest git master fails to build with following errors:

> cp: cannot stat './asset/assets-gtk2/Others/bottom.png': Not a directory
> cp: cannot stat './asset/assets-gtk2/Others/focus.png': Not a directory
> cp: cannot stat './asset/assets-gtk2/Others/left.png': Not a directory
> cp: cannot stat './asset/assets-gtk2/Others/null.svg': Not a directory
> cp: cannot stat './asset/assets-gtk2/Others/right.png': Not a directory
> cp: cannot stat './asset/assets-gtk2/Others/top-hover.png': Not a directory
> cp: cannot stat './asset/assets-gtk2/Others/top.png': Not a directory
> Makefile:1225: recipe for target 'install-data-local' failed

Build parameters are:
> --disable-unity --enable-plank --enable-chrome --enable-parallel

**Comment by TheAifam5** [comment]
For me works fine...
Can you use issue template to provide more informations?

**Comment by HeikoAdams** [comment]
Maybe fixed by f162e0e93665746b9025b47b1426bb5b2f482b59 in the meantime. I'll check and report back.

**Comment by HeikoAdams** [comment]
Nope. Not fixed :disappointed:

**Comment by HeikoAdams** [comment]
**Reporter info**

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 
 ```

**Adapta version (if you knew)**
Master


**Actual issue**
Build fails


**Steps to reproduce (if you knew)**
checkout latest git master and try to build

**Comment by pschichtel** [comment]
I had the same issue when switching the AUR package to parallel. It is probably related to these changes.

**Comment by HeikoAdams** [comment]
I'll try to build with disabled parallel

**Comment by tista500** [comment]
Hmm... This commit helped?: https://github.com/tista500/Adapta/commit/b0830225f2871fce8f6ac8cf9f9c0353540639fc

I never suggest to use parallel on buiild-server packaging... :/

**Comment by pschichtel** [comment]
I doubt the problems are related to being run in parallel on a build server. AUR packages are generally not run on servers, but on user systems. Good news: that commit fixed the build.

I guess a Makefile-based approach to compiling the assets could improve it even more. And when using make, build systems can usually change/override options, so a build server could decide if it allows parallel builds or not.

**Comment by tista500** [comment]
@pschichtel,

I'm not taking to you but original reporter. So guess what?
Please let me see any patches you wrote.

**Comment by HeikoAdams** [comment]
Build works fine with disabled parallel :smile:
