### ISSUE TITLE
Gedit search box UI nearly invisible 

### ISSUE THREAD

**Issue by zoutiyx** [tista500/Adapta#179]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)**
 3.21.4.43

**Related Application and/or Shell theming (or name of widget)**
gedit (Text Editor)

**Actual issue**
search box text and (up) and (down) arrows nearly invisible. It's hard on the eyes.

**Steps to reproduce (if you knew)**
1. Open gedit
2. CTRL + F

**Expected behaviour**
Search box pops up on the top right with the specified issued described above 

**Other Note (feature-request, question, etc...)**
![nearly invisible](https://cloud.githubusercontent.com/assets/8180637/17120303/55effb36-5299-11e6-920c-60efd19fd9e6.png)

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/db6812f0d8210fa3251e9ecc30ef04c2241eeeda

Regards.
