### ISSUE TITLE
 Window shadow inconsistency

### ISSUE THREAD

**Issue by tung9484** [tista500/Adapta#18]
I'm using GNOME and GTK 3.18 and Adapta from git master on Arch Linux

![screenshot from 2016-03-14 19-58-17](https://cloud.githubusercontent.com/assets/15673389/13745192/47829578-ea1f-11e5-94f9-12f3e55ba42e.png)

**Comment by tista500** [comment]
@tung9484,

What application was behind your terminal? Conky?

If so, could you please check whether the Server-side-decoration was restored after stopping such desktop widgets?

Regards.

**Comment by tista500** [comment]
@tung9484,

Ah, today I've confirmed and reproduced this issue.
So fix is committed now.

Regards.
