### ISSUE TITLE
[Budgie-Desktop] Broken keyboard indicator styling

### ISSUE THREAD

**Issue by cybre** [tista500/Adapta#180]
**Reporter info**

 ```
 * Distribution - Solus 1.2
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Budgie
 ```

**Adapta version (if you knew)**
Latest git

**Related Application and/or Shell theming (or name of widget)**
`keyboard-layout` applet

**Actual issue**
* The first item is raised and has a different background colour for no reason. I am guessing this is caused by the new `user-indicator` styling.
* Last item is pushed to the side.  
![screenshot from 2016-07-26 03-08-41](https://cloud.githubusercontent.com/assets/3101505/17122964/6970e67e-52e0-11e6-8064-993f85956ed4.png)

**Steps to reproduce (if you knew)**
Enable the indicator if you haven't already and try it for yourself.

**Expected behaviour**
It should be a normal list with normal list buttons.

**Other Note (feature-request, question, etc...)**
None

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/5552919bcd19ef854191ba27a43b5010069a426c

Regards.

**Comment by cybre** [comment]
The last item is still pushed to the side.

**Comment by tista500** [comment]
2nd fix was committed: https://github.com/tista500/Adapta/commit/01f93e2025bf68f26e7ca9ca550e6eac64bac295
