### ISSUE TITLE
Notification background color black on light shell theme

### ISSUE THREAD

**Issue by flipflop97** [tista500/Adapta#182]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
3.21.4.66-1 (AUR)

**Related Application and/or Shell theming (or name of widget)**
Shell theme (light) - notification

**Actual issue**
The notification background color and the text on it are both black, thus making it hardly readable.

**Steps to reproduce (if you knew)**
Receive a notification, for example with the command ```$ notify-send title content```

**Expected behaviour**
The notification having a white background (like in the notification/calendar popup)

**Other Note (feature-request, question, etc...)**
![screenshot from 2016-07-27 14-49-44](https://cloud.githubusercontent.com/assets/13943260/17175883/51fb28a8-540a-11e6-866f-aaaa9d47e44a.png)

**Comment by tista500** [comment]
?? :eyes: 

I could not reproduce, here's my gnome-shell 3.20.3:
![screenshot from 2016-07-28 06-44-27](https://cloud.githubusercontent.com/assets/6073622/17193695/30327368-548f-11e6-9713-2ad742f815c5.png)

> The notification having a white background (like in the notification/calendar popup)
I completely disagreed.
Because notification dialog/popup is a part of OnScreenDisplay elements instead of Popover/Context-Menu.

Regards.

**Comment by TheAifam5** [comment]
@flipflop97 just use https://aur.archlinux.org/packages/adapta-gtk-theme-git/

**Comment by flipflop97** [comment]
@TheAifam5 Still have the same issue with the git version.
@tista500 Having white text and a dark background is also good, but black on almost black is just unreadable.

**Comment by tista500** [comment]
It's not an issue of Adapta.

I suspect you had done something weird with `/usr/share/gnome-shell/gnome-shell-theme.gresource`, since that binary can be treated as highest priority than any other user-side themes.

Closed.

**Comment by flipflop97** [comment]
@tista500 Yep, you're right. It's because I installed the custom lockscreen of Plat Flat. Didn't know it could affect other themes. Thanks!
