### ISSUE TITLE
Content of notifications not correctly aligned

### ISSUE THREAD

**Issue by flipflop97** [tista500/Adapta#183]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
3.21.4.66-1 (AUR)

**Related Application and/or Shell theming (or name of widget)**
Shell theme - Notifications

**Actual issue**
The content of notifications isn't correctly aligned like the title.

**Steps to reproduce (if you knew)**
Receive a notification (using the command ´´´$ notify-send title content´´´)

**Expected behaviour**
The content to be correctly aligned:
More to the right, under the title, and probably a little more to the top.

**Other Note (feature-request, question, etc...)**
![screenshot from 2016-07-27 14-49-44](https://cloud.githubusercontent.com/assets/13943260/17176283/3158b85c-540c-11e6-8445-078ac54a5204.png)

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/8140f8c64b4f8430453e1379e74a156efb43b4fd
