### ISSUE TITLE
AnyDesk support

### ISSUE THREAD

**Issue by TheAifam5** [tista500/Adapta#184]
**Reporter info**

 ```
 * Distribution - ArchLinux
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Budgie Desktop
 ```

**Adapta version (if you knew)**
Master

**Related Application and/or Shell theming (or name of widget)**
AnyDesk

**Actual issue**
White theme in Application using dark theme

**Steps to reproduce (if you knew)**
Install Adapta-Nokto and install AnyDesk. Run and you will see.

**Expected behaviour**
More integrated with theme.

**Other Note (feature-request, question, etc...)**
![anydesk](https://cloud.githubusercontent.com/assets/2192274/17250940/cfa81e8a-55a6-11e6-96e4-421e9485a3fc.png)

**Comment by tista500** [comment]
There;s nothing I can do, contact to application developers.

Closed
