### ISSUE TITLE
Wrong notification theming

### ISSUE THREAD

**Issue by sanchaez** [tista500/Adapta#185]
**Reporter info**

 ```
 * Distribution - OpenSUSE Tumbleweed
 * Gtk+ 3.0 version - 3.20.2
 * Desktop environment - GNOME 3.20.2
 ```

**Adapta version (if you knew)**
Master

**Related Application and/or Shell theming (or name of widget)**
GNOME Shell

**Actual issue**
Notification has dark background with black text which is impossible to read (see screenshot).
![screenshot from 2016-07-30 15-58-23](https://cloud.githubusercontent.com/assets/10636528/17270588/7ae64fde-566e-11e6-8d5d-faafac3e39c6.png)

Both Adapta and Adapta-Nokto affected.

**Steps to reproduce (if you knew)**
Get a notification in GNOME eg. 
`notify-send "SUMMARY" "BODY"`

**Expected behaviour**
Light background and dark text in notification.

**Comment by tista500** [comment]
See https://github.com/tista500/Adapta/issues/182.
