### ISSUE TITLE
Oval buttons

### ISSUE THREAD

**Issue by Naheel-Azawy** [tista500/Adapta#186]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)** 
Not sure how to find that out but it should be the last one..

**Related Application and/or Shell theming (or name of widget)**
Buttons generally

**Actual issue**
Sometimes the buttons look oval while it should look circular or rectangular. Here are two screenshots for example,
Nemo
![screenshot from 2016-08-02 02-08-35](https://cloud.githubusercontent.com/assets/5764614/17311990/0c74f8a2-5858-11e6-9a6f-e28f757c5ffa.png)
Valama
![screenshot from 2016-08-02 02-08-56](https://cloud.githubusercontent.com/assets/5764614/17311997/11290adc-5858-11e6-9b62-6c1b307712a2.png)

**Comment by tista500** [comment]
Hmm, font-size and font-scaling-factors?

**Comment by tista500** [comment]
What version of Nemo? Stock 2.8.6-2 in main repository doesn't have 'reload' button in GtkToolBar.

> Valama

I will not support such minor apps what is breaking the design of GtkHeaderBar with mixin' other widgets...

Regards.

**Comment by tista500** [comment]
Fix for Nemo was committed: https://github.com/tista500/Adapta/commit/64d981013550124012f6755920f79f3e2b02af93

Closed.
