### ISSUE TITLE
Wishlist : Reduce the title bar height make it compact

### ISSUE THREAD

**Issue by sandeepbhardwaj** [tista500/Adapta#187]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.20 version -
 * Ubuntu Gnome 16.04 with gnome 3.20 
 ```
Please reduce the title bar height and also make it more compact , huge title bar take too much space in 14 inch laptop.

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> huge title bar

Let me see the differences between Adapta and Adwaita. I don't think Adapta has quite larger GtkHeaderBars and/or Mutter's titlebars than any others.

> in 14 inch laptop

It doesn't matter what inch the display had, it depends on resolution instead. Adapta is developed to cover Hi-end LCD displays like 3K, 4K and OLEDs, and Adapta is also concering the touchscreen displays on 2-in-1 ultrabooks/tablets.

So today 'less-padding' design is useless for me and I will not support such low-resolution devices.

Regards.

**Comment by woohooatb** [comment]
lol REKT
