### ISSUE TITLE
Fonts too light 

### ISSUE THREAD

**Issue by victormoreira** [tista500/Adapta#189]
**Reporter info**

 ```
 * Distribution - Manjaro Cinnamon
 * Gtk+ 3.0 version - 3.20.6-1
 * Desktop environment - Cinnamon 3.0.7
 ```

**Adapta version (if you knew)**
Last of git

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Your theme is on another level man, Congrats.
Fonts are too light in notifications, Alt+F2, Alt+Tab and other things.

![adapta](https://cloud.githubusercontent.com/assets/13660595/17339166/0958b528-58c1-11e6-9cf8-2726882739e1.png)

Thanks 

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Reverted: https://github.com/tista500/Adapta/commit/4d885a82993fcf171575fc68048b23991a906300

That will fix ths isue...
