### ISSUE TITLE
Mailnag gnome-shell extension not correctly themed

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#192]
**Reporter info**

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3.20 
 ```

**Adapta version (if you knew)**
latest git master

**Related Application and/or Shell theming (or name of widget)**
mailnag gnome-shell extension

**Actual issue**
The list of items on the mailnag gs extension is not correctly themed.

![bildschirmfoto von 2016-08-09 20-36-59](https://cloud.githubusercontent.com/assets/1418818/17528812/141a25cc-5e71-11e6-896c-5c97372f0bf2.png)
 

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
I'm not a user of that extension, so I don't know those commits could work or not.
Anyway if those did not work, there's nothing I can do for it.

Regards.

**Comment by towo** [comment]
Going to have to reopen this, current state with adapta-gtk 3.89.4.37-0ubuntu1~yakkety1 is still borked.
![screenshot from 2017-02-21 16-22-05](https://cloud.githubusercontent.com/assets/271819/23171182/120bd048-f852-11e6-9794-fbafa873c4d5.png)

**Comment by tista500** [comment]
That extension seems only for Adwaita, and also ignores user-side themes.
There's nothing to do for it anymore.

Closed.
