### ISSUE TITLE
Buggy ripple animation

### ISSUE THREAD

**Issue by ricardopvz** [tista500/Adapta#193]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3
 ```

**Adapta version (if you knew)**
3.21.4.155

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Ripple animation goes away too fast and doesn't complete if mouse button is not pressed

**Steps to reproduce (if you knew)**
Click a button

**Expected behaviour**
The animation should be slower and complete even if mouse button is not pressed

**Other Note (feature-request, question, etc...)**
Check Flat-Plat animation
Tabs should also have the animation

**Comment by tista500** [comment]
Partial fix was committed: https://github.com/tista500/Adapta/commit/7731c740b22fb0e9ff804d4358922255cb779406

> Tabs should also have the animation

Completely disagreed.
We should not employ animation property in `:checked` pseudo-class.

Closed.

**Comment by ricardopvz** [comment]
> Completely disagreed.
We should not employ animation property in :checked pseudo-class.

Well, I don't know how gnome theming works, but I was just following the Material Design guidelines here: https://material.google.com/components/tabs.html#tabs-specs
Check the video on `Tab touch target animation`
