### ISSUE TITLE
Is it possible to change title bar color by options?

### ISSUE THREAD

**Issue by GreenSkinMonster** [tista500/Adapta#194]
Like --with-selection_color ?

Thank you for this great theme.

**Comment by GreenSkinMonster** [comment]
Hi, I found a dirty way to do it.

After ```make``` is done, run below two commands to replace all default title bar color  ```2a373e``` to the color you prefer, in my case ```3c3f41``` .

```bash
find . -type f|xargs sed -i 's/2a373e/3c3f41/g'
find . -type f|xargs sed -i 's/2A373E/3c3f41/g'
```
Then ```make install```, switch to another theme then go back, the new color should be there.

I know little about gtk+ theme, but I think this could solve my problem, so I close this issue.

Thanks.

**Comment by croisebeck** [comment]
i liked u user picture.
