### ISSUE TITLE
(Xfce4) Notification theming

### ISSUE THREAD

**Issue by stelariusinfinitek** [tista500/Adapta#195]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.8
 * Desktop environment - Xfce4
 ```

**Adapta version (if you knew)** 3.21.4.169

**Related Application and/or Shell theming (or name of widget)** xfce4-notifyd

**Actual issue** I installed Adapta today from AUR and the notifications are not themed. I could see an option for Adapta in the past. (Xfce4-notifyd had an update these days, could that be it?)

![screenshot_2016-08-12_23-15-54](https://cloud.githubusercontent.com/assets/18717816/17635960/ffdc7ae6-60e2-11e6-9b71-922f34414994.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
?? :eyes: 
Seems UI of GtkDialog has changed, so XFce4 uses Gtk+ 3.x? If so, Adapta does not support those newer/upcoming UIs in XFce4 yet. :(

Regards

**Comment by tista500** [comment]
Ah, Greybird did this: https://github.com/shimmerproject/Greybird/commit/0aa96d04d3596d8c93c092c796ac7d4a0a111923

**Comment by tista500** [comment]
Trial was committed: https://github.com/tista500/Adapta/commit/16aaa05807094eb0edafd9d9fae623e86f200072

But I don't know it may or may not work...

Regards.

**Comment by tista500** [comment]
Polished: https://github.com/tista500/Adapta/commit/123193a0056ee4ab5dc737683402bc11b85d3a10

**Comment by stelariusinfinitek** [comment]
Damn :) Good work!

![2016-08-13-100027_1366x768_scrot](https://cloud.githubusercontent.com/assets/18717816/17641946/cc7a5a7e-613c-11e6-8864-f2013797a10b.png)

**Comment by tista500** [comment]
Ugghh, not enough...

* drop-shadows were not drawn around that widget.
* `button` node's `label` colour was incorrect.

OK. I will rewrite later...

Regards.

**Comment by tista500** [comment]
2nd trial was committed: https://github.com/tista500/Adapta/commit/2b9f1fb18a36236601474bca25fc0458b7b16a47

I hope it could work as I expected, so let me see the result as screenshot again...

Regards.

**Comment by stelariusinfinitek** [comment]
Sorry, had some problems. I will post results today (Sunday here). Thanks!

**Comment by stelariusinfinitek** [comment]
This is what it looks like now : 

![screenshot_2016-08-14_13-29-55](https://cloud.githubusercontent.com/assets/18717816/17648573/46cab990-6223-11e6-92c5-d153e441164b.png)

**Comment by tista500** [comment]
OMG...

Hmm, 3rd trial was committed:  https://github.com/tista500/Adapta/commit/6bdd88b47d293147fc11f8abd6e6858e6a7318dd

It that commit did not work properly, I may have to remove all of drop-shadows from  ugly notifications.

Regards.

**Comment by stelariusinfinitek** [comment]
Sorry :/

![screenshot_2016-08-14_14-17-45](https://cloud.githubusercontent.com/assets/18717816/17648762/ef14f524-6229-11e6-887f-bc46b6d62ce3.png)

**Comment by tista500** [comment]
OK. Final commit was done: https://github.com/tista500/Adapta/commit/9e4a05e49f7ac0596d54191113c5b7144b371194

I've removed all of drop-shadow composition because it did not work at all as I expected...
Thanks for providing lots of screenshots and in this time this issue was closed, since I didn't have any ideas to do compositing with shadows, damned... :(

Regards.
