### ISSUE TITLE
Cinnamon calendar arrows hover

### ISSUE THREAD

**Issue by victormoreira** [tista500/Adapta#198]
**Reporter info**

 ```
 * Distribution - Manjaro Cinnamon
 * Gtk+ 3.0 version - 3.20.*
 * Desktop environment -  Cinnamon 3.0.7
 ```

**Adapta version (if you knew)**
Last

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Can you make a hover for calendar arrows ?

![hover](https://cloud.githubusercontent.com/assets/13660595/17709074/0fb06ef4-63be-11e6-9413-0365960bafb3.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/ecc57642cbf266927c3bde1245dad64b80535bb2

Regards.
