### ISSUE TITLE
Gnome Photos "Select" bug

### ISSUE THREAD

**Issue by tung9484** [tista500/Adapta#20]
![screenshot from 2016-03-18 01-53-53](https://cloud.githubusercontent.com/assets/15673389/13857509/ceba49b6-ecac-11e5-9a4d-0be5e6ebebe5.png)
![screenshot from 2016-03-18 01-54-06](https://cloud.githubusercontent.com/assets/15673389/13857512/d08f7d6a-ecac-11e5-9322-25f64b5e044f.png)

**Comment by tista500** [comment]
Fixed.

Regards.
