### ISSUE TITLE
xfwm4 - alt+tab support

### ISSUE THREAD

**Issue by mzpsh** [tista500/Adapta#200]
**Reporter Info**
```
* Distribution - Arch Linux
* Gtk+ 3.0 version - 3.20
* Desktop environment - xfwm4 (not full xfce apps)
 ``` 
**Adapta version - 3.21.4.193**
**Related Application - xfwm4**

Should add support for prettier and flat-er xfwm4 alt-tab appearance, like Arc theme did.

Adapta:
![2016-08-18-195228_1280x800_scrot](https://cloud.githubusercontent.com/assets/7564816/17773083/1744113a-657f-11e6-8709-6f63cc5c886b.png)

Expected result:
![2016-08-18-200331_1280x800_scrot](https://cloud.githubusercontent.com/assets/7564816/17773088/215011e2-657f-11e6-8ba2-687ecddd157d.png)

**Comment by tista500** [comment]
I don't have any ideas why I should mimic Arc theme... :/
If you liked Arc, please stop using Adapta and go back to Arc.

Anyway enhancement was committed: https://github.com/tista500/Adapta/commit/d7bb90d6c6c5bb9ccc7a8914437e66753c75f7ef

Regards.

**Comment by mzpsh** [comment]
Sorry, i mean, Arc as reference. By the way, many thanks.
