### ISSUE TITLE
Ubuntu's global menu extends when opening on an menu item

### ISSUE THREAD

**Issue by Defman21** [tista500/Adapta#201]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Unity 
 ```

**Adapta version (if you knew)** 3.21.4+git20160820-0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)** Appmenu

**Actual issue**

When you access an menu item in the globalmenu for first time in current session, the panel will be extended by 2 pixels because border-bottom will appear on the active element.

**Steps to reproduce (if you knew)**

Access an menu item in the global menu for first time in current session.

**Expected behavior**

No jump of height of the panel.

**Other Note (feature-request, question, etc...)**

To solve that, you can always render a transparent border for menu items in any menubar (it's being injected in the menubar of Unity) or don't draw it at all.

**Comment by tista500** [comment]
o_O ??
I could not reproduce with unity 7.4.0+16.04.20160801.2-0ubuntu1...
![untitled](https://cloud.githubusercontent.com/assets/6073622/17834920/f13f04f4-6790-11e6-849e-d51defc85632.png)

My shot keeps 24px height of `unity-panel` in case:
1. first login
2. open global-menu of Gnome-Terminal
3. open global menu of Firefox

> To solve that, you can always render a transparent border for menu items in any menubar (it's being injected in the menubar of Unity) or don't draw it at all.

I'm quite not sure why you were talking about `border-bottom` property though, Adapta does not use any borders to draw `.unity-panel.menubar.menuitem` style-class...
```
.unity-panel.menubar,
.unity-panel .menubar {
  background-color: transparent;
  background-image: none;
  box-shadow: none;

  &.menuitem,
  & .menuitem * {
    padding: 0 6px;
    border-radius: 0;
    border-bottom: none;
    background-color: transparent;
    color: $inverted_fg_color;
    &:hover {
      color: $selected_fg_color;
      box-shadow: inset 0 -2px $selected_bg_color;
    }
  }
}```

To draw underline-indicator, Adapta uses `box-shadow

**Comment by Defman21** [comment]
I thought you're using border-bottom, didn't know you can use box-shadow to get the same result. I'll dig more to see what's going on there.

**Comment by tista500** [comment]
??
You mean Firefox shrinks its GtkWindow height by itself around 2px?
If that was true, your issue is really related to Gtk+ theme? :(

Regards.

**Comment by Defman21** [comment]
I don't know what exactly Firefox shrinks. I'll try with the default theme.

**Comment by Defman21** [comment]
Yep, the default theme has the same problem (it's not the problem of a theme but something in Firefox). It's not related to your beautiful theme :)

**Comment by tista500** [comment]
Ah, I now confirmed Firefox shrinks its own GtkWindow height. And it happens with Numix theme as well.

Maybe when pulling GtkMenuBar form its GtkWindow and port it to unity-panel, Firefix's 'preferred_height' re-calculation might be canceled or forgotten, though I don't have any ideas to fix this....

Regards.
