### ISSUE TITLE
ibus font difficult to see

### ISSUE THREAD

**Issue by caoli5288** [tista500/Adapta#203]
```
Fedora-24 with gnome-shell-3.20.1
```
![2016-08-25 05-02-27](https://cloud.githubusercontent.com/assets/3120587/17948104/fcfcee38-6a14-11e6-9956-4d4436670bb0.png)

Some (chinese) word in i-bus is difficult to see because much smaller font than the default theme. It not good feel if I need to enter text for a long time. (on my 14'' laptop). It's a good idea to adjust the font size here.

**Comment by tista500** [comment]
o_O ??

Adawaita uses 11pt Cantarell font as default, and Adapta uses 10pt.
If -gtk-dpi was set to 96, usually:
```
11pt / 72pt/inch * 96px/inch = 14.667px
10pt / 72pt/inch * 96px/inch = 13.333px
```
So delta is equal to 1.33px only.
> ecause much smaller font than the default theme

I don't think that delta can be "much smaller"... :(
And so why don't you scale your fonts and Gtk+ widget before filing the report?

Regards.

**Comment by tista500** [comment]
Workaround was committed: https://github.com/tista500/Adapta/commit/c7466b7c7c4dd2b1e32302969a3d9955e3864068

Regards.

**Comment by caoli5288** [comment]
THX! Good luck for you:-)

**Comment by caoli5288** [comment]
The most beautiful theme that I have ever used! I love it! +1 for you!:-)
