### ISSUE TITLE
Inconsitent theming of tool bar in Yakkety, Unity

### ISSUE THREAD

**Issue by Mentis** [tista500/Adapta#204]
**Reporter info**

 ```
 * Distribution - Yakkety
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**
3.21.4+git20160824-2-0ubuntu1~yakkety1

**Related Application and/or Shell theming (or name of widget)**
Nautilus, Gedit

**Actual issue**
Inconsistent theming of "window decorations"/"tool bar". Some apps have dark line between tool bar and window decoration (like Nautilus), some apps don't (like Gedit)
![default](https://cloud.githubusercontent.com/assets/273806/17980058/7903d422-6ab2-11e6-8ab1-795bde404c4b.png)

![default](https://cloud.githubusercontent.com/assets/273806/17980096/a225a10a-6ab2-11e6-953f-5321187d76ed.png)

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Unity7 needs tons of extra tweaks which we don't need in GNOME environment. And in most case, those are ugly, this is because I REALLY want to purge Unity7 support.

I don't have any solutions to cover all of such Canonical's changes. I mean "won't fix". I think Unity7 is cancer of Gtk+ 3.x. So don't expect too much. I'm going to track down this issue though...

Regards.

**Comment by tista500** [comment]
Workaround was committed: https://github.com/tista500/Adapta/commit/dd9d814955fb2a0f0249afa2bab84cad24cf17b1

**Comment by Mentis** [comment]
Thanks man! Thank you for maintaining such a great theme. Unfortunately I found Unity the only usable DE at the moment. It is really hard to use gnome shell due to this:
![1](https://cloud.githubusercontent.com/assets/273806/17987099/fcbd4e22-6ad2-11e6-997d-f664fb7a6eb1.png)

Global menu + "hiding windows title bar for maximized windows" is great usability features that only Unity offers.

**Comment by tista500** [comment]
Hey hey, it's not the GNOME's fault but application side... :(

GtkHeaderBar can save the vertical space than Compiz + GtkToolBar. And most remarkable thing is Compiz is really unstable and outdated code-base today. Actually Canonical devs did NOT enhance and maintain it for many years...
