### ISSUE TITLE
Adapta-Nokto with custom .gtkrc file for just dedicated applications.

### ISSUE THREAD

**Issue by tamastoth-ebola** [tista500/Adapta#206]
Hello!

As for the environment I use the latest Adapta from the official PPA with Ubuntu Gnome 16.04.

As I don't know yet that this is my fault or the theme this is why I try to ask for a help from you.

I tried to make a custom .gtkrc file (as the required applications uses just GTK2 yet) with Adapta-Nokto theme. I put the basic GTK theme and also the required 'light' icon theme (which is Papirus-Dark-GTK) in the file. The whole thing is because I need dark theme especially just for Inkscape and Gimp.

The content of the file is (the direct links for the .rc files instead of the original gtkrc is just because I tried that the problem is maybe just because the multi level includes but sadly not as the results are the same with both ways):

```
# To set the GTK theme.
include "/usr/share/themes/Adapta-Nokto/gtk-2.0/colors-dark.rc"
include "/usr/share/themes/Adapta-Nokto/gtk-2.0/common-dark.rc"
include "/usr/share/themes/Adapta-Nokto/gtk-2.0/misc-dark.rc"
include "/usr/share/themes/Adapta-Nokto/gtk-2.0/3rd-party-dark.rc"

# To set the icon theme.
gtk-icon-theme-name = "Papirus-Dark-GTK"
```

When I pull the related applications with this custom .gtkrc file the success is just half. I get fully light icons (what I wanted) but just with half way applied dark theme. The select boxes are dark and some others also, but the 70% of the applications still use the same light theme.

Could anybody help me what is the real problem? With the settings above could be our desktop environment totally a modern and nicely applicable for graphical works.

Anyway thanks for this fantastic theme. It is blown away any other in my eyes!

Thanks in advance!

**Comment by tista500** [comment]
The real problems behind the scene is your favorite Apps were not ported to Gtk+ 3.x.

And Gtk+ 2.x still has some limitations compared with 3.x.
* 2.x does not have any features to "re-colour" symbolic icons.
* 2.x does not have application-specific colour-variant feature.
* 2.x does not accept "dynamic reloading" in colour-scheme.

Those meant to be:
* We can not override selected-theme's gtk-color-scheme on demand when applications were loaded. So "mixed-variant" could not be realized (as far as I know).

As of some articles in Web, user-specific `.gtkrc-2.0` in XDG user home directory might be able to override some parts of Gtk+ 2.x themes, But at least I don't have any clue to override `gtk-color-scheme` dynamically (I did not read the source of Gtk+ 2.x yet though)...

Regards.

**Comment by tista500** [comment]
I suppose you'd better to contact upstream Gtk+ developers...

Closed.
