### ISSUE TITLE
Notebook-friendly version of Adapta?

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#207]
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - 3.21.90
 * Desktop environment -  Gnome 3.21.90
 ```

**Adapta version (if you knew)**
latest git master

**Other Note (feature-request, question, etc...)**
It would be nice if you could provide a notebook-friendly version of the theme with smaller decorations - like the "laptop" version of the current Flat Plat release

**Comment by tista500** [comment]
See #199 and #187.

I don't think it's not "notebook friendly" but "poor resolution friendly". :/

Regards.
