### ISSUE TITLE
Request: Evolution theming

### ISSUE THREAD

**Issue by Feichtmeier** [tista500/Adapta#209]
![bildschirmfoto vom 2016-08-28 18-32-31](https://cloud.githubusercontent.com/assets/15329494/18127390/6371a012-6f80-11e6-9408-07b9d6bc4904.png)

**Reporter info**

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**
Always up to date through the ppa 

**Related Application and/or Shell theming (or name of widget)**
Evolution Mail & Calendar

**Actual issue**
Would it be possible to change those ugly event frames in evolution? The rest looks perfect. Look at the screenshot and you will see what I mean :dart: 

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@Feichtmeier,

Ah, unfortunately Adapta did not have any specific stylings for Evolution.
Evolution is a bit tough thing to polish the styling, anyway I will do it after I've got much time to develop for it...

Regards.

**Comment by tista500** [comment]
In Gtk+ 3.2x, Evolution has lots of "hard-coded" widgets which we could not override from user-side CSSs, So I gave up... :(

I'm sorry I could no help you...
Regards.
