### ISSUE TITLE
Bar color in F-key popups

### ISSUE THREAD

**Issue by fb87** [tista500/Adapta#211]
**Reporter info**
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3

**Adapta version (if you knew)**
Latest

**Related Application and/or Shell theming (or name of widget)**
F-key popups.

**Actual issue**
In contrast to an older version of Adapta I installed on another machine, I don't have green colored bars when pressing the F-keys (louder / quieter / brighter / darker), but instead see the default style.

**Steps to reproduce (if you knew)**
Pressing louder/quieter/brighter/darker.

**Expected behaviour**
Slim and green colored bar in the popup.

Many thanks for a fix! :)

**Comment by tista500** [comment]
Hmm, if you meant "level-bar", works for me as I expected with latest git snapshot:

![screenshot from 2016-09-03 07-05-29](https://cloud.githubusercontent.com/assets/6073622/18219541/5488e0fc-71a5-11e6-9f6b-4384537300ff.png)

**Comment by fb87** [comment]
Yes, this doesn't work for me on my laptop and on my HTPC, but on my laptop at work somehow it works...

**Comment by tista500** [comment]
> But the lockscreen isn't themed. Would be nice if you could theme this, too! :)

Please do googling.... Adapta already bundled gresource file. :(

Closed.

**Comment by fb87** [comment]
Tried it with gdm3setup, but that didn't work on Fedora 24. :( If you got a hint for me, I would appreciate it!
