### ISSUE TITLE
Window indicators in dock are partly hidden

### ISSUE THREAD

**Issue by fb87** [tista500/Adapta#212]
**Reporter info**

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 3
 ```

**Adapta version (if you knew)**
Git master.

**Related Application and/or Shell theming (or name of widget)**
Dock of the Gnome extension „Dash To Dock“.

**Actual issue**
Like you see in the screenshot, Adapta introduces a circle around each application symbol, which hides the first and the fourth dot almost completely and even parts of the second and third one.
![auswahl_012](https://cloud.githubusercontent.com/assets/10520767/18224572/b79e8842-71da-11e6-8360-bd7d7db6cfea.png)

DTD also allows displaying indicators for each window, if I activate this, they get overlayed:
![auswahl_012](https://cloud.githubusercontent.com/assets/10520767/18224602/04ed1554-71dc-11e6-8b17-81bf565af619.png)

**Steps to reproduce (if you knew)**
Install and activate Dash To Dock

**Expected behaviour**
All four dots should be shown completely.

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/c7f7761ff3ffb7cb85087b9d31247259af10ff59

Regards.

**Comment by fb87** [comment]
Sorry to bother you again, but do you mind narrowing the space between the dots a little bit? Think this looks a tad better (like DTD does). What do you think?
