### ISSUE TITLE
Error :: ./autogen.sh: autoreconf: not found

### ISSUE THREAD

**Issue by smartclash** [tista500/Adapta#213]
I am using the latest version of Adapta, GTK and Ubuntu(16.04.1)

When i just executed the command `./autogen.sh` in the Adapta DIR, i get the following error `./autogen.sh: 11: ./autogen.sh: autoreconf: not found`

Why is that happening? I just installed the Ubuntu into my system. Is there anything i need to do before installing this theme?

**Comment by GhettoGirl** [comment]
From the README, read the README first next time. There is a reason why such things exist :grimacing: 

> build-requirements
> * autoconf
> * automake
> * inkscape
> * libglib-2.0-dev (glib2)         >= 2.48.0
> * libxml2-utils (libxml2)
> * pkg-config (pkgconfig)
> * ruby-bundler (rubygem-bundler)  >= 1.11
> * ruby-sass (rubygem-sass)        >= 3.4.21

**Comment by tista500** [comment]
I know nobody read the README.

Closed.

**Comment by smartclash** [comment]
@tista500 @GhettoGirl Sorry guys, i am new to ubuntu. That's why
