### ISSUE TITLE
Background color for selected text in GNOME Files

### ISSUE THREAD

**Issue by ppgllrd** [tista500/Adapta#214]
Is there an easy way to change background color for selected text in GNOME Files? Currently (see word New in attached picture), the only effect applied to such text is that it looks slightly brighter than non-selected one. I would like to use a different background color for this
![captura de pantalla de 2016-09-06 02 05 47](https://cloud.githubusercontent.com/assets/4742844/18258537/e7a6b614-73d7-11e6-8aca-4b3634efd098.png)
Thanks

**Comment by tista500** [comment]
Those are the reasons why I will NOT help you.

* Ignored issue template.
* I've never done such theming like what your attached shot showed.
* Here's not the help forum.

Regards.

**Comment by ppgllrd** [comment]
_- Ignored issue template._ 
My fault, sorry

_- I've never done such theming like what your attached shot showed._ 
That's the theme as downloaded from this repo without any modification.

_- Here's not the help forum._
Is it anywhere else?

Regards to you too.
