### ISSUE TITLE
Selected color on ALT+TAB menu is too dim

### ISSUE THREAD

**Issue by xpduyson** [tista500/Adapta#218]
**Reporter info**

 ```
 * Distribution - Debian Testing
 * Gtk+ 3.0 version - 3.21.92
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)**
[lasted git commit](https://github.com/tista500/Adapta/commit/c19c1b1bab5e1c0862ca6c692c4c7ca3341654da)

**Other Note (feature-request, question, etc...)**
Selected color on ALT+TAB menu is too dim, I can't see clearly what program is selected. Could you make it a little contrast, make it more visible?
Here are 2 real "screenshot" to describe, the first one is Adapta, the second one is Adwaita.
![img_20160915_144112](https://cloud.githubusercontent.com/assets/6981890/18542395/deaba284-7b54-11e6-9c37-2192d7346bae.jpg)
![img_20160915_144404](https://cloud.githubusercontent.com/assets/6981890/18542396/deb2a1c4-7b54-11e6-8bfd-9b4c911aba3c.jpg)

**Comment by tista500** [comment]
Workaround was committed: https://github.com/tista500/Adapta/commit/8ef73ca08117fc1a766b8307ed5d35ca3ea00276

Regards.
