### ISSUE TITLE
git master fails to build

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#22]
Current git master fails to build since yesterday

> make[1]: Entering directory '/builddir/build/BUILD/Adapta-b4ab22e7537438d3c77811a354f47db69913201d'
make[1]: Nothing to be done for 'install-exec-am'.
make  install-data-hook
make[2]: Entering directory '/builddir/build/BUILD/Adapta-b4ab22e7537438d3c77811a354f47db69913201d'
test -e /builddir/build/BUILDROOT/Adapta-3.18.9-1.201603191305gitb4ab22e.fc24.x86_64/usr/share/themes/Adapta && \
rm -rfv /builddir/build/BUILDROOT/Adapta-3.18.9-1.201603191305gitb4ab22e.fc24.x86_64/usr/share/themes/Adapta
Makefile:558: recipe for target 'install-data-hook' failed
make[2]: Leaving directory '/builddir/build/BUILD/Adapta-b4ab22e7537438d3c77811a354f47db69913201d'
make[2]: *** [install-data-hook] Error 1
make[1]: *** [install-data-am] Error 2
Makefile:489: recipe for target 'install-data-am' failed
make[1]: Leaving directory '/builddir/build/BUILD/Adapta-b4ab22e7537438d3c77811a354f47db69913201d'
Makefile:443: recipe for target 'install-am' failed
make: *** [install-am] Error 2

**Comment by tista500** [comment]
@HeikoAdams,

Revert commit: 2195f5f650bff8fadca6969f98bc120b44931e33
So check if that commit could solve this issue.

Regards.

**Comment by HeikoAdams** [comment]
Yes, that solves the issue

**Comment by tista500** [comment]
OK.Closed.

Regards.
