### ISSUE TITLE
Laptop Gnome Shell version

### ISSUE THREAD

**Issue by miguelcarax** [tista500/Adapta#220]
Could be possible a laptop version of the upper bar (Gnome-Shell)  in Gnome like [Flat-Plat](https://github.com/nana-4/Flat-Plat)? Thanks!

**Comment by tista500** [comment]
No. Go back to Flat-Plat.

**Comment by tista500** [comment]
I've committed some changes: https://github.com/tista500/Adapta/commit/703e644570388cb8d4d23c90b7933915c9211b24
