### ISSUE TITLE
Fedora installation

### ISSUE THREAD

**Issue by TimurEke** [tista500/Adapta#221]
On Fedora (24) the command `which` is not available, so `make` will throw errors. So executing `perl -e "s|\`which\ inkscape\`|INKSCAPE LOCATION|g;" -pi $(find . -type f)` in the Adapta directory will replace all occurrences of `which inkscape` with the location, where inkscape is located(they are listed in `whereis inkscape`). I hope this will save a couple of hours in your life.

**Comment by TimurEke** [comment]
Maybe add that to README.md?

**Comment by stesachse** [comment]
```
$ cat /etc/fedora-release
Fedora release 24 (Twenty Four)
$ type -a which
which is aliased to `(alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot'
which is /usr/bin/which
$ rpm -qf /usr/bin/which
which-2.20-13.fc24.x86_64
```

which is in the following package groups (sed stolen from [here](http://unix.stackexchange.com/a/236975))

```
$ dnf group info '*' | sed -n '/Group:/h;/'"  which"'/{x;p;x;p}'
Group: Fedora Workstation product core
   which
Group: Standard
   which
Group: Buildsystem building group
   which
```

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/66067402c4e2cc96846b39469506a6470b52f7e7

Regards.
