### ISSUE TITLE
Some configuration buttons are missing in Raven - (Budgie Desktop)

### ISSUE THREAD

**Issue by Udara-U3** [tista500/Adapta#222]
**Some configuration buttons are missing in Raven (Budgie Desktop)**

 ```
 * Distribution - budgie-remix 16.10
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Budgie 
 ```

**Adapta version (if you knew)**
3.21.6 via PPA

**Related Application and/or Shell theming (or name of widget)**
Budgie Desktop - Raven sidebar

**Actual issue**
Some configuration buttons are missing

**Expected behaviour**
Buttons should appear in Raven

![adapta_issue](https://cloud.githubusercontent.com/assets/12265797/18633035/6a47e5ee-7e8b-11e6-9494-70b2e0092e03.jpg)

**Comment by tista500** [comment]
@Udara-U3,

Without screen configuration info, how could I reproduce? :(

**Comment by tista500** [comment]
Raven is the vertically scrollable widget. and if you had such 768px height of the screen (or x2 scaling from QHD or QHD+), use Adapta-Eta variant.

I can't help you.

Regards.
