### ISSUE TITLE
logout dialog menu display error

### ISSUE THREAD

**Issue by juvevood** [tista500/Adapta#224]
* Gtk+ 3.0 3.20.2
 * Desktop environment:Budgie-Desktop 10.2.7
 * Adapta version :3.22.0.11

![screenshot from 2016-09-22 16-06-36](https://cloud.githubusercontent.com/assets/1421513/18740915/d803bc48-80de-11e6-8799-e65739a9b1a9.png)

**Comment by tista500** [comment]
This might be related to https://github.com/solus-project/budgie-desktop/commit/ff92bee9edc0637321cdb5f55eaf587fda3d8082.

Regards.

**Comment by juvevood** [comment]
nice patch.it's work!

**Comment by tista500** [comment]
So I think I have few things to do with this issue, upstream will fix automatically, I hope...;)

Closed.
