### ISSUE TITLE
Light theme not working

### ISSUE THREAD

**Issue by sejr** [tista500/Adapta#225]
**Reporter info**

 ```
 * Distribution - Ubuntu 16.04.1
 * Gtk+ 3.0 version - Latest
 * Desktop environment - Latest
 ```

**Adapta version (if you knew)**

Latest

**Related Application and/or Shell theming (or name of widget)**

Application

**Actual issue**

When I install Adapta it is the dark theme by default. Is the light theme still available?

**Steps to reproduce (if you knew)**

Install the latest version of Adapta and select via Tweak Tool.

**Expected behaviour**

Should display light theme.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> Desktop environment - Latest

Which part are you talking about? I can't get any info in your report... :(

Regards.

**Comment by tista500** [comment]
No response in 6 days, Closed.
