### ISSUE TITLE
[readme]dependency package name error

### ISSUE THREAD

**Issue by alim0x** [tista500/Adapta#226]
line 114 in readme:

```
 * libglib-2.0-dev (glib2)         >= 2.48.0
```

This package's name should be 

```
 * libglib2.0-dev (glib2)         >= 2.48.0
```

[ubuntu](http://packages.ubuntu.com/xenial/libglib2.0-dev)
[debian](https://packages.debian.org/sid/libglib2.0-dev)

**Comment by tista500** [comment]
Fix was committed:  https://github.com/tista500/Adapta/commit/7d92809cfcc8c4977cc774d3bf6312306aff3c95

Regards.
