### ISSUE TITLE
Thunar Dark Toolbar

### ISSUE THREAD

**Issue by rauldipeas** [tista500/Adapta#227]
**Reporter info**

 ```
 * Distribution -
AviX 3.2(Ubuntu 16.04.1)
 * Gtk+ 3.0 version -
GTK+ 3.18
 * Desktop environment - 
XFCE 4.12
 ```

**Adapta version (if you knew)**
From Xenial PPA

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

How can I set Thunar toolbar to get dark color?

**Comment by tista500** [comment]
Adapta does not recommend any dark GtkToolBars in light-variant.
If you'd like to make it for personal use, see Arc theme since Arc seems to have Thunar specific theming (what Adapta does not have). Anyway I can't help you...

Regards.
