### ISSUE TITLE
Use opensuse build service

### ISSUE THREAD

**Issue by Arjoni** [tista500/Adapta#228]
Can you please use opensuse build service to create packages and repos for all distros? This way, we don't miss any update. https://build.opensuse.org/

**Comment by tista500** [comment]
Adapta packages are already provided via ppa, copr, aur, and ypkg by contributors on each distributions.
So why external build-service was needed? Gentoo?

Regards.

**Comment by tista500** [comment]
7days no response, closed.

**Comment by cbcoutinho** [comment]
I would like to reopen this - I use OpenSUSE and would like to use the OBS whenever possible

**Comment by tista500** [comment]
@cbcoutinho,

Isnt' enough? https://github.com/adapta-project/adapta-gtk-theme#installation-from-packages
Oh please... :(

**Comment by cbcoutinho** [comment]
Oops, I didn't click enough links on the opensuse site to find what I was looking for (this page https://software.opensuse.org/download.html?project=home%3ARonis_BR&package=adapta-gtk-theme)

Sorry for the short-sidedness!
