### ISSUE TITLE
Window close button broken (duplicated icon)

### ISSUE THREAD

**Issue by ZOezdem** [tista500/Adapta#229]
**Reporter info**

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - 3.20.9-1
 * Desktop environment - gnome 3.20.2
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**
Terminal / firefox

**Actual issue**
Close Button is duplicated

**Steps to reproduce (if you knew)**
installed directly from github and also tried the copr repository for fedora.
After choosing the theme with gnome-tweak-tool

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by ZOezdem** [comment]
Here is a screenshot of the terminal:
![terminal-example](https://cloud.githubusercontent.com/assets/10046739/19019861/f8f13c8c-8895-11e6-851c-97884f5f1932.png)

**Comment by paulle** [comment]
close, minimize, maximize buttons duplicated in libreoffice, firefox and other programs.

**Comment by tista500** [comment]
Hmm, revert commit: https://github.com/tista500/Adapta/commit/b8debcb856306df7bca7d5e7e327e2714a4371e6

Closed.

**Comment by paulle** [comment]
Thak you for the fix, double buttons are gone.
