### ISSUE TITLE
[Gtk+ 3.20] [Info from Dev] Tons of issues and switching to 3.20 as Master

### ISSUE THREAD

**Issue by tista500** [tista500/Adapta#23]
Greetings,

Today I've rebooted refactoring theming, but unfortunately I've experienced tons of visual issues on my Adapta...

So please wait for my fixes to be landed on new Master. After releasing 3.20, 3.18.x will be moved to another branch as 'legacy' (maybe it will be named 3.18.x or so).

Regards.

**Comment by zor1984qq** [comment]
so sad ;(...

**Comment by tista500** [comment]
@zor1984qq,

Yeah Gtk+ 3.20 is a fantasy... :cry: 
But I will replace whole things in Master with Gtk+ 3.20 tonight because development focus is now on 3.20 or higher.

Regards.

**Comment by tista500** [comment]
Master branch is now replaced with Gtk+ 3.20 theming...

Regards.
