### ISSUE TITLE
Xfce4 Panel background not transparent on Indicator Applet 

### ISSUE THREAD

**Issue by tstarboy** [tista500/Adapta#230]
**Reporter info**
 ```
 * Distribution - Xubuntu 16.04
 * Gtk+ 3.0 version - 3.18
 * Desktop environment - Xfce4
 ```

**Adapta version (if you knew)**
3.22.1

**Related Application and/or Shell theming (or name of widget)**
xfce4-panel

**Actual issue**
The .xfce4-panel class inside gtk-3.0/gtk.css sets a background color. This causes the Indicator Applet to draw a background set to that color, rather than respecting the panel settings.
With transparent background:
![02-10-2016_selection_0010](https://cloud.githubusercontent.com/assets/22086580/19024133/f8222d18-88ca-11e6-8a0a-803144bae732.png)
With opaque background:
![02-10-2016_selection_0014](https://cloud.githubusercontent.com/assets/22086580/19024154/78c35f8c-88cb-11e6-9b3e-68a17c8cb30a.png)

**Steps to reproduce (if you knew)**
Add a GTK3.0 applet to an Xfce4 panel with transparent background

**Expected behaviour**
The background-color property on .xfce4-panel and its children should be set to transparent. This will allow the Indicator Applet panel to follow whatever configuration is set on the panel itself.
With transparent background:
![02-10-2016_selection_0011](https://cloud.githubusercontent.com/assets/22086580/19024140/214ab3cc-88cb-11e6-88fb-3906f1df12ff.png)
With opaque background:
![02-10-2016_selection_0013](https://cloud.githubusercontent.com/assets/22086580/19024147/4c633c64-88cb-11e6-8417-16eb81731794.png)

**Comment by tista500** [comment]
We're now evaluating #130. The priority of this issue is lower than that one.

Regards.

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/e78ad6776fab86f8c375c293bb9cd8de953d9af8

Regards.

**Comment by tstarboy** [comment]
Thank you!
