### ISSUE TITLE
The dark theme is still too light for me

### ISSUE THREAD

**Issue by Alsan** [tista500/Adapta#232]
I'd like to use a even darker color as the background of the dark them, which value should I change?

**Comment by tista500** [comment]
https://github.com/tista500/Adapta/blob/master/gtk/sass/common/_colors.scss
https://github.com/tista500/Adapta/blob/master/gtk/gtk-2.0/colors-dark.rc.in
https://github.com/tista500/Adapta/blob/master/gtk/asset/assets-gtk3.svg.in
https://github.com/tista500/Adapta/blob/master/gtk/asset/assets-gtk2.svg.in
https://github.com/tista500/Adapta/blob/master/shell/sass/common/_colors.scss
and some other SVGs.

Regards.

**Comment by Alsan** [comment]
Thanks, I'll try to make the modification.
