### ISSUE TITLE
Font is small and not spaced well in budgie menu

### ISSUE THREAD

**Issue by tristan957** [tista500/Adapta#233]
**Reporter info**

 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Budgie
 ```
![screenshot from 2016-10-05 10-35-46](https://cloud.githubusercontent.com/assets/11936772/19120357/223a652e-8ae8-11e6-85b3-23f755ed1bcb.png)

**Adapta version (if you knew)** 3.22.1.12

**Related Application and/or Shell theming (or name of widget)** Budgie Menu

**Actual issue** Font is small and not spaced well

**Steps to reproduce (if you knew)** Open the Menu

**Expected behaviour** Bigger font with better spacing

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
> Font is small and not spaced well
The same font-size should be applied in both left and right pane.
And vertical spacing is the same value with other GtkPopover.

I don't think I have to change anything...

Regards.

**Comment by tista500** [comment]
Enhancement was done: https://github.com/tista500/Adapta/commit/6f4fa95d9849a36264fcdbb4faa28637caf07a8f

Regards.

**Comment by tristan957** [comment]
Thanks!
