### ISSUE TITLE
Openbox theme?

### ISSUE THREAD

**Issue by zecoj** [tista500/Adapta#234]
Love the theme so much but there isn't an accompanying openbox theme. Please consider this when you have time.

**Comment by tista500** [comment]
Openbox is not the themeable stuff for me.

* Openbox could not accept for border-radius of window-frames.
* Openbox could not handle any of compositors.
* Drop-shadows are rendered by 3rd-party "stand-alone" compositor without Gtk+ integration.
* There's no plan to support LXDE.

Regards.

**Comment by zecoj** [comment]
Thanks for that. It's a shame but I was able to quickly create one to make it look a bit more uniform.
https://dl.dropboxusercontent.com/u/7959866/adapta-nokta-openbox.png

Cheers

**Comment by tista500** [comment]
Hmm, I now have some questions:

* Why focused and un-focused windows are exposed with the same depth? I mean drop-shadows seems to be same between them and it's very incorrect.
* Where is the top-edge border of window-frame? In Material Design, Window should have 1px thickness (depth).
* Context-menus should not be drawn with transparentized materials. Those widgets are not the OnScreenDisplay.
* Close/Max/Min/Menu buttons should be modified with free-form design.
* Context-menu hovered items should be drawn with highlight text colours.
* Actual windows did not have any rounded-corders but shadows had very rounded one. It's weird in real world if delta of z-axis between windows and backgrounds is not so large.

Regards.

**Comment by zecoj** [comment]
I'm not a themer so can't answer these questions, just created this so the window decorations don't look out of place.

**Comment by tista500** [comment]
It's OK.
But unfortunately your shot is out of place for me already. :(
If my questions above are stemmed (related) to the technical limitation of Openbox itself, yeah I should say again "Openbox is not the themeable stuff"...

If you had already committed that theming to your github, please let me see.

Regards.

**Comment by zecoj** [comment]
I've created a new repo: https://github.com/zecoj/adapta-openbox

Also to address some of your points earlier: 

- The compostion is done by compton, so drop shadow and transparency are done there.
- Context menu you mentioned is openbox's system-wide menu.
- I don't think openbox can have top border only for the window decoration, all four are to be applied

You're right in saying that openbox is not flexible in term of theming. It was never really designed to look great but rather to be functional and lightweight.

**Comment by tista500** [comment]
OK. I'll check later...

Regards.

**Comment by tista500** [comment]
Merge was done: https://github.com/tista500/Adapta/commit/8039718c26ea600358a54c69210b7281ef312b4e

Anyway I may have to polish close button appearance again if I got much time to do it... ;P

Regards.

**Comment by tista500** [comment]
Forgot to mention.

It's now OK to close your repo: https://github.com/zecoj/adapta-openbox

Thanks for your implementation... :smile:

Best Regards.

**Comment by zecoj** [comment]
cheers thanks again
