### ISSUE TITLE
Unity top panel bgcolor should be the same as titlebar bgcolor

### ISSUE THREAD

**Issue by Sadi58** [tista500/Adapta#235]
This happens in some themes; when chosen, the unity top panel bgcolor does not look the same as the (active) window titlebar.
This might be due to a design choice or lack of unity experience but - whatever the reason - the result is that when a window is maximised unity panel also serves as the titlebar (and even menubar) of the maximised window, and then suddenly one sees a change in titlebar bgcolor.
This also results in another problem with some applications: For instance, Thunderbird and Google Chrome / Chromium display two different stripes of bgcolors at the top of the window.
```
 * Distribution - Ubuntu 16.04
 * Desktop environment - Unity
 * Adapta version - The latest in launchpad
```

**Comment by tista500** [comment]
Hmm, I think this issue is a part of Unity itself and I don't have any clue why you asked me...
I've experienced much of painful theming breakages in Unity7 desktop. To be honest, Unity7 support was my worst fault in Adapta.

> panel bgcolor should be the same as titlebar bgcolor

Disagreed unfortunately.

Regards.

**Comment by Sadi58** [comment]
I tried changing `background-color` value of `UnityPanelWidget, UnityPanelWidget:backdrop, .unity-panel, .unity-panel:backdrop` to `#2A373E` but it also produced a similar inconsistency, this time displaying  toolbar bgcolor as `#13191c`
I thought you can find a solution to this...

**Comment by tista500** [comment]
> this time displaying toolbar bgcolor as #13191c

o_O ??
There's no GtkToolBar with `$panel_bg_color` in Adapta, so I don't know what are you talking about...
And your approach seems to be going to break GNOME environment. If it was true, please stop spreading out such things here. GNOME environment is most important thing in Adapta.

**Comment by tista500** [comment]
Unfortunately I won't solve this issue.
> two different stripes of bgcolors at the top of the window

Even if it were solved, it improves nothing. In Android (Material Design), top-bar should be drawn with different and darker colours.

But feel free to tweak Adapta for personal use only, since Adapa is under GPL-2.0 license. Like this:
```diff
--- a/gtk/sass/3.18/_3rd-party.scss
+++ b/gtk/sass/3.18/_3rd-party.scss
@@ -1095,8 +1095,8 @@ UnityDecoration { // FIXME: do not use scalable units
 UnityPanelWidget,
 .unity-panel {
   &, &:backdrop {
-    border-bottom: 1px solid $panel_bg_color;
-    background-color: $panel_bg_color;
+    border-bottom: 1px solid $inverted_dark_color;
+    background-color: $inverted_dark_color;
     color: $inverted_fg_color;
     box-shadow: none;
   }
@@ -1123,12 +1123,21 @@ UnityPanelWidget,
 }
 
 // workaround for stupid compiz
-.background:not(.csd):not(.ssd):not(.solid-csd) .header-bar {
-  &, &:not(:last-child) {
-    padding: 0.4em;
-    border-radius: 0;
-    border-top-color: transparent;
-    box-shadow: $menubar-shadow;
+.background:not(.csd):not(.ssd):not(.solid-csd) {
+  &,
+  &.maximized,
+  &.tiled {
+    .header-bar {
+      &, &:not(:last-child) {
+        padding: 0.4em;
+        border-radius: 0;
+        border-width: 1px 0 1px;
+        border-top-color: transparent;
+        border-bottom-color: $borders_color;
+        background-color: $inverted_dark_color;
+        box-shadow: $menubar-shadow;
+      }
+    }
   }
 }
```

Regards.

**Comment by Sadi58** [comment]
I fully understand you, and thanks a million for showing how to tweak for personal use!
