### ISSUE TITLE
Buttons on the titlebars of Qt apps are missing with -Eta themes

### ISSUE THREAD

**Issue by KenetJervet** [tista500/Adapta#236]
**Reporter info**

 ```
 * Gentoo -
 * Gtk+ 3.22 version -
 * GNOME - 
 ```

**Adapta version (if you knew)**
3.22.1.42

**Actual issue**
In *-Eta themes, buttons on the titlebars of Qt apps are missing (e.g. konversation, shadowsocks-qt5)
They still work, if you click on the correct position. They are just not shown.

**Expected behaviour**
Buttons are displayed correctly.

**Comment by tista500** [comment]
o_O ??

I'm not a K desktop user so I'm not really sure what  konversation 1.6.1 is, but it seems nornal with Mutter 3.22.0 and Gtk+ 2.x theming on Gnome-Shell 3.22.0:
![screenshot from 2016-10-08 12-43-37](https://cloud.githubusercontent.com/assets/6073622/19210138/1e9cb1d2-8d55-11e6-924c-9fb94f7df30e.png)

Server-side decoration seems works as I expected.

**Comment by KenetJervet** [comment]
Sorry man it turned normal! _(:з」∠)_ Didn't know what happened. Now everything works as expected.
Thanks for your attention_(:з」∠)_

**Comment by tista500** [comment]
No problem.. ;)
