### ISSUE TITLE
Dolphin file manager

### ISSUE THREAD

**Issue by LZL0** [tista500/Adapta#237]
Hello tista500,

Will Dolphin, the file manager get its own styling?
I believe it would be a wonderful addition to Adapta.

Keep up the great work!

**Comment by tista500** [comment]
> I believe it would be a wonderful addition to Adapta.

That file-manager is REALLY needed by many of Gtk+ desktop users?
At least I don't need it.

If you had some issues in existed Gtk+ file-managers, you should first file a issue-report/feature-request to its development team before installing K desktop applications into Gtk+ desktops, isn't it?
I think this request is not the root/stem of your issue...

Finally Adapta is not Qt theme but Gtk+ theme.

Regards.

**Comment by LZL0** [comment]
Yep, agreed.

**Comment by tista500** [comment]
I've experienced some technical limitations of Qt integration for Gtk+ desktop. Unfortunately I have few things to help "mixed" desktop uses. :(

Regards.

**Comment by LZL0** [comment]
I just wanted to submit it as an idea. I checked out Dolphin and it looks very cool, it has a very similar look to TotalCommander. :) Unfortunately with Adapta (as of today) I am unable to use it, because of the styling.
Other than that you are really doing a great job with Adapta, keep it up! :+1:
