### ISSUE TITLE
Nautilus dim-label

### ISSUE THREAD

**Issue by Sadi58** [tista500/Adapta#238]
I wonder if the following line can be added to the **Nautilus** section of `gtk.css` with a view to having file sizes/folder contents displayed in **grey** color (or any other color **different from file/folder names**)

 ```
.nautilus-canvas-item.dim-label, .nautilus-list-dim-label { color: #B6BAC4; }�
```
Pictured left is the current state, and pictured left is the desired state in another theme:
![nautilus dimmer 1-horz](https://cloud.githubusercontent.com/assets/6375934/19222539/bf8c38b2-8e52-11e6-85e6-8c3922d85b53.jpg)
 ```
 * Ubuntu 16.04
 * Gtk+ 3.18
 * Unity 
 * Adapta git version
 ```

**Comment by tista500** [comment]
Nautilus 3.14.x is only for Ubuntu users in Gtk+ 3.18.x.
It means there's few reasons to improve/support such breakage in GNOME. And in Adapta, active development of Gtk+ 3.18.x theming is almost over.

Anyway committed: https://github.com/tista500/Adapta/commit/eef25b0ad17e3285574a37d5bb9129343d052687

**Comment by Sadi58** [comment]
Thanks! I wish Ubuntu and Gnome worked more in harmony - at least for the sake of efficiency ;-)

**Comment by Sadi58** [comment]
After system upgrade, this issue came back to me ;-)
