### ISSUE TITLE
Thunderbird - Compose Window, Quicktext bar

### ISSUE THREAD

**Issue by Sadi58** [tista500/Adapta#239]
I'm not sure it this is due to a flaw in Quicktext, a Thunderbird Addon, but I don't have a similar problem in some other themes.
Quicktext inserts a bar right above the message pane of Compose window enabling user to quickly insert user-defined texts as well as some standard variables.
Adapta themes uses a dark bgcolor there with a slightly darker fgcolor, unlike the Formatting Toolbar right above it.

Pictured below is the Adapta behaviour (top), and the expected behaviour (bottom)
![thunderbird quicktext](https://cloud.githubusercontent.com/assets/6375934/19223710/707d1234-8e6e-11e6-8e3a-92088f9d46eb.png)
  ```
 * Ubuntu 16.04
 * Gtk+ 3.18
 * Unity 
 * Adapta git version
 ```

**Comment by tista500** [comment]
This is related to Thunderbird codes and/or such add-on itself, and then it's un-fixable.
Since thunderbird enforces GtkMenuBar styling onto GtkToolBar (happens in other Gtk+ themes as well).

Shoudl be fixed in upsteram.

Closed, Regards.

**Comment by Sadi58** [comment]
I understand, but the other theme which does not have this problem made me think that maybe some fix can be implemented about this, although the root cause might lie in the upstream.
