### ISSUE TITLE
Deepin Desktop Environment support 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [tista500/Adapta#241]
Can you add Deepin Desktop support to your adapta theme?? 
I ask this to arc theme owner, no answer

I am using latest Arch Linux,Deepin DE and adapta from AUR;

**Comment by tista500** [comment]
That DE seems the chaos combo Gnome-Shell + Cinnamon + Pantheon... It's funny.
So where is the originality of its design? And I could not find human-interface-guidelines in anywhere. I don't think devs concerned external theming support.

Finally no. Adapta will not support it.

Closed, regards.

**Comment by caoli5288** [comment]
I think deepin do not support custom theme..
