### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by ceyhunnabiyev** [tista500/Adapta#242]
It would be perfect  that dark adapta background color is close to black color(or too dark blue) like in arc-dark-theme

**Comment by tista500** [comment]
Disagreed since night-mode in Android 8.x was not decided to unveil yet.

Closed, regards.

**Comment by ceyhunnabiyev** [comment]
Just I suggest , because your adapta  theme a little bit light  I think, please look at the picture:
![screenshot from 2016-10-11 22-33-33](https://cloud.githubusercontent.com/assets/5506156/19283673/d8dc48ea-9003-11e6-9c3e-f0d6086a3848.png)

I think if  background color of nautilus  is the same with color of sublimetext findandreplace bar, it  would  be more elegant I think. 

---------------------------
Thanks for attention to my questions
