### ISSUE TITLE
Evolution 3.20: Status- and Junk-column looking ugly

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#25]
![bildschirmfoto von 2016-03-26 10-52-32](https://cloud.githubusercontent.com/assets/1418818/14059441/f9e05230-f340-11e5-987f-14825425e960.png)

**Comment by tista500** [comment]
I'm not a evolution user, so I can't understand any issues even if you just put the shot...

Invalid.

Regards.
