### ISSUE TITLE
how to install the theme on gnome 3.18

### ISSUE THREAD

**Issue by arshavindn** [tista500/Adapta#26]
Hi. I clone this repo and do `git checkout 3.18.x` to switch to 3.18.x branch but when I install this theme by `./autogen.sh; make; sudo make install` and it does not work.
![workspace 1_055](https://cloud.githubusercontent.com/assets/10246162/14066467/404ee734-f474-11e5-9514-a7e8116ee8b6.png)

**Comment by tista500** [comment]
@arshavindn,

As your shot, `git checkout` did not switched to 3.18.x branch. after running `autogen.sh`, term said `3.20`...

So how about do this: `git checkout origin/3.18.x`?

Regards.
