### ISSUE TITLE
gtk 3.20 and (probably) HiDPI issue with window bar

### ISSUE THREAD

**Issue by psychonaut** [tista500/Adapta#28]
![zrzut ekranu z 2016-03-28 11-43-50](https://cloud.githubusercontent.com/assets/807289/14075558/80dea382-f4da-11e5-97a7-33a46def789a.png)

I've got hidpi configuration, so GDK_SCALE=2 factor is applied. Top bar looks like have doubled its size.

**Comment by tista500** [comment]
@psychonaut,

Unfortunately I could not reproduce your issue on my Dell XPS 11 (QHD display and scaling-factor=2) and Gtk+ 3.20.1. And even if I've added `GDK_SCALE=2` into `/etc/environments, too.

Basically, Gdk-scaling did not affect to Server-side-decorations, so SSDs would not be scaled with it... But scaling via gsettings key "scaling-factor" will affect to SSDs as well, although font-scaling was not changed properly.

Regards.

**Comment by psychonaut** [comment]
Whatever You did it's fixed now. Thanks!
