### ISSUE TITLE
Gnome Shell theme issue with font scale 1.5

### ISSUE THREAD

**Issue by horosgrisa** [tista500/Adapta#33]
I use Gnome Shell at my FullHD tablet, with font scale 1.5. Default Gnome Shell theme look normal.
![2016-03-29 18-29-23](https://cloud.githubusercontent.com/assets/4980269/14113581/44dee4de-f5dc-11e5-8a15-55a22483ec94.png)

But Adapta theme look ugly
![2016-03-29 18-37-36](https://cloud.githubusercontent.com/assets/4980269/14113845/57e16650-f5dd-11e5-88f3-eac5b1e7cf40.png)

**Comment by tista500** [comment]
@horosgrisa,

That commit will fix this issue.

Regards.

**Comment by horosgrisa** [comment]
It does not fix issue
![2016-03-29 20-42-53](https://cloud.githubusercontent.com/assets/4980269/14117765/d6726c6a-f5ee-11e5-9735-2149eceddf0a.png)

**Comment by tista500** [comment]
@horosgrisa,

??
Which part are you talking about?

Regards.

**Comment by horosgrisa** [comment]
Menu with sound, Wi-Fi status, battery,...

**Comment by tista500** [comment]
2nd fix was committed.

Check it out.

Regards.
