### ISSUE TITLE
Gedit progressbar

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#34]
I accidentally opened a larger zip file with gedit and noticed the bad contrast of the progressbar to its background:

![gedit-loading](https://cloud.githubusercontent.com/assets/526104/14114330/d3fde7d8-f5d6-11e5-8bfe-4c1c9694681e.png)

**Comment by tista500** [comment]
@pschichtel,

I'm not tested well, but I hope it could solve your issue...

Regards.
