### ISSUE TITLE
Menuitem captions in LibreOffice are unreadable

### ISSUE THREAD

**Issue by HeikoAdams** [tista500/Adapta#35]
![bildschirmfoto von 2016-03-31 09-46-58](https://cloud.githubusercontent.com/assets/1418818/14168985/89c2f758-f725-11e5-9da9-750a7edf95c6.png)

**Comment by tista500** [comment]
Upstream bug.

**Comment by zoutiyx** [comment]
@HeikoAdams,

File a bug report here: https://bugs.documentfoundation.org/enter_bug.cgi
