### ISSUE TITLE
huge headerbar on HiDPI displays

### ISSUE THREAD

**Issue by damiango** [tista500/Adapta#38]
Some apps show a huge headerbar and buttons in HiDPI display (3200x1800 @ 96dpi)
Mostly, gtk-2 apps, but not exclusively. gnome-terminal shows the same behavior.

gedit (well rendered) side by side with gnome-terminal (huge):
![seleccion_001](https://cloud.githubusercontent.com/assets/18292503/14293948/696d571a-fb34-11e5-8b79-d91c5ffee873.png)

gedit (well rendered) side by side with google-chrome (huge):
![seleccion_002](https://cloud.githubusercontent.com/assets/18292503/14293965/7db2397a-fb34-11e5-8ab3-5ba5678af349.png)

Normal button size:
![seleccion_003](https://cloud.githubusercontent.com/assets/18292503/14293986/94b23b2a-fb34-11e5-8d24-0c71057907b6.png)

Huge button size:
![seleccion_004](https://cloud.githubusercontent.com/assets/18292503/14294000/9f78404a-fb34-11e5-9069-d342c8a4e926.png)

I tried disabling window scaling in gnome-tweak, and the headerbars render in correct size, but text in those bars keep rendering big.

Gnome: 3.20
GTK+: 3.20
Distro: Fedora 24

**Comment by damiango** [comment]
If I write the following in .config/gtk-3.0/gtk.css the bars work better:

`headerbar {
    min-height: 38px;
    padding-left: 2px;
    padding-right: 2px;
}

headerbar entry,
headerbar spinbutton,
headerbar button,
headerbar separator {
    margin-top: 2px;
    margin-bottom: 2px;
}

.default-decoration {
    min-height: 0;
    padding: 2px
}

.default-decoration .titlebutton {
    min-height: 38px;
    min-width: 38px;
    padding: 2px
}`

![seleccion_005](https://cloud.githubusercontent.com/assets/18292503/14296049/f0a97124-fb3d-11e5-984f-fbe38f3487c0.png)

**Comment by tista500** [comment]
@damiango,

I'm not sure why you tweaked CSDs spacing factors via pixel-based tiny padding, but anyway I've committed fix...

Regards.
