### ISSUE TITLE
Gtk2 Adapta-dark?

### ISSUE THREAD

**Issue by fogzot** [tista500/Adapta#39]
It would be nice to have a dark version for Gtk2, to go together with the "Global dark theme" Gtk3 option.

**Comment by tista500** [comment]
@fogzot,

Hmm, To be honest, I don't like whole dark variant... But someday it may be realized.

Regards.

**Comment by tista500** [comment]
@fogzot,

Today 'Adapta-Nokto' has come.
Please select 'Adapta-Nokto' via Gnome-Tweak-Tool and once enabled 'global dark theme' for Gtk+ 3, All dark variant theming would come...

Regards.

**Comment by fogzot** [comment]
Wooot! GREAT! :)
