### ISSUE TITLE
default font

### ISSUE THREAD

**Issue by MichaelTiebesl** [tista500/Adapta#4]
Hi there, thanks for the great theme. I was already a big fan of the Flat-Plat theme.

What is your default font with this theme? I see for example in Rhythmbox is doesn't show right to me.

Cheers

**Comment by tista500** [comment]
@MichaelTiebesl,

Adapta uses `Robot`, `Lato` and `Cantarell` as default for Gnome-Shell.
I'm happy if you could let me know which part did not render your fonts properly, Gnome-Shell, Mutter/Metacity window-manager, or Gtk+ widget?

Regards.

**Comment by MichaelTiebesl** [comment]
I made an screenshot from Rhythmbox where the font is not showing correctly. On the screenshot itself the font looks better for me then in real. I have it so far only with Rhythmbox in the grey box. Maybe somebody else can confirm this also. 

![schermafdruk van 2016-02-24 19-25-37](https://cloud.githubusercontent.com/assets/10792019/13284333/900aec8c-db2e-11e5-968d-f11e07595351.png)

**Comment by tista500** [comment]
@MichaelTiebesl,

Thanks for uploading shot...
Well, I'm now running rhythmbox 3.3.1 ( stock version of Ubuntu 16.04), so yours looks newer version than mine.

![screenshot from 2016-02-24 22-05-01](https://cloud.githubusercontent.com/assets/6073622/13286256/7d72a398-db43-11e5-8b41-f4c80921eaba.png)

Fonts are "Lato regular 9pt" on budgie-desktop 8.2 (en_US.UTF-8). Seems hard to reproduce your issue precisely on my Laptops? Anyway I wil see the codes around GtkTreeView that I suspect if it has unexpected padding/margin or not...

Regards.

**Comment by tista500** [comment]
Any progress?

Today I could not reproduce this issue with some locales, so please file a new issue if you had this issue still.

Regards.
