### ISSUE TITLE
Tweak tool could not recognize the gtk theme (Ubuntu, Xenial, GTK-3.18)

### ISSUE THREAD

**Issue by khurshid-alam** [tista500/Adapta#40]
Hi,

I just install it from PPA. With gnome-tweak-tool it is not possible to select the theme as "**gtk-3.0**" directory is missing from `/usr/share/adapta`.  It works after If I create a symlink to it.

`ln -s gtk-3.18 gtk-3.0`

**Comment by tista500** [comment]
@khurshid-alam,

Let me see the output of `dpkg -l | grep tweak-tool`. Which version of Tweak-Tool you run?

And
> as "gtk-3.0" directory is missing from /usr/share/adapta

Hey, that directory is now completely outdated. Adapta already moved to multiple versioned theme (quite different from any other themes), so please don't do such thing...

Regards.

**Comment by khurshid-alam** [comment]
I know it is a multiple versioned theme. It didn't work with tweak-tool 3.18 before, but now it does work with tweak-tool 3.20. Thanks.

**Comment by tista500** [comment]
@khurshid-alam,

OK. Nice...

Regards.

**Comment by HEXcube** [comment]
@tista500 Can't the `gtk-3.0` folder be symlinked like @khurshid-alam did, for compatibility with GNOME Tweak Tool 3.18? :confused: Especially considering an LTS version of Ubuntu (16.04LTS) ships Tweak Tool 3.18. Coz, as per https://git.gnome.org/browse/gtk+/tree/gtk/gtkcssprovider.c#n2014 , GTK searches for gtk.css in the directories in decreasing order `gtk-3.20`, ...,`gtk-3.14` and finally `gtk-3.0`.

An even better method would be to rename `gtk-3.18` as `gtk-3.0` coz the minimum requirement for Adapta is GTK3.18. :relaxed: This is how **Numix** does it: https://github.com/shimmerproject/Numix . The `numix-gtk-theme` package from https://launchpad.net/~numix/+archive/ubuntu/ppa contains `gtk-3.0` and `gtk-3.20` folders.

**Comment by tista500** [comment]
@HEXcube,

No.
See https://git.gnome.org/browse/gnome-tweak-tool/commit/?h=gnome-3-16 and https://git.gnome.org/browse/gnome-tweak-tool/commit/?h=gnome-3-18.

It's the decision of GNOME.
And if `gtk-3.0` directory was existed, this causes version conflicts when newer version was landed. Means if theme did not have proper versioned theme direcotry (i.e. `gtk-3.22`), Gtk+ will search `gtk-3.0` directory automatically. It will never help users as "fallback", too.

Please follow the GNOME changes if you want to use GNOME eco-system, or commit the features to upstream with things what you want to do...

Regards.

**Comment by HEXcube** [comment]
K.. I see. But are those patches make it into another point release of Tweak Tool 3.18? :confused: Coz, I haven't seen any GNOME version release patches this late in developement cycle. The official tarballs are still at 3.18.1 : http://ftp.gnome.org/pub/GNOME/sources/gnome-tweak-tool/3.18/ . And it's not likely Ubuntu'll update their `gnome-tweak-tool` package post freeze date.

While I'm happy to use GNOME Tweak Tool 3.20 from Adapta PPA on my GNOME 3.18 system (who doesn't like newer software :grin:  ), isn't it possible to add a `gtk-3.0` during packaging? Like the way it's handled in Solus package?: https://git.solus-project.com/packages/adapta-gtk-theme/tree/package.yml . It'll help the users running vanilla Ubuntu GNOME 16.04LTS. :relaxed:

**Comment by HEXcube** [comment]
> And if gtk-3.0 directory was existed, this causes version conflicts when newer version was landed. Means if theme did not have proper versioned theme direcotry (i.e. gtk-3.22), Gtk+ will search gtk-3.0 directory automatically. It will never help users as "fallback", too.

I don't think that's true. :confused: This is the code from GTK (not Tweak Tool) https://git.gnome.org/browse/gtk+/tree/gtk/gtkcssprovider.c#n2046

````C
for (i = MINOR; i >= 0; i = i - 2)
    {
      if (i < 14)
        i = 0;

      subsubdir = g_strdup_printf ("gtk-3.%d", i);
      path = g_build_filename (base, subsubdir, file, NULL);
      g_free (subsubdir);

      if (g_file_test (path, G_FILE_TEST_EXISTS))
        break;

      g_free (path);
      path = NULL;
    }
````

According to this snippet, GTK repeatedly checks from current GTK version (say `gtk-3.20` and goes through all the versions till `gtk-3.14`). It's only then it'll fall back to `gtk-3.0`. So, I don't really see any harm in including a `gtk3.0` directory/symlink.

**Comment by tista500** [comment]
@HEXcube,

Hey, 
> nly then'll it fall back to `gtk-3.0`.

Isn't it the problem?
If tomorrow Gtk+ 3.22 was landed, then if Adapta did not have `gtk-3.22` directory, Gtk+ will use `gtk-3.0` directory as `gtk-3.22`. I meant this in previous comment... `gtk-3.0` directory now becomes dangerous for me.

Regards.

**Comment by HEXcube** [comment]
Nah, according to that code snippet, once it can't find `gtk-3.22`, it'll try `gtk-3.20`. `gtk-3.0` is the last resort, used only if there's not even a `gtk-3.14` directory. :relaxed:

**Comment by tista500** [comment]
Ah OK... OK..

I will do.

Regards.

**Comment by HEXcube** [comment]
@tista500 Many thanx! :kissing_heart: Looking forward to testing the backward compatible Adapta theme on Solus, budgie-remix and Ubuntu GNOME!  :relaxed:

**Comment by HEXcube** [comment]
I tested the theme on both **Ubuntu GNOME 16.04** Beta (with *GNOME Tweak Tool 3.18*) and **budgie-remix** (through _Raven_ side panel). Now, with the budgie support added yesterday, it looks really great on Budgie desktop! :heart_eyes:

![Adapta with Budgie](https://cloud.githubusercontent.com/assets/3755396/14652461/0e1fd306-0692-11e6-9fec-e0f0a6289714.png)

![Adapta with Budgie Light](https://cloud.githubusercontent.com/assets/3755396/14652471/19188a82-0692-11e6-9470-35a24908445c.png)

**Comment by HEXcube** [comment]
However, there's a small problem: Adapta from PPA pulls in `gnome-tweak-tool` as dependency. :worried: Budgie desktop uses Raven instead of _GNOME Tweak Tool_ and as a result **Solus** and **budgie-remix** don't have it installed by default. @tista500 So, can u remove this dependency and make it possible to install Adapta without GNOME Tweak Tool? :confused:

**Comment by HEXcube** [comment]
Checked the latest package from [Adapta PPA](https://launchpad.net/~tista/+archive/ubuntu/adapta) and it doesn't have dependency on `gnome-tweak-tool` anymore! :relaxed: @tista500 Thanks for solving this issue! :kissing_heart:
