### ISSUE TITLE
Nemo light bg with dark theme

### ISSUE THREAD

**Issue by nos1609** [tista500/Adapta#42]
Nemo v 2.8.7 has no dark background with lastest release  v3.20.2.100 and with v3.20.2.95
Using it on gnome 3.20.0.
![2016-04-09 14-06-30](https://cloud.githubusercontent.com/assets/11856987/14403370/f97058a2-fe64-11e5-9b27-30d9be88b5ce.png)

Everything was fine on v3.20.2.93

**Comment by tista500** [comment]
@nos1609,

Looks really bad...
So I've committed Nemo specific styling: https://github.com/tista500/Adapta/commit/99629dca752d104ec3a50373694d7eddc4fd0da3

Unfortunately Nemo is not my file-manager, so please check the latest master if it could solve your issue (Nemo seems to need old-style GtkNotebook styling yet, too bad)...

Regards.

**Comment by nos1609** [comment]
It woks with the lastest master. Thank You!
