### ISSUE TITLE
Evolution notice contrast in dark mode

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#44]
I started using evolution today and I got this notice in evolution about loading external content:

![evolution](https://cloud.githubusercontent.com/assets/526104/14410811/1aca89f4-ff38-11e5-8dda-edf0d3b3acbe.png)

**Comment by tista500** [comment]
@pschichtel,

I'm not test in actual Evolution, but at least gtk3-demo was fixed...

Regards.

**Comment by tista500** [comment]
I hope it's already fixed...

Regards.

**Comment by pschichtel** [comment]
When the windows has no focus, the focus, the message is still unreadable

**Comment by tista500** [comment]
?? :(

How to reproduce your exact issue?

Regards.

**Comment by pschichtel** [comment]
it is indeed fixed, my system didn't pick up the updated theme last time I tested it.
