### ISSUE TITLE
Chrome title bar should also be dark grey

### ISSUE THREAD

**Issue by jhasse** [tista500/Adapta#45]
When telling Chrome to use the Gtk theme settings, it would be nice if it could use the same background colors for the tab bar as the title bar. I think it's clearer what I mean with some screenshots. This is Chrome with Adapta:

![image](https://cloud.githubusercontent.com/assets/80071/14413700/a26229ea-ff82-11e5-8809-6b2d53d0ad28.png)

And this is Chrome with the Paper Gtk theme:

![image](https://cloud.githubusercontent.com/assets/80071/14413715/027d435a-ff83-11e5-84eb-953857fff932.png)

**Comment by tista500** [comment]
@jhasse,

I did not test yet, but that commit may fix this issue so, please check the latest master...

Regards.

**Comment by jhasse** [comment]
Yes, works! Thanks :)
