### ISSUE TITLE
Gtk 3.20: [_common.scss] Possible typo 'treetiew'

### ISSUE THREAD

**Issue by glitsj16** [tista500/Adapta#46]
Using latest git master I noticed the gtk-3.20 _common.scss file references 'treetiew' on line 1136:

...
// Misc
  treetiew & {
...

Being unfamiliar with the ins & outs of scss I could be mistaken, but it might be a typo if it was meant to read 'treeview' instead. Just wanted to let you know.

Thanks for this awesome theme!

**Comment by tista500** [comment]
@glitsj16,

Ahahaha! My bad... :smile: 
Yeah it's typo so fix will be committed soon.

Regards.
