### ISSUE TITLE
Chrome Theme

### ISSUE THREAD

**Issue by austinbutler** [tista500/Adapta#48]
Any plans for a matching Chrome theme?

If not, the best match I found is this: https://chrome.google.com/webstore/detail/material-for-chrome/gokahbgdhhcjfnjlfeiojfmgnoikpcco?hl=en

**Comment by tista500** [comment]
@austinbutler,

No.
Just to be clear, which part of my theming lacks integrations?
I usually use Epiphany instead of Chrome(ium), so please describe your issue clearly... In some parts, I may or may not fix.

Regards.

**Comment by austinbutler** [comment]
I don't know that there's anything specifically lacking, just curious if that was in the plans or not. To me, though, the theme I linked seems like a better fit than letting it use the defaults form the GTK+ theme. It's really not a big deal though.

Using GTK+ theme:
![screenshot from 2016-04-12 19-48-34](https://cloud.githubusercontent.com/assets/354741/14481475/0e29fde0-00e8-11e6-8c25-886d9979b467.png)

Using theme from Chrome store:
![screenshot from 2016-04-12 19-53-20](https://cloud.githubusercontent.com/assets/354741/14481501/534c51f2-00e8-11e6-8fec-cbf3f1d76d7c.png)

**Comment by tista500** [comment]
@austinbutler,

As of the 1st shot, you seems to use Arc-Dark? Oh please wrong place...

Regards.

**Comment by golimpio** [comment]
The default Adapta GTK theme actually looks good IMHO:

![chrome-screenshot](https://cloud.githubusercontent.com/assets/138681/14564990/4bd1180a-036c-11e6-97bc-bd551ca0348c.png)

**Comment by austinbutler** [comment]
You guys are totally right. I was switching themes and got the names mixed up. :-1: 

Going to go hang my head in shame now...

**Comment by tista500** [comment]
Ah no problem...

But anyway default Adapta is not so good though because inactive tabs had raised materials and used similar foreground colour with active tab. It might not be able to get fine contrast between them...

Regards.
