### ISSUE TITLE
Theme in root

### ISSUE THREAD

**Issue by MichaelTiebesl** [tista500/Adapta#5]
Hi there,

I can't get it right to get Adapta theme showing correctly in root mode. I have it installed in /usr/share/themes with the right permission but it is not showing. I get the default theme from Gnome.

I'm using Arch - Gnome.

Cheers

**Comment by tista500** [comment]
@MichaelTiebesl,

Sorry for my delayed response.
So `sudo cp -r Adapta /usr/share/themes` could not install my theme?

Regards.

**Comment by MichaelTiebesl** [comment]
Yes with your 
> sudo cp -r Adapta /usr/share/themes <

i get it installed. Same happens unfortunately with me.
This is a screenshot of it.

![schermafdruk van 2016-02-24 19-00-44](https://cloud.githubusercontent.com/assets/10792019/13283735/92618aa8-db2a-11e5-8e86-4bc50e847842.png)

**Comment by MichaelTiebesl** [comment]
With the last update this is okay now. Thanks
