### ISSUE TITLE
Some dialog buttons are unreadable

### ISSUE THREAD

**Issue by golimpio** [tista500/Adapta#51]
Some dialog's buttons are almost invisible on Ubuntu/unity:
![some-dialog-buttons-unreadable](https://cloud.githubusercontent.com/assets/138681/14483797/1b4886f8-018e-11e6-9197-27d77d72da62.png)

The one above is when I right click the bin and click on "Empty Rubish Bin...".

Environment:
- Ubuntu 16.04
- GTK 3.18
- Latest Adapta from GitHub (updated today)
- Using the light theme (Global Dark Theme is disable)

**Comment by tista500** [comment]
@golimpio,

Ah, looks bad... :(

I will track this issue soon but please wait a bit more time, since my Unity testing bench are broken with Gtk+ 3.20 so I need to setup fresh stock Xenial in my laptops.

Regards.

**Comment by tista500** [comment]
@golimpio,

Just now I've committed but I've not tested yet though, so please check if that commit could solve your issue properly...

Regards.

**Comment by golimpio** [comment]
Thank you @tista500 !!

The issue seems to be fixed:
![adapta-dialog-ok](https://cloud.githubusercontent.com/assets/138681/14514239/2c582760-0232-11e6-8ae7-64ccea2497bb.png)

**Comment by tista500** [comment]
OK. Nice.. :)

Closed.

Regards.
