### ISSUE TITLE
Title bar sometimes disappears on Ubuntu 16.04

### ISSUE THREAD

**Issue by golimpio** [tista500/Adapta#53]
This is not a new issue, but since Ubuntu 16.04 is not officially launched, I decided to wait a bit until report it.

**Note:** This only happens with GTK2 applications.

Every time I login, the title bar for GTK2 apps is not visible.

To replicate it you have to open a GTK2 app after you login, e.g.:
- CompizConfig Settings Manager (ccsm)
- Atom (or any Electron application)
- Sublime Text Editor

Sometimes, restarting Compiz/Unity solves it (but usually not). Usually I have to set the default Ubuntu theme, login, then after login I change it to Adapta.

But since Compiz is unstable and crashes often, when it restarts I loose the title bar again.

It doesn't happen with other themes as far as I could see.

Environment:
- Ubuntu 16.04
- GTK 3.18
- Latest Adapta from GitHub (updated today)
- Using the light theme (Global Dark Theme is disable)

**Comment by golimpio** [comment]
I suspect that it might be a bug on _Unity_... it seems that _Unity_ doesn't like the units in `em`, changing the units to 'px' seems to fix this issue.

I'll run a few more tests later.

**Comment by golimpio** [comment]
Yes, _Unity_ doesn't like units in `em`.

I've done the following changes to test it and the title bar stopped to disappear:

```
UnityDecoration {
  -UnityDecoration-extents: 28px 0 0 0;
  /*
  -UnityDecoration-extents: 3.4em 1 1 1;
  */
  -UnityDecoration-input-extents: 8px;
  -UnityDecoration-shadow-offset-x: 0px;
  -UnityDecoration-shadow-offset-y: 8px;
  -UnityDecoration-active-shadow-color: rgba(0, 0, 0, 0.24);
  -UnityDecoration-active-shadow-radius: 12px;
  -UnityDecoration-inactive-shadow-color: rgba(0, 0, 0, 0.16);
  -UnityDecoration-inactive-shadow-radius: 6px;
  -UnityDecoration-glow-size: 10px;
  -UnityDecoration-glow-color: #00BCD4;
  -UnityDecoration-title-indent: 10px;
  -UnityDecoration-title-fade: 35px;
/*
  -UnityDecoration-title-indent: 1.5em;
  -UnityDecoration-title-fade: 3.4em;
*/
  -UnityDecoration-title-alignment: 0.0;
}

UnityDecoration.top {
  border: 1px solid rgba(0, 0, 0, 0.09);
  border-bottom-width: 0;
  border-radius: 2px 2px 0 0;
  padding: 1px 6px 0 6px;
/*
    padding: 0.1em 0.4em 0 0.4em;
*/

  background-image: linear-gradient(to bottom, #2a373e);
  color: #ECEFF1;
  box-shadow: inset 0 1px rgba(255, 255, 255, 0.07);
}
```

**Comment by tista500** [comment]
@golimpio,

Wow, great finding you did! :)
Let's convert to px... BTW, what a bad window-manager Compiz was since scalable unit could not be accepted for...

Regards.

**Comment by tista500** [comment]
Fixes were committed... I hope those could solve the issue.

Regards.

**Comment by golimpio** [comment]
It's working for me...thanks for fixing it!!

Yes, compiz is the most buggy/unstable software I've seen/used recently (it used to work well some years ago). I wish I could replace it, because overall I enjoy Unity UX over Gnome Shell (just a personal preference, not because it's better, actually visually speaking, vanilla Gnome 3.20 does look better than Unity to me).

Regards.
