### ISSUE TITLE
[Feature Request] Budgie support

### ISSUE THREAD

**Issue by feskyde** [tista500/Adapta#55]
This is how Budgie looks using Adapta:

![captura de pantalla de 2016-04-15 22-50-19](https://cloud.githubusercontent.com/assets/12128317/14578362/baa25920-035c-11e6-8704-fbeebda29706.png)

You can find how to theme Budgie looking at the [Vertex](https://github.com/horst3180/vertex-theme/search?utf8=%E2%9C%93&q=budgie) code :smile:.

**Comment by tista500** [comment]
@feskyde,

Budgie support was already integrated, so what do you want to ask me? :(

Regards.

**Comment by feskyde** [comment]
I installed the theme from AUR (adapta-gtk-theme), so I will try with the git one, sorry... :)

**Comment by tista500** [comment]
@feskyde,

Your shot seems to be enabled Adapta theming.
Let me know which part you want me to fix.

Regards.

**Comment by feskyde** [comment]
With "Budgie support was already integrated", did you mean for GTK 3.18 only? (I'm using 3.20 on Arch)

![captura de pantalla de 2016-04-15 23-33-00](https://cloud.githubusercontent.com/assets/12128317/14578593/6e6737d2-0362-11e6-8ebc-601d384687a9.png)

Take a look to task manager and Raven's sliders

**Comment by tista500** [comment]
@feskyde,

Read the README.md.
Yes. Gtk+ 3.18.x only. Because the combo Budgie-desktop 10.2.5 + Gtk+ 3.20.3 is out of control for me. So I've dropped integration until fixed. And I will not support in future...

Regards.

**Comment by feskyde** [comment]
Well, thank you

**Comment by tista500** [comment]
@feskyde,

I've just committed new stying for Gtk+ 3.20, so check the git master...

Regards.

**Comment by feskyde** [comment]
**Thanks!**

Just a thing: sliders aren't shown

**Comment by tista500** [comment]
Fix are committed now: https://github.com/tista500/Adapta/commit/e371cf7fc052cb193bddf30f9624621889445fcc

Regards.
