### ISSUE TITLE
Unity launcher remove icon background

### ISSUE THREAD

**Issue by grampa** [tista500/Adapta#57]
Hi,

is it possible to remove icon background in Unity launcher like in Numix GTK theme?
For now it can be done manually - http://askubuntu.com/a/455047

**Comment by tista500** [comment]
@grampa,

I really don't know how Unity7 treats its theme styling, so please check this commit could change the situation in Unity7 ( Because Unity is not my thing ever)...
https://github.com/tista500/Adapta/commit/9cabf5182030de5fef31efd01d19b364d7b14698

Regards.

**Comment by grampa** [comment]
Great, this works.
Also, Unity users can now select theme with Unity Tweak Tool.

**Comment by tista500** [comment]
OK. Closed.

Regards.
