### ISSUE TITLE
Topicons are truncated

### ISSUE THREAD

**Issue by herzmeister** [tista500/Adapta#62]
Hello, this theme is almost perfect.

The only problem I have is with the Topicons extension (I can't live without it). The icons appear truncated.

![Topicons](https://i.imgur.com/MSji4vr.png)    
   
Happens with this theme and Flat-Plat. With all other themes I don't have this problem.

**Comment by tista500** [comment]
@herzmeister,

Which 'Trayicons' extension did you use?
**Trayicons Plus** did not have such issue and truncation is caused the poor extension codes, not ours. Although I've the only tested one legacy systrray of transmission...

**Trayicons Plus** could control icon sizes, so you should set proper size via its settings window.

Regards.

**Comment by herzmeister** [comment]
thanks, i wasn't aware of other variants. i'm using https://github.com/phocean/TopIcons-plus now.

**Comment by tista500** [comment]
OK. Closed.

Regards.
