### ISSUE TITLE
nemo pathbar arrow button

### ISSUE THREAD

**Issue by arshavindn** [tista500/Adapta#63]
![nemo3](https://cloud.githubusercontent.com/assets/10246162/14807952/553d32ec-0bab-11e6-81b2-ac92746eeea4.png)
over the cursor is arrow button but it does not show arrow, and the style seems wrong too

**Comment by tista500** [comment]
@arshavindn,

Hey, why you guys don't explain your environments? :(
I don't know who you are, and I don't know which version of Nemo you guys use...

How to track down the issues without those info, tell me.

Invalid.

**Comment by arshavindn** [comment]
I'm using ubuntu gnome 16.04 gnome version 3.18

**Comment by tista500** [comment]
Let me see the output of these commands:
```
dpkg-query --show libgtk-3-0
dpkg-query --show nemo
```

Those are what I want to know...

Regards.

**Comment by arshavindn** [comment]
`libgtk-3-0:amd64	3.18.9-1ubuntu3`
`nemo	2.8.7-1~webupd8~xenial07`

**Comment by tista500** [comment]
OK. Fix was committed...

Closed.

**Comment by arshavindn** [comment]
it still does not fix for me
