### ISSUE TITLE
Gtk+ 2.0 applications not themed at all

### ISSUE THREAD

**Issue by nlaplante** [tista500/Adapta#64]
I tried Google Chrome, Chromium and gtk-demo. All of them are using the ugly windows-95-esque default gtk-2 theme.

I have the pixmap engine located at:
`/usr/lib64/gtk-2.0/2.10.0/libpixmap.so`

Fedora 23. 

Everything works fine in Gtk-3. Do I miss something?

**Comment by tista500** [comment]
@nlaplante,

Sounds strange...
Where/How did you install Adapta?

Regards.

**Comment by nlaplante** [comment]
How I installed:
```
./configure --prefix=/home/${USER}/.local
make
make install
```

When running `GTK2_RC_FILES=~/.local/share/themes/Adapta/gtk-2.0/gtkrc gtk-demo`, it works and the theme is applied.

**Comment by tista500** [comment]
Is this issue related Adapta specific?? :(

If I remembered well, Gtk+ 2.0 did not check `~/.local/share/themes` directory to pull `gtkrc` file. Use `~/.themes` for Gtk+ 2.0.

Regards.

**Comment by nlaplante** [comment]
That did it!

```
ln -sf ~/.local/share/themes ~/.themes
```

Thank you very much!

**Comment by tista500** [comment]
Or another way:

eport environment from `.profile` like this:
```
export GTK2_RC_FILES=$HOME/.local/share/themes/Adapta/gtk-2.0/gtkrc
```

Because once you've linked those 2 dirs, maybe Gnome-Tweak-Tool listed twice in all of themes localted in `~/.local/share/themes` directory (g-t-t bug). So exporting env might be smarter a bit...

Regards.

**Comment by nlaplante** [comment]
Thanks for the tip, but exporting means I have to choose theme in Tweak Tool for GTK3 and edit the profile var for GTK2. Less work with symbolic link!
