### ISSUE TITLE
LibreOffice menu unreadable

### ISSUE THREAD

**Issue by vibeast** [tista500/Adapta#66]
**Reporter info**

 ```
 * Distribution - Manjaro Cinnamon
 * Gtk+ version - gtk2 = 2.24.30-1; gtk3 = 3.20.3-1
 * Desktop environment - Cinnamon 3.0.1
 ```

**Adapta version (if you knew)**
Last from github

**Related Application and/or Shell theming (or name of widget)**
LibreOffice Version: 5.1.2.2.0

**Actual issue**
LibreOffice menu unreadable.
![screenshot from 2016-04-28 13-36-59](https://cloud.githubusercontent.com/assets/18408100/14893912/92ee83c8-0d47-11e6-8dbf-389754a2e2e9.png)

**How to reproduce (if you knew)**
I don't know

**Expected behaviour**
![screenshot from 2016-04-28 13-50-07](https://cloud.githubusercontent.com/assets/18408100/14894073/4444261e-0d48-11e6-9848-d19686775e2a.png)

**Other Note (feature-request, question, etc...)**

**Comment by arshavindn** [comment]
it's upstream bug, and also duplicated issue #35, so please search for closed issues before post new one

**Comment by vibeast** [comment]
Ok, sorry.
