### ISSUE TITLE
maximize button

### ISSUE THREAD

**Issue by vibeast** [tista500/Adapta#67]
**Reporter info**

 ```
 * Distribution - Manjaro Cinnamon 
 * Gtk+ version - gtk3 = 3.20 gtk2 = 2.24
 * Desktop environment - Cinnamon 3.0.1
 ```

**Adapta version (if you knew)**
Last from git.

**Related Application and/or Shell theming (or name of widget)**
Metacity ?

**Actual issue**
![screenshot from 2016-04-29 23-11-59](https://cloud.githubusercontent.com/assets/18408100/14933278/cd4a58f8-0e5f-11e6-9bc5-7fab6c053209.png)

**How to reproduce (if you knew)**
I don't know

**Expected behaviour**
- + x ?

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
Ah now I'm refactoring all of window-manager buttons, so it might happen while I'm converting them...

Regards.

**Comment by vibeast** [comment]
Ok, looks very nice now.

I'd never seen this maximize style, very nice.

Regards
