### ISSUE TITLE
No text Polari

### ISSUE THREAD

**Issue by MichaelTiebesl** [tista500/Adapta#7]
I can't see any text from the name of the room in Polari when i open that room.

![schermafdruk van 2016-02-25 10-11-37](https://cloud.githubusercontent.com/assets/10792019/13307779/db013122-dba8-11e5-8634-21727479a139.png)
![schermafdruk van 2016-02-25 10-11-33](https://cloud.githubusercontent.com/assets/10792019/13307783/e791019c-dba8-11e5-864a-8dfb5c7bc4e8.png)

**Comment by tista500** [comment]
I just now added Polari fix into master, so please check if it could solve your issue...

Regards.

**Comment by MichaelTiebesl** [comment]
Sorry it is still the same after i update it.

**Comment by tista500** [comment]
OK...

Now just updated this fix again. Polari seems its own css what it was hardcoded so that I could not override its ugly stylesheed, yeah it's really mad for me.

Regards.

**Comment by MichaelTiebesl** [comment]
No problem. The rest of your beautiful makes it's acceptable for me. I see other theme have the same issue. Thanks.
