### ISSUE TITLE
GDM (Lock/Login Screen)

### ISSUE THREAD

**Issue by zoutiyx** [tista500/Adapta#70]
Is there a possibility that the Flat Plat Lock/Login Screen can be ported for Adapta?

**Comment by tista500** [comment]
@zoutiyx,

From the start, I've already bundled `gresource` file insdie the `gnome-shell` directory, so it should work same as Flat-Plat...

Didn't it work now!?

Regards.

**Comment by Rahh1112** [comment]
It didn't work for me..all that i get is a black and resetting gdm :/ (maybe i'm doing something wrong?)

**Comment by tista500** [comment]
?? :(

Current gresource file works for me in both GNOME 3.18, 3.20 and even on git master as well.

Regards.

**Comment by Defman21** [comment]
How should it looks btw? I'm using Fedora 24 with Gnome 3.20 but seems like it doesn't work for me.

**Comment by tista500** [comment]
NO progress so just close this.

Regards.

**Comment by ceyhunnabiyev** [comment]
Hi @tista500 ,  How about gdm background image?  How do I set it manually?

**Comment by Feichtmeier** [comment]
The GDM commands from flat plat repo totally work for both 16.04 and 17.04 with adapta! Tested it on two machines:
GTK_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")
sudo cp -v --backup /usr/share{/themes/$GTK_THEME,}/gnome-shell/gnome-shell-theme.gresource

Just sayin'
