### ISSUE TITLE
Missing newtab icon for firefox

### ISSUE THREAD

**Issue by drdeimos** [tista500/Adapta#72]
**Reporter info**

No newtab icon in Firefox 46. When run firefox:
`(firefox:4062): Gtk-WARNING **: Error loading theme icon 'list-add' for stock: Icon 'list-add' not present in theme Adapta
`

 ```
 * Distribution - Ubuntu 16.04
 * Gtk+ 3.0 version -
 * Desktop environment - No. bspwm
 ```

**Comment by tista500** [comment]
@drdeimos,

Why don't you obey the issue format?
Anyway it's not the issue of Gtk+ theme but icon theme, so contact a author of your current icon pack theme.

Invalid and could not reproduce.

Regards.
