### ISSUE TITLE
Pie chart missing

### ISSUE THREAD

**Issue by gregorydk** [tista500/Adapta#73]
**Reporter info**

 ```
 * Distribution - Debian
 * Gtk+ 3.0 version -
 * Desktop environment - GNOME 3.20
 ```

**Adapta version (if you knew)**
Latest

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Pie chart not showing with available and used space on mounted drives.

**Steps to reproduce (if you knew)**
Right-click on mounted drive and choose Properties.

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
https://github.com/tista500/Adapta/commit/3984399e1e012cbcf670e6467a276c5d939d1a3e

Fix committed.

Regards.
