### ISSUE TITLE
Libreoffice Menu Bar

### ISSUE THREAD

**Issue by vinadoros** [tista500/Adapta#75]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.3 (gtk2 version is 2.24.30, if that is needed)
 * Desktop environment - GNOME 3.20
 ```

**Adapta version (if you knew)**
3.21.1.62

**Related Application and/or Shell theming (or name of widget)**
LibreOffice Writer v5.1.2.2 (https://www.archlinux.org/packages/extra/x86_64/libreoffice-fresh/). I am using Adapta as the GNOME Shell theme. I believe LibreOffice is rendering using GTK2 in Arch.

**Actual issue**
The menubar at the top (File, Edit, etc...) has font colors which blend with the background (a light color font). The font color for content inside of the menus is just fine though (black font).

Screenshot:
![screenshot from 2016-05-04 10-03-56](https://cloud.githubusercontent.com/assets/6318224/15016638/2066cb60-11e0-11e6-967d-52d62f5a8b7f.png)

**Steps to reproduce (if you knew)**
Loading Libreoffice Writer should show the issue immediately.

**Expected behaviour**
Expected contrasting colors to be able to see the menu headers properly.

**Other Note (feature-request, question, etc...)**

**Comment by arshavindn** [comment]
#43

**Comment by vinadoros** [comment]
Whoops, this is a dupe. Closing.
