### ISSUE TITLE
Close button out of shape

### ISSUE THREAD

**Issue by victormoreira** [tista500/Adapta#76]
**Reporter info**

 ```
 * Distribution - Manjaro Cinnamon 
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Cinnamon 3.0.1
 ```

**Adapta version (if you knew)**
Last from git.

**Related Application and/or Shell theming (or name of widget)**
Close button on cinnamon 

**Actual issue**
![screenshot from 2016-05-05 23-11-29](https://cloud.githubusercontent.com/assets/13660595/15062489/d1666402-1316-11e6-81fb-343b0e95045a.png)
![screenshot from 2016-05-05 23-11-49](https://cloud.githubusercontent.com/assets/13660595/15062495/d665572e-1316-11e6-9450-aa63940711c8.png)

**Steps to reproduce (if you knew)

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@victormoreira,

Let me know some additional info:
* font-name used in window-manager
* font-size used in window-manager
* font-scaling-factor
* HiDPI scaling factor

Regards.

**Comment by victormoreira** [comment]
Cantarell Bold 11
Slight RGBA 1.0

**Comment by tista500** [comment]
OK.

Now fix was committed: https://github.com/tista500/Adapta/commit/ea510b973f43a5f0e8cd8ce6d22d2e05f72e35e3

Closed.
