### ISSUE TITLE
Unreadable text in dconf Editor popup

### ISSUE THREAD

**Issue by elxa** [tista500/Adapta#78]
**Reporter info**

 ```
 * Distribution - gentoo
 * Gtk+ 3.0 version - 3.20.2
 * Desktop environment - gnome 3.20
 * dconf Editor version - 3.20.0
 ```

**Adapta version**

```
3.21.1.91
```

**Screenshot showing a popup in dconfig editor directly after startup**
![dconf editor screenshot]
(http://i.imgur.com/C5vnIwf.png)

The dark text to the right of the checkbox says "Show this dialog next time."

**Comment by elxa** [comment]
**Running dconf-editor with GTK_DEBUG=interactive**

![]
(http://i.imgur.com/C05Ka6q.png)

![]
(http://i.imgur.com/YJ8jkpc.png)

**Comment by tista500** [comment]
@elxa,

I've already passed that warning dialog, so check if committed fix was fixed this issue.

Regards.

**Comment by elxa** [comment]
@tista500 ,

Thanks, it's fixed.

![]
(http://i.imgur.com/URaJmOO.png)

**Comment by tista500** [comment]
OK. good...

Then closed.

Regards.
