### ISSUE TITLE
Problem with fonts in the shell

### ISSUE THREAD

**Issue by ivandotv** [tista500/Adapta#80]
Ubuntu Gnome 16.04
Gnome
Latest - from the ppa
Shell problem

Fonts issue.
![screenshot from 2016-05-10 11-31-02](https://cloud.githubusercontent.com/assets/390700/15142011/5b61ea5c-16a3-11e6-9211-25e919f21dd8.png)
![screenshot from 2016-05-10 11-31-21](https://cloud.githubusercontent.com/assets/390700/15142015/5db89832-16a3-11e6-9163-1ab78f6aaedf.png)

**Comment by tista500** [comment]
@ivandotv,

Why did you ignore issue template?

Invalid.
