### ISSUE TITLE
Nokto: Gnome Software unfree hint not very readable

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#83]
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.20.4
 * Desktop environment - GNOME 3.20
 ```

**Adapta version (if you knew)**
3.21.1.122

**Related Application and/or Shell theming (or name of widget)**
Gnome Software

**Actual issue**
White text on a light blue background is not good to read

![bildschirmfoto von 2016-05-10 17-29-42](https://cloud.githubusercontent.com/assets/526104/15152270/e17059d6-16d4-11e6-9ac5-904a2751852c.png)

**Steps to reproduce (if you knew)**
Open any potentially non-free package in Gnome Software while using the Nokto theme

**Expected behaviour**
More readable text

**Comment by tista500** [comment]
@pschichtel,

Confirmed and fixed.

Regards.
