### ISSUE TITLE
Tabbar Height and shadow-effect in Gedit

### ISSUE THREAD

**Issue by demoy** [tista500/Adapta#84]
**Reporter info**

 ```
 * Distribution -
 * Gtk+ 3.0 version -
 * Desktop environment - 
 ```
Fedora rawhide
Gtk+ 3.20
Gnome

**Adapta version (if you knew)**
at commit 798

**Related Application and/or Shell theming (or name of widget)**
Gedit (Mainbar/Toolbar and Tabbar) version 3.20.2

**Actual issue**
[1] The Gedit toolbar lacks shadows separating it from the textarea and tabbar.
[2] Gedit tabbar height looks gigantic.
![screenshot from 2016-05-11 13-33-58](https://cloud.githubusercontent.com/assets/2396524/15192044/0e015088-177d-11e6-9d58-2c7e8a88d24f.png)

**Steps to reproduce (if you knew)**
Open Gedit (lol).

**Expected behaviour**
Consistent shadowing and tab height size relative to other applications. such as Nautilus below,
![screenshot from 2016-05-11 13-33-43](https://cloud.githubusercontent.com/assets/2396524/15192050/1260ceec-177d-11e6-9d1d-d849aebc79b6.png)
(dimensions are roughly the same as Gedit image above)

**Other Note (feature-request, question, etc...)**
For my future reference, should I post multiple issues for the same application together.

**Comment by tista500** [comment]
@demoy,

>  [1] The Gedit toolbar lacks shadows separating it from the textarea and tabbar
No, it can't. Because of the limitation of Gedit's stupid codes.

> [2] Gedit tabbar height looks gigantic
Fix was committed: https://github.com/tista500/Adapta/commit/a702e1cabff28c70fe5957dac28dc562010cba4f

Regards.
