### ISSUE TITLE
Background color with intellihide "Dash to Dock" and "Workspaces to Dock"

### ISSUE THREAD

**Issue by dsboger** [tista500/Adapta#85]
**Reporter info**

 ```
 * Distribution - Antergos
 * Gtk+ 3.0 version - 3.20.4
 * Desktop environment - GNOME Shell
 ```

**Adapta version (if you knew)**

3.21.1.128

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

I'm using the "Dash to Dock" and "Workspaces to Dock" extension that allows me to put the dash and workspaces as intellihide sidebars. The problem is that Adapta theme sets these components with transparent background, making them hard to use in that way. Both extensions allow me to tune the opacity of the widget, but if I make them opaque they become black, not matching with the rest of the theme. Is it possible to change the background color of both widgets so that when they are made opaque they will have the same color as the panel? It would not change the default theme, as the backgrounds are transparent. Thanks!

Thanks!

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@dsboger,

I don't think those extensions are useful so I did as possible as I could now.
Fix was committed: https://github.com/tista500/Adapta/commit/5a74ca25aca383cafbd294bbed74827eade1834a

Regards.

**Comment by dsboger** [comment]
Thank you very much for your effort! It worked for the Dash to Dock side, but the Workspace to Dock is still black.

**Comment by alex285** [comment]
@tista500 See here
https://github.com/passingthru67/workspaces-to-dock#theme-support
You only need to include a "workspaces-to-dock.css" inside shell theme. 
Let me check if that works

**Comment by alex285** [comment]
@tista500 Okay I tested it. The docs on the link are wrong. What works is this:
Adapta/gnome-shell/extensions/workspaces-to-dock/workspaces-to-dock.css
Adapta-Nokto/gnome-shell/extensions/workspaces-to-dock/workspaces-to-dock.css

I can write the patches to match both themes if you want to.

**Comment by alex285** [comment]
I didn't pull a request, but this is how it works about. That changes the color or workspaces to fit Adapta, plus makes the border to 2px like Adapta.  It also has images, that I didnt edit at all. 

https://github.com/alex285/Adapta/commit/62b9b6229c0553cbbabbb70d8541d9f71d20d7f8

**Comment by tista500** [comment]
@alex285,

Ah, basically extension author's stylesheet is not matched with Adapta's coding style...
Means I have to rewrite from scratch, both codes and pixmaps.

Hmm, need much more time...

Regards.

**Comment by tista500** [comment]
Specific styling was added: https://github.com/tista500/Adapta/commit/6da3a4981fac6c2e0fcdc99277f05dc051b3fde4

I don't know it works well or not though...

Regards.

**Comment by alex285** [comment]
@tista500 It works fine. Thank you!
