### ISSUE TITLE
Dart theme - Audacity progress barr

### ISSUE THREAD

**Issue by mike227** [tista500/Adapta#86]
**Reporter info**

 ```
 * Distribution - Debian Jessie
 * Gtk+ 3.0 version -
 * Desktop environment - i3
 ```

**Adapta version (if you knew)**
commit 5a74ca25aca383cafbd294bbed74827eade1834a

**Related Application and/or Shell theming (or name of widget)**

Audacity

**Actual issue**

Audacity progress bar colors: Can not recognize progress  

![image](https://cloud.githubusercontent.com/assets/6150394/15267081/e336e5e2-19b7-11e6-8934-eb63ad27b246.png)

![image](https://cloud.githubusercontent.com/assets/6150394/15267083/f5b45740-19b7-11e6-9552-60ac1081804c.png)

**Comment by tista500** [comment]
Report Gtk+ version and audacity version.

Regards.

**Comment by tista500** [comment]
Jessie employs Gtk+ 3.14.x as default, so Adapta doesn't support.

Closed.

**Comment by mike227** [comment]
I updated to the gtk 3.20.3-2 (stretch) version, but the problem persists. Audacity version is 2.1.2.

**Comment by tista500** [comment]
OK.

This issue was fixed: https://github.com/tista500/Adapta/commit/2a4fbbdbd0e14879af2c8f5bb50859312a08225f

Regards.
