### ISSUE TITLE
White text on white background in Legacy Tray

### ISSUE THREAD

**Issue by gregorydk** [tista500/Adapta#87]
On GNOME 3.20 (arrow is not visible).
Also some extensions have white text on white background.

![scrrenshot adapta legacy tray 2016-05-14](https://cloud.githubusercontent.com/assets/7804464/15269755/abf8ef60-1a09-11e6-83cf-a72bca098bd7.png)

**Comment by tista500** [comment]
Already fixed: https://github.com/tista500/Adapta/commit/b573606f6ddfcd7046d820088c9e3235c466de3d

Regards.
