### ISSUE TITLE
Theme no longer renders.

### ISSUE THREAD

**Issue by user501254** [tista500/Adapta#88]
**Reporter info**

 ```
 * Distribution - Fedora 23
 * Gtk+ 3.0 version - gtk3-3.18.9-1.fc23.x86_64
 * Desktop environment - GNOME (GNOME Shell 3.18.5)
 ```

**Adapta version (if you knew)**
[3.21.1.162](https://github.com/tista500/Adapta/releases/tag/3.21.1.162)

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Theme no longer renders. 
GTK+ On selecting *Adapata* or *Adapta-Nokto* under gnome-tweak tool, it just reverts to the default look; while there's no option for *Adapata* or *Adapta-Nokto* under Shell theme dropdown.

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**
The release notes for [3.21.1.162](https://github.com/tista500/Adapta/releases/tag/3.21.1.162) say:
> Release for Gtk+ 3.21.1/3.20.4/3.18.9 and Gnome-Shell 3.20.2/3.18.5  

But clearly, it's not working for me. Not sure if something is wrong with my configuration.

Thanks for the wonderful theme, I really like it. :-)

**Comment by tista500** [comment]
@user501254,

>  Not sure if something is wrong with my configuration.

You should report "steps to reproduce" before you said that.
All of Fedora people does like that in bug reports? :(

Anyway remove `Adapta` and `Adapta-Nokto` directories and re-install them.

Regards.

**Comment by user501254** [comment]
I thought I had remove the folders but clearly it was still there. 
Works fine now. Thanks :-)
