### ISSUE TITLE
Notification box seems to be a bit too small

### ISSUE THREAD

**Issue by Nikki1993** [tista500/Adapta#9]
Hey there @tista500 

Here is what I meant with notification box 

![notification](https://cloud.githubusercontent.com/assets/1446529/13391342/8e11cbd8-dedc-11e5-99fd-0038ebfdbce4.png)

Maybe increase the overall size and add padding so it seems more consistent. 

Can you also point me to the direction of css class or id that affects the notification box size? I tried editing multiple classes to no avail, I am interested in learning shell theming :)

**Comment by tista500** [comment]
@Nikki1993,

Unfortunately I'm not a specialist of Gnome-Shell theming but it may be easy to enlarge that 'banner' box width and height:
``````
diff --git a/gnome-shell/_common.scss b/gnome-shell/_common.scss
index c426f54..bf02ffe 100644
--- a/gnome-shell/_common.scss
+++ b/gnome-shell/_common.scss
@@ -1808,6 +1808,7 @@ StScrollBar {
 .notification-banner {
   width: 34em;
   margin: 5px;
+  padding: 1.2em 1em 0;
   border: none;
   border-radius: 2px;
   font-size: 11pt;
@@ -1819,20 +1820,24 @@ StScrollBar {
   &:focus { background-color: $bg_color; }
 
   .notification-icon { padding: 5px; }
+
   .notification-content {
     padding: 5px;
     spacing: 5px;
   }
   .secondary-icon { icon-size: 1.09em; }
   .notification-actions {
-    padding-top: 0;
+//    padding-top: 0;
+    padding: 0 1em 1.2em;
     border-top: 1px solid $fill_color;
     spacing: 1px;
     background-color: transparent;
   }
 
   .notification-button {
-    padding: 9px 4px 10px;
+//    padding: 9px 4px 10px;
+    padding: 0;
+    margin: 0 1em 1.2em;
     background-color: transparent;
     color: $secondary_fg_color;
     font-weight: 500;
```

However, if you'd like to enlarge the area of its *contents*, it will also need to fix elsewhere, like notification-center in the popup of top-bar clock. Then notification-banner has the dynamic action buttons (in usual, those are adaptively attached by the parent action, like 'mount media'), so only well-designed spacing factors would be accepted for it. Meanwhile I don't think I should re-design such banners anyway...

Regards.

**Comment by tista500** [comment]
Ah, Arc theme seems like to add simply symmetric padding into banner:
```
// Banners
.notification-banner,
.notification-banner:hover,
.notification-banner:focus {
  font-size: 1em;
  width: 34em;
  margin: 5px;
  padding: 10px;
  color: $fg_color;
  background-color: transparent;
  border: 1px solid transparent;
  border-image: url("#{$asset_path}/menu/menu.svg") 9 9 9 9;
```
Regards.

**Comment by Nikki1993** [comment]
I edited width and height but it seems to have no effect.

I do it this way, edit .scss (I use sass --watch command) move theme to /usr/share/themes with sudo rsync -av command and then reboot the shell by ALT+F2 and typing R. Is that a correct way of testing changes or not? and is there a better one perhaps?

P.S. Reasons why I asked where to edit is because I wanna try and contribute to the theme where I can/makes sense. This is a great place to learn and get some feedback :) hope you don't mind

**Comment by tista500** [comment]
@Nikki1993,

> edit .scss (I use sass --watch command) move theme to /usr/share/themes with sudo rsync -av command and then reboot the shell by ALT+F2 and typing R

Why don't you use `parse-sass.sh` script to generate css stylesheets? this script based on `bundle` ruby management system, so you don't need to define each scss files to generate a single css. 

Regards.

**Comment by Nikki1993** [comment]
I used that, just made sense to hook sass directly since I was making changes and constantly alt'tabbing got annoying xD but I just tried with parse-sass.sh as well and there seems to be no difference.

**Comment by tista500** [comment]
Any progress?

Just closed at this point. So please re-open it if you had such issue.

Regards.
