### ISSUE TITLE
Unthemed shortcuts window

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#90]
**Reporter info**

 ```
 * Distribution - Arch linux
 * Gtk+ 3.0 version - 3.20.2
 * Desktop environment - Gnome
 ```

**Adapta version (if you knew)** The latest git version

**Related Application and/or Shell theming (or name of widget)** Shortcuts window

**Actual issue** Keyboard shortcuts are unthemed
![capture du 2016-05-15 21-36-35](https://cloud.githubusercontent.com/assets/7660997/15276338/5feca31e-1ae5-11e6-8d68-9ae40df6a925.png)

**Expected behaviour** how it looks like using an other theme (Flat-Plat on the screenshot)
![capture du 2016-05-15 21-39-08](https://cloud.githubusercontent.com/assets/7660997/15276342/788ae430-1ae5-11e6-9308-2e763c33defa.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@bil-elmoussaoui,

Confirmed and fixed: https://github.com/tista500/Adapta/commit/99de3d5f44520fee65f70227f3add2b992fd5428

Regards.
