### ISSUE TITLE
White text

### ISSUE THREAD

**Issue by stelariusinfinitek** [tista500/Adapta#91]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - latest
 * Desktop environment - XFCE (latest)
 ```

**Adapta version (if you knew)** latest

**Related Application and/or Shell theming (or name of widget)** : Various settings dialogs

**Actual issue** Text is not visible in some dialogs because it is white. Text appears black if I hover the mouse over it.

**Steps to reproduce (if you knew)** Open Window Manager. Text is white and the background is white too.

**Expected behaviour** The text should be black.

**Other Note (feature-request, question, etc...)** I'm attaching an image : http://i.imgur.com/9KBsOJQ.png

**Comment by tista500** [comment]
@stelariusinfinitek,

Confirmed and fixed: https://github.com/tista500/Adapta/commit/ab6e7af8aff1fef0143e70ad11777709ab142dd7

Regards.
