### ISSUE TITLE
White square over icons

### ISSUE THREAD

**Issue by stelariusinfinitek** [tista500/Adapta#92]
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - latest
 * Desktop environment - Xfce
 ```

**Adapta version (if you knew)** latest

**Related Application and/or Shell theming (or name of widget)**

**Actual issue** A white square appears over some icons in notifications. Here is a photo : http://i.imgur.com/zOWgnCT.png

**Steps to reproduce (if you knew)**

**Expected behaviour** I think that a transparent (but not fully transparent) square would be better.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@stelariusinfinitek,

I don't know your 'latest' since I'm not an Arch user. File a report more precisely, please.
And stop using external link to put images. Use Github becuase some hosting services cause security issues.

So which systray icon had such raised button appearance?

Regards.

**Comment by stelariusinfinitek** [comment]
I'm sorry, I'm a bit new to github. By latest I mean the latest stable version. I'll be more precise.

The audio systray icon is the problem. Audio Mixer (external).

**Comment by stelariusinfinitek** [comment]
I have an idea. Can you replace that square with a blue line at the bottom, like you did with others (Window Buttons for example). That would be great.

**Comment by tista500** [comment]
> I have an idea. Can you replace that square with a blue line at the bottom, like you did with others (Window Buttons for example). That would be great. 

Hey please don't mix bug fixing with implementation... :(
And there's no item named "Audio Mixer (external)" in my XFce4 4.12 on Ubuntu 16.04.
We only have "PulseAudio Plugin" in audio category ("Panel" -> "Add new items"). So let me know where is the source package what contains such systray icon.

Regards.

**Comment by stelariusinfinitek** [comment]
I think I am stupid. Okay, I get it :D You are better than me at fixing this, it was just an idea. 

The item is xfce4-mixer, I think you can find it in the repository. You're doing an amazing job, thank you!

![screenshot_2016-05-16_15-41-32](https://cloud.githubusercontent.com/assets/18717816/15289732/b9b893a2-1b7c-11e6-9537-83fbfa8d4f45.png)

**Comment by tista500** [comment]
Ah, thanks for tracking package... It seems `xfce4-mixser` is now outdated and was dropped from Ubuntu 16.04.

I need a bit more time to track down, so please use other appindicators and/or plugin to control sound volume until I can find the way to fix it...

Regards.

**Comment by stelariusinfinitek** [comment]
It's a minor problem, aesthetic. If you need some files, I can provide that. Also, I'll test. I'm using the latest git of Adapta, compiled today.

**Comment by tista500** [comment]
Fix was committed. And I hope Arch also could implement some other/newer applet for VolumeControl...

Regards.

**Comment by stelariusinfinitek** [comment]
Thank you so much!

![screenshot_2016-05-16_16-29-02](https://cloud.githubusercontent.com/assets/18717816/15290782/72a0bfec-1b83-11e6-92d3-acbc33724f21.png)

**Comment by tista500** [comment]
OK. Good...

Closed.
