### ISSUE TITLE
Correctly theme Corebird

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#96]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)** Corebird

**Actual issue**
The top buttons are unthemed and uses the default theme colors
![capture du 2016-05-17 12-19-38](https://cloud.githubusercontent.com/assets/7660997/15319157/c3d26220-1c29-11e6-8cb0-52a67f72b4c3.png)
The buttons nodes are `.horizontal.topbar .image-button`

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@bil-elmoussaoui,

Hey, Have you ever seen the themes what could override corebird's `style.css`? Unfortunately I haven't.

Let me know such themes...

Regards.

**Comment by bil-elmoussaoui** [comment]
You're right, it's hardcoded! i've tried using Gtk Inspector but it's seems that does not detect if the theme uses the default style or not..

**Comment by tista500** [comment]
Yes. Out of control.

Closed.
