### ISSUE TITLE
Unthemed borders on terminix

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#97]
**Reporter info**

 ```
 * Distribution -Arch
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 
 ```

**Adapta version (if you knew)** The latest git version

**Related Application and/or Shell theming (or name of widget)**
Terminix

**Actual issue**
![capture du 2016-05-17 13-41-33](https://cloud.githubusercontent.com/assets/7660997/15321184/2c5745f8-1c35-11e6-8308-63262ec2d2d7.png)

**Steps to reproduce (if you knew)**
1 - Install Terminix
2 - split the terminal vertically or horziontaly 
2 - empty(transparent) border bettween the two terminals

**Expected behaviour**

The same application with Flat-Plat theme
![capture du 2016-05-17 13-43-51](https://cloud.githubusercontent.com/assets/7660997/15321234/70d4d6be-1c35-11e6-8190-ab687f471a8c.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
1st trial fixing: https://github.com/tista500/Adapta/commit/812c276b8ce6464ba8e5584f21b280fe5f997278

Regards.
