### ISSUE TITLE
Huge headerbars on FeedReader

### ISSUE THREAD

**Issue by bil-elmoussaoui** [tista500/Adapta#98]
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Gnome 
 ```

**Adapta version (if you knew)** The latest git version

**Related Application and/or Shell theming (or name of widget)** Few applications , example : FeedReader, the widget : HeaderBar

**Actual issue**
![capture du 2016-05-17 13-46-19](https://cloud.githubusercontent.com/assets/7660997/15321280/c0928570-1c35-11e6-9d54-567c7eecd02a.png)

**Steps to reproduce (if you knew)**
Just use FeedReader (couldn't reproduce that with an other application)

**Expected behaviour**
![capture du 2016-05-17 13-45-54](https://cloud.githubusercontent.com/assets/7660997/15321289/d0256f02-1c35-11e6-976c-48ec3074acc4.png)

Or the same application with Flat-Plat
![capture du 2016-05-17 13-47-35](https://cloud.githubusercontent.com/assets/7660997/15321309/ec7c747a-1c35-11e6-9fd8-11ff7f3f8300.png)

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@bil-elmoussaoui,

You said *some*, so any other?
If you don't know, rewrite issue title.

Regards.

**Comment by tista500** [comment]
@bil-elmoussaoui,

Fix was committed: https://github.com/tista500/Adapta/commit/90fdf9f9035e0916b0d3edae3477cd953bb4511b

Don't forget to restart daemon before evaluating the fix...

Regards.
